### ISSUE TITLE
Feedback on Tutorial: Start Using SAP HANA, express edition

### ISSUE THREAD

**Issue by siliconchris1973** [SAPDocuments/Tutorials#1158]
Great tutorial. 

I had my very own SAP Hana Express Edition up and running in no time.

However, one very important piece of information I am still missing. If I call up the WebIDE in my browser, I'm presented with a login  screen. But I have no idea, which user/password to use here. I tried

XSA_DEV / XSA_ADMIN and XSA_SHINE all with the set password. All three users login fine, but I'm only presented with a rather lame "Welcome to XSUAA"

Am I missing something (sure I must be)?

Nevertheless. It's great to see that SAP finally made a version of HANA available to spur independent development. Something I asked for already back in 2012 in my blog post [Why SAP HANA needs help to unfold it's potential](https://blogs.sap.com/2012/12/01/why-sap-hana-needs-help-to-unfold-its-potential/), where I wrote "_...that HANA is the next big thing in computer technology. Just like the invention of microprocessors, like Client Server back in the 80’s, like affordable and actually usable personal computers and of course the internet. But, without a broad developer base from independent (and that means independent from SAP) companies. Without creative users and architects and designers to think beyond SAP’s enterprise analytics and planning horizon, it can’t unfold it’s full potential._"

**Comment by JCurrie27** [comment]
Hi Christian: Thanks for your feedback. Have you tried WebIDE login using SAP HANA 2.0, express edition yet? A lot of changes have been made since 1.0 SP 12.

I've been able to log in to WebIDE using the XSA_DEV user and password. You can see it at minute mark 4:41 in my video "SAP HANA 2.0, express edition Installation (Virtual Machine Method)" (http://www.sap.com/assetdetail/2016/09/d2900513-8a7c-0010-82c7-eda71af511fa.html). 

The procedure for changing default user passwords -- including WebIDE's XSA_DEV user -- are found at minute mark 3:01.

> There's a link to this video at the top of tutorial **Start Using SAP HANA 2.0, express edition (Virtual Machine Method)** (http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html).

Default password change procedures, and the WebIDE login procedure are also found in tutorial **Start Using SAP HANA 2.0, express edition (Virtual Machine Method)** (http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html).

Hope this helps,
John Currie
