### ISSUE TITLE
Feedback on Tutorial: Installing the VM Image

### ISSUE THREAD

**Issue by amysy** [SAPDocuments/Tutorials#1183]
What if my laptop has just 4GB of RAM. 
Can I still use the VM set up and get cracking with Express install?

**Comment by amysy** [comment]
was there a resolution provided to your query - I've same questions

**Comment by JCurrie27** [comment]
Hello - The minimum RAM requirement for your laptop is 16GB RAM, with 24GB recommended. 

SAP does not recommend installing on a laptop that doesn't meet the RAM requirements -- not all required services will start. 

You may want to consider installing the [binary package](http://www.sap.com/developer/tutorials/hxe-ua-installing-binary.html) to a cloud-hosted virtual machine, rather than installing the VM package to your laptop.

Hope this helps,
John C.

**Comment by amysy** [comment]
Thanks John-
You've documentation for the use case scenario you mentioned. Appreciate if you could share as I can go down this route. 
Much appreciate your response.
