### ISSUE TITLE
firstTime.mtaext listed on "Getting started ..." pages has a syntax error

### ISSUE THREAD

**Issue by LayneB** [SAPDocuments/Tutorials#1245]
The yamls used for the installation of the EA Designer, on both Getting Started pages, the -name has incorrect spacing.  
[`Create a text file, copy the following content to it, replacing the variable with your choice of a temporary administrator password for the first login, and save it as firstTime.mtaext:

_schema-version: "2.0.0"
ID: com.sap.hana.eadesigner.ext
extends: com.sap.hana.eadesigner

modules:
  - name: eadesigner-backend
  properties:`]

(http://www.sap.com/developer/tutorials/hxe-ua-getting-started-binary.html)

Cutting and pasting into the firstTime.mtaext file causes the installation to bomb.   I deleted the spacing in front of the dash name to make the xs install work. Request the HTML be updated.   Thanks ... @ccmehil @jpenninkhof

**Comment by i825908** [comment]
Please refer to https://github.com/SAPDocuments/Tutorials/issues/1224. Thank you!

**Comment by JCurrie27** [comment]
The tutorial [Start Using SAP HANA 2.0, express edition (Virtual Machine Method)](http://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html) and the binary getting started tutorial were both modified as below. Please note our testing indicates there should be two spaces in front of "- name".  Also, in the comment above, there is a bullet instead of a dash in "- name" in your code snippet.

...

2. Create a text file, copy the following content to it, replacing the variable <`tempPwd`> with your choice of a temporary administrator password for the first login, and save it as `firstTime.mtaext`:

    >**Important**: Incorrect indentation causes errors. If you are copying code, make sure that `- name`, `properties` and `ADMIN_PASSWORD` are indented with spaces, not tab. There are two spaces in front of `- name:`. There are two spaces in front of `properties`. There are four spaces in front of `ADMIN_PASSWORD`.

    ```bash
    _schema-version: "2.0.0"
    ID: com.sap.hana.eadesigner.ext
    extends: com.sap.hana.eadesigner

    modules:
      - name: eadesigner-backend
      properties:
         ADMIN_PASSWORD: <tempPwd>
    ```
