### ISSUE TITLE
Create a hybrid app in SAP HANA Cloud Platform mobile services for development and operations

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#1271]
The screenshot in step 7 shows **Enable CSRF protection** and **Ignore Case for User Name** checked but the table above says: **(leave unchecked)**.

**Comment by jonathanbaker7** [comment]
This actually belongs to Jim, so I'm re-assigning it. 

I checked the image, and discovered that almost all of the images have changed (and it would change the instructions).  Rather than just updating one image, I would like Jim to take a look and make sure the workflow is still correct.  @akula86, if you want assistance updating this, let me know.
