### ISSUE TITLE
SAPUI5 - Setup the DataSource in the local application

### ISSUE THREAD

**Issue by eflamm** [SAPDocuments/Tutorials#1333]
The provided service endpoint (/V3/Northwind/Northwind.svc) is incorrect - it should be /V2/Northwind/Northwind.svc

**Comment by jonathanbaker7** [comment]
Did you have a problem with the V3 service?

**Comment by eflamm** [comment]
Yes - I received a 404 error, because the data source setup points to V2, while the endpoint in the exercise points to V3. I assume I could create another data source pointing to V3, but this is a beginner's tutorial, and the 2 steps should work together. This is the link to the step which uses the V2 url: http://www.sap.com/developer/tutorials/hcp-create-destination.html

**Comment by jonathanbaker7** [comment]
I think I see the problem, but it should not be affecting your tutorial at all.

Did you follow Step #3 in the hcp-create-destination tutorial exactly as it appears?  The settings should look like this:

Field Name     | Value
:------------- | :-------------
Name           | `Northwind` 
Type           | `HTTP`
Description    | `Northwind OData Service`
**URL**            | **`http://services.odata.org`**
Proxy Type     | `Internet`
Authentication | `NoAuthentication`

With the following additional properties:

Field Name       | Value
:--------------- | :-------------
`WebIDEEnabled`  | `true`
`WebIDESystem`   | `Northwind_Data`
`WebIDEUsage`    | `odata_gen`


I highlighted the URL that I think is the problem. 

If your system is set up that way, the later tutorials should work.  Let me know what you find, so we can continue to work out the issue.


Cheers,
Jonathan

**Comment by eflamm** [comment]
Is that URL sufficient to connect to the Northwind data service? There's this text at the top of the tutorial:

> The data source URL is http://services.odata.org/V2/Northwind/Northwind.svc/

which is what I used to setup the data source. I'll go back and update it to just services.odata.org and see if it works with the V3 endpoint in the

**Comment by jonathanbaker7** [comment]
I can also see how you were confused by this, and it makes complete sense.  I will update the tutorial today, because having this URL at the top is very confusing.  Thank you, that was a very good catch.  I'm sure someone else has (or will) make the same mistake.

Please make that change, and then use the path "V3/Northwind/Northwind.svc" in your application.  the combination of both the destination and this path should work.  (It will also give you a generic destination which you can use for any other tutorial, as well.)  Let me know what happens.  If you are still having problems, just update this thread.

Again, good catch.  Thanks!

**Comment by jonathanbaker7** [comment]
I am going to close this bug report, as the changes to the tutorial are now made.  If you have any further issues, please open it again.
