### ISSUE TITLE
SAP HCP predictive services, Visualize your predictive demo data set

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#1345]
Hi Abdel Dadouche,

At the outset I would like to thank you for the great work you have been doing in coming up with these tutorials on Predictive Analytics on SAP HANA. I've been working on these tutorials for about a week now and would like to ask you few questions and thus provide some feedback. 
I am learning Predictive Analytics on SAP HANA to build a PoC on HANA to build an app that helps shoppers and merchants (Retailers) to predict what the customer is likely to buy and accordingly give him similar inputs. If he buys bread regularly I want to give him a discount on his regular bread and offer him other discounts on Ketchup, Cheese and such similar products. Some thing similar to what we see on Amazon. Based on his past buying pattern the merchant should  be able to offer him discounts in real time on what he is scanning in the store. And the customer should get inputs on his smart phone as to on what products discounts are available - All this in the store while he is shopping. 
My background is I am a data modeller a BW and HANA Consultant. I do not have any experience in HTML, JAVA, JSON, ODATA, REST and what ever has been mentioned here. 
Now the question I have is can I (a person without any programming experience) build an app using these tutorials on SAP HANA Predictive Analytics and build an app?
Should a person have any experience on any of these programming languages to build these apps on SAP HANA?
Please advise. It would be great if you can refer me to some right tutorials or user guides from where I can learn and start. 

Once again thanks a lot for your time in coming up these tutorials. I've learnt a great deal.

Thank you.

Regards,
Pavan.

**Comment by adadouche** [comment]
Hi pavanmulpur,

The intent of these tutorials is to give users the ability to start using these features whatever their background is.

It is not intended to explain everything in details, because the format is not appropriate for this, and this why sometime "we" use some shortcuts or don't intentionally provide all the explanations (as this also force the users to search for more details on the topic).

People learn in different ways, read, watch listen. Our intent is not to replace formal training (classroom or online), but really to give any users the ability to "try it out" with no fuss and quickly, and then let them start and find their own journey.

You will find interesting content on the openSAP web site like the UI5 training for example (https://open.sap.com/courses/ui51) or other tutorials using our tutorial navigator (http://www.sap.com/developer/tutorials.html).

Regards
