### ISSUE TITLE
https://hxehost:8090  not working

### ISSUE THREAD

**Issue by s0000241042** [SAPDocuments/Tutorials#1658]
hello
I have implemented SAP HANA Express Edition 2.0. on a windows 10 and tablet surface pro 4.
The above command is not working. it does only work when i put the IP-Adresse.
In the VMware Workstation 12 Player, under xs apps are many https://hxehost: nnnnn adresses, none of them is working in a browser like chrome.
What do i have to configure in Windows, DNS-Server and where, ethernet or the  VMware network 1 or 8?
Many thanks for fast help as i am stucked now.
regards. Nick

**Comment by Lsubatin** [comment]
Hi, Nick, 

I suggest you post this kind of questions in the Community Q&A, since this is for issues related to the tutorials, not technical issues. Have you mapped "hxehost" to the IP in the hosts file in Windows? Check the "Getting started guide" that gets downloaded by default with the VM image, section "2.4.1 Edit hosts on Windows".
Cheers,

Lucia.

**Comment by s0000241042** [comment]
problem solved. the problem was, the file host had the ending .txt and this file was not read by the Windows 10.
I was copying the file host to desktop and changed the ip adress, after i pushed it back. then the file had the ending .txt and this was the fatal error.
thanks and reagards. Nick
