### ISSUE TITLE
Inserting OData query options into your SAPUI5 app

### ISSUE THREAD

**Issue by smilingsun** [SAPDocuments/Tutorials#1759]
Hi, 

Thanks so much for these great tutorials!

But where is the source code for this tutorial? 
For example, you mentioned ``northwind/view/Master.controller.js``.

Thanks!

**Comment by smilingsun** [comment]
Perhaps a link to [Build an app from an SAP Web IDE template](https://www.sap.com/developer/tutorials/hcp-template-mobile-web-app.html) should be put on the ``Prerequisites`` part of the page of [Inserting OData query options into your SAPUI5 app](https://www.sap.com/developer/tutorials/hcp-webide-inserting-query-options.html)

**Comment by mhassett92** [comment]
Hello,

Apologies for the long delay, and I am sure you figured it out. For reference, that tutorial is part of a longer series that starts with[ Build an app from an SAP Web IDE template](https://www.sap.com/developer/tutorials/hcp-template-mobile-web-app.html) as you mentioned. This tutorial is not the immediate predecessor which is why it is not listed in the Prerequisites section. Prerequisite and Next Steps are intended to similar to Previous and Next "buttons" for the series.

However, we have noted this a possible usability issue on our side and will make sure to consider it as we are redesigning the tutorial experience.

Thank you!
Meredith
