### ISSUE TITLE
Installing the SAP Cloud Platform for iOS SDK  Step 2

### ISSUE THREAD

**Issue by mohiteveer** [SAPDocuments/Tutorials#1767]
I am at Step 2: Open or create Xcode project?
Where do I find the demo application project? com.sap.tutorial.demoapp.DemoApplication

**Comment by qualiture** [comment]
Hi @mohiteveer,

When we wrote this tutorial, it was meant to be a follow-up to this tutorial group: https://www.sap.com/developer/groups/ios-get-started.html 

Here you create the `com.sap.tutorial.demoapp.DemoApplication`.

In your case, you can simply create a dummy Single-View application with the same namespace and name; you won't use it after this tutorial since in one of the following tutorials, you will be creating a new app using the SDK Assistant, and build from there.

I'll change the tutorial to make this more clear, thanks for pointing this out.

**Comment by mohiteveer** [comment]
Qualiture,
Thank you for sharing the link and solving my issue.
Also appreciate the effort to update the tutorial with these pointers. It makes our lives easier.
Have a great day.

PS. Closing the issue.
