### ISSUE TITLE
Click to enlarge images would be helpful

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#1790]
Hi Tutorials Team,

some of the pictures especially in the CI tutorials are displayed very small. Currently I can only enlarge them when I open them in a new tab:

![screen shot 2017-07-18 at 21 18 04](https://user-images.githubusercontent.com/2639535/28335430-a13d407e-6bfe-11e7-9c73-239c5499e9e0.png)

Could a link to the original sized picture be provided directly? Perhaps as a lightbox?

Best regards
Gregor

**Comment by qualiture** [comment]
I vote +1 for @gregorwolf's enhancement request -- I have a couple of images in my tutorials that would benefit from it as well.

_(On a sidenote, since 1DX the Wordpress blog editor on blogs.sap.com also doesn't support opening larger images. But since it has an HTML editor, that can be remedied by wrapping an anchor tag with blank target around the image)_

**Comment by akula86** [comment]
I like Gregor's suggestion and it has come up internally as well. We have it in the backlog - but we have a lot of other items to tackle for the next few months. That said - I'll keep trying to bump it up. I'll leave this open until we have a final disposition.

**Comment by thecodester** [comment]
We have now implemented this in 2 ways:
* The width of tutorial column is now much wider and can show larger images
* Images larger than the width have a button to enlarge them
