### ISSUE TITLE
HANA Express Edition - Install Dependencies for Ubuntu on Google Cloud Platform

### ISSUE THREAD

**Issue by mc1271** [SAPDocuments/Tutorials#1819]
HI tried your script in order to move from VM to SAP Hana Express on my local Ubuntu (16.04).
Although I added the chkconfig alias the install still Fails:

`alias chkconfig='sysv-rc-conf'

`Output line 1: /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh: 206: /hana/shared/HXE/global/hdb/saphostagent_setup/installsapinit.sh: chkconfig: not found
              Program terminated with exit code 5`

I can use the alias with desired result, however starting Setup_hxe.sh or installsapinit.sh produces the same (above) error.

A hint would be appreciated.

**Comment by Lsubatin** [comment]
Hi Mike, what happens if you become root, do the alias and  test the command?

**Comment by mc1271** [comment]
I tried it sudoing and by activating and executing with real root account. Fails both times. But I can still execute chkconfig successfully afterwards.

**Comment by Lsubatin** [comment]
I've seen this issue when the alias and setup script were not run as root (or the machine is restarted between setting the alias and running the sript, thus losing the alias). You can try this: https://uni.edu/~prefect/devel/chkconfig/index.shtml

Also, please bear in mind that if you are using the SPS02 version, the install will fail because of an SSL library. These tutorials are still pending update and the issue is being worked on.

**Comment by tai-le** [comment]
We also found following issues on Ubuntu 16.04:

1. /bin/bash is softlink to /bin/dash.  Some of the installation scripts are not compatible with "dash".
     * Workaround: Make /bin/bash softlink to /bin/sh
2. libstdc++6 on Ubuntu 16.04 doesn't support GLIBCXX_3.4.22.
    * Install newer libstdc

**Comment by Lsubatin** [comment]
Known issues with SPS02 are now solved. Tutorials updated to  
- Core database (or server-only flavor): https://www.sap.com/developer/tutorials/hxe-gcp-ubuntu-db.html 
- Database server + XS Advanced applications: https://www.sap.com/developer/tutorials/hxe-gcp-ubuntu-xsa.html

Thanks @tai-le !!
