### ISSUE TITLE
Installing SAP HANA 2.0, express edition (Virtual Machine Method)

### ISSUE THREAD

**Issue by samiumiu** [SAPDocuments/Tutorials#1883]
Need your help please! ^_^
Issue: hsexsa cannot run in VM method, more details on attached screen capture. 
Environment: macbook, VMware Fusion pro 8.5.7 
![hxe issue on fusion](https://user-images.githubusercontent.com/32578229/31306280-362e2bc4-ab12-11e7-93c4-5533b54822f6.jpeg)

**Comment by entmike** [comment]
In my experience, it is impossible for initial VM setup to work successfully on a MacBook because it has only 16GB of RAM. I had to perform the initial setup in a host with more RAM (I set the VM to 24GB if I recall) and then did initial setup. Once that was completed, I shut down th VM and copied the .VMX files over to my MacBook and it then has been running fine with 12GB.

**Comment by Lsubatin** [comment]
Hi,

A new version was released yesterday for the VM addressing this. Could you please let us know how it works? Also, on my machines, I change the RAM setting to 16GB (which is what the host has). It may get slow at times but it finished if I leave the host alone.

Cheers,
Lucia.

**Comment by i831123** [comment]
Hi Lucia, Yes I was about to test it and it works on my MAC. Please use the latest image from SPS 02.

**Comment by entmike** [comment]
Hey i831123/Lucia,

So as we know, MacBook laptops top out at 16GB of RAM.  I wasn't aware that you could set RAM of a guest VM to 16GB (otherwise the host has no RAM to host) - I assume it's doing some virtual swapping to pull of this feat?  Very cool if so :)

Do you have a recommended bare-minimum amount of RAM that you'd suggest setting an HXE 2.0 machine at which could run XSA?  I've managed to run mine with 12GB, but only after turning off that bloated XSA HANA Admin Cockpit...

**Comment by JCurrie27** [comment]
Hi - There is a n SAP HANA express edition sizing guide on the SAP Help Portal that lists the memory requirements for each optional component:

[https://help.sap.com/viewer/9e4243e92f244537b2164a57a405a9fd/2.0.02/en-US](https://help.sap.com/viewer/9e4243e92f244537b2164a57a405a9fd/2.0.02/en-US)

Please take a look and let us know if this helps with your installation.

**Comment by entmike** [comment]
That is very cool.  Is this new?  I was reading through the documentation about a month back and must have missed this otherwise.  This would be an extremely handy reference for the tutorial documentation as well!  Thanks for pointing that out.
