### ISSUE TITLE
SAP HANA XS Advanced, Connecting to SAP Web IDE and cloning a Git Repository to begin development

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAPDocuments/Tutorials#1962]
Kindly help on Host number pleaseeeeeeeeeee

from where I got this **<hostname>** for XSadvanced.

Also, I have one web IDE account but it doesn’t show me XS advanced application creation or you can say No nodejs app creation etc. Kindly help me with missing info, Totally exhausted, Kindly HELP!!!
https://webide-p1942951835trial.dispatcher.hanatrial.ondemand.com/
![image](https://user-images.githubusercontent.com/22063881/31435640-ee418ad8-ae9d-11e7-9891-e867f40128a9.png)

Is it mandatory to install HANA XSA command line tool if yesfrom where i get this exactly with name please.

**Comment by Lsubatin** [comment]
Hi, Ahmed,

I am not sure what the issue is here or which port number you are looking for. These tutorials are based on HANA Express editions and you seem to be using the Cloud trial. Node.js is not yet available there. 

Here are some options for HANA Express: https://blogs.sap.com/2017/10/02/quick-deployment-options-for-hana-express-on-the-cloud/ 

Best, 
Lucia.,

**Comment by ahmedkhan29789** [comment]
Hi Lucia,

I am using Google cloud platform only, My metadata is working fine on
another port but my app is looking for metadata on another port, is there
any way that i can ask my app to look metadata on the port i want.



With Best Regards,

*Ahmed Ali Khan*

*SAP Consultant*

Mob.: +919911380694
