### ISSUE TITLE
Create a BUILD Prototype - adding columns works differently now

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#2002]
Hey there, noticed that in Step 6 of the "Create a BUILD Prototype" tutorial, adding a column cannot now be done via the context menu (right click -> Add Column Left). Instead, I had to use the Properties area to add a child column (see screenshot). Wasn't sure if this was the same for everyone else, otherwise I'd have created a pull request :-)

![screen shot 2017-11-01 at 08 41 21](https://user-images.githubusercontent.com/73068/32266843-e886ba16-bee0-11e7-8cf6-face0f526c57.png)

**Comment by mhassett92** [comment]
Hello! That is an alternate way to add a column. However, the way listed in the tutorial does still work. In your above screenshot, you have the whole table selected. In order to see the Add Column Left/Right menu option, you need to have only 1 column in the table selected as indicated in the screenshot in the tutorial. 

Thanks!
