### ISSUE TITLE
Gateway Demo system

### ISSUE THREAD

**Issue by S0004855984** [SAPDocuments/Tutorials#2068]
Hi,
I tried to post on Demo system, CC 9400 Slovakia and in SK is valid EURO currency 8 years (from 1.1. 2008).
Would be possible to change currency for Slovakia ? 
What is valid posting period ? I think 2017 year not, I can not authorization for check it.
Is it demo system for training, viewing or presentation ? 
BR,
Jan

**Comment by jonathanbaker7** [comment]
Jan,

My apologies for taking so long to get back to you.  

This sounds like a bug in the ES4 system, but this should be fixed in the new ES5 system.  Here is a [registration link to that new system](https://register.sapdevcenter.com/SUPSignForms/).

For any detailed questions about that system, please check out [Andre Fischer's blog post](https://blogs.sap.com/2017/12/05/new-sap-gateway-demo-system-available/), or go to the [SAP Q&A system](https://answers.sap.com/tags/181161894649260056016734803547327) to post a question.  We don't maintain that system here, so all we can do is refer you to the people who do run it.

If you have any other questions, please just re-open this bug.  Thanks

**Comment by softy12** [comment]
This problem is inherited from SAP IDES systems. In all IDES systems, Slovakia is still assigned with SKK as currency. The situation is present even in the newest up2date IDES ERP 6.0 incl. EHP8.
So basically someone in SAP shall finally customize correct currency in the IDES for the Slovakia which is Euro since 1st of Jan 2009 :)
