### ISSUE TITLE
hana express docker  port to connect xs api end point ?

### ISSUE THREAD

**Issue by lucodealethea** [SAPDocuments/Tutorials#2099]
Hi,
I installed hana express successfully but cannot 
xs login -u SYSTEM --skip-ssl-validation
returns
FAILED: Could not connect to controller on https://hxed:39030
        Connection refused (Connection refused) (local port 51506 to address 172.17.0.1, remote port 39030 to address 172.17.0.2 (248436a04264))

1. /hana/shared/HXE/xs/controller_data/controller/ssl-pub/router/default.root.crt.pem > no such a file in the container to use with xs api --cacert 
2. Desperate to get a list of url-endpoints via xs apps

Any suggestion is welcome ,

Cheers

docker port 248436a04264
returns
39041/tcp -> 0.0.0.0:39041
39043/tcp -> 0.0.0.0:39043
39045/tcp -> 0.0.0.0:39045
1128/tcp -> 0.0.0.0:1128
39013/tcp -> 0.0.0.0:39013
39017/tcp -> 0.0.0.0:39017
59013/tcp -> 0.0.0.0:59013
59014/tcp -> 0.0.0.0:59014
1129/tcp -> 0.0.0.0:1129
39042/tcp -> 0.0.0.0:39042
39044/tcp -> 0.0.0.0:39044

none of the above connects...
example: xs api https://hxed:39044 --skip-ssl-validation

**Comment by lucodealethea** [comment]
Well, Hana Express version docker doesn't come with XSA or XS Classic; so I guess we'll have to make extra effort to orchestrate one statefull hdb container with others xsa platform runtime / nodejs container ?

**Comment by cxww107** [comment]
@lucodealethea did you manage to solve the problem? Could be xsa runtime installed afterwards? 

What I can't understand: I don't see xsengine in the list of services (HDB info).
But when I try host:8090:  it returns the beautiful SAP Logo with a message "XSEngine is up and running".
<img width="683" alt="screen shot 2018-01-14 at 21 21 11" src="https://user-images.githubusercontent.com/16280975/34920301-e7d1c9c4-f970-11e7-8224-b0f939c31754.png">

**Comment by lucodealethea** [comment]
Hi Nik, I was wrongly expecting the hana 2.0 sps 2-21 container having xsa installed, but it doesn't nor that it seems to have xs classic( with hana cockpit ) installed. I came to that conclusion after looking at install directories/log in the container itself. I finally came back to a virtual machine despite my deep interest in the containers orchestration topic, as we know that it should be possible to orchestrate ( on a developer platform ) a hana dbms container along with xsa runtime container, and xsa client one. A matter of time and continuous effort...

**Comment by lucodealethea** [comment]
Please note that HXE 2.0 sp2 -21 binary install is also subject to caveats as per  rafdre comments on Nov 19, 2017, where solution is made clear in https://github.com/SAPDocuments/Tutorials/issues/1490
cheers,

luc

**Comment by Lsubatin** [comment]
The docker version does not have XSA and the scenario has not been tested yet.
XS Classic should still be there. You do not see the xsengine process anymore because it's embedded in the nameserver process. XSC has been deprecated as of SPS02 and I would not use the Web Editor Workbench as there are some known problems with it. The cockpit you could open in HANA 1.0 SPS12 was moved to XSA, so you should get an error if using HANA Studio to open it. This does not mean you can't do OData services, for example or still use HANA Studio.
As for the "Please note that HXE 2.0 sp2 -21 binary install is also subject to caveats" I still do not know what the problem with rafdre's installation was as the question and logs were incomplete. Other than lack of resources during installation, there are no known problems with the installation of rev 21.  Lack of RAM memory or disk space could lead to errors during installation.
Downloading the latest binary installation packages (rev 22) is a better idea if you are going to try XSA on docker.

**Comment by lucodealethea** [comment]
For the HXE 2.0 sp2 -22 XSA binary install, it will be required to

cp <install_path>/HANA_EXPRESS_20/hxe_info.txt /usr/sap/HXE/SYS/global/hdb/hxe_info.txt

Otherwise the following error will stop the installation:
sed: can't read /usr/sap/HXE/SYS/global/hdb/hxe_info.txt: No such file or directory
Cannot install XSA.  This XSA version is not compatible with your installed HANA, express edition version.
