### ISSUE TITLE
Implement Offline OData in your application

### ISSUE THREAD

**Issue by MadsBogeskov** [SAPDocuments/Tutorials#2124]
You refer to `ESPMContainer` however it doesn't seem to exist in any of the frameworks?

**Comment by MadsBogeskov** [comment]
I have created a new project from the Assistant, and is trying to follow the guide from https://www.sap.com/developer/tutorials/fiori-ios-hcpms-offline-odata-implementation.html to switch to offline mode.

**Comment by qualiture** [comment]
Hi @MadsBogeskov,

`ESPMContainer` is not part of the framework, but refers to the data service provider generated by the SDK Assistant for your OData service. If you created the app with the sample OData service (see [https://www.sap.com/developer/tutorials/fiori-ios-hcpms-sample-odata-service.html](https://www.sap.com/developer/tutorials/fiori-ios-hcpms-sample-odata-service.html)) your generated app will have an ESPMContainer class in folder `./Proxy Classes/public`

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by carstenhag** [comment]
Hey, I'm having the same issue. I've generated the app with the Assistant, Version 2.1.501.

There are no ESPMContainer files or "espm"-named in general in the entire project.

**Comment by qualiture** [comment]
Hi @carstenhag,

The way this particular tutorial was written, is that it used to be part of a sequence of tutorial groups, containing a sequence of tutorials (as indicated by the 'prerequisite tutorial' and 'next steps')

The idea was to first create an application definition on SCPms (containing a datasource pointing to the sample OData service), and then run the SDK Assistant using that predefined configuration. With these order of steps, you will get the `ESPMContainer` file. See the sample project I created for this issue in the screenshot below:

![ESPMContainer.swift](https://i.imgur.com/bnUnV7W.png)

The quickest way to replicate the behaviour described in the tutorial is as follows:

* Use the SDK Assistant to create a new application using the Sample OData service (in the **Cloud Configuration** step, choose **Sample**)
* Once it is created, use the SDK Assistant to create a new application based on the previously created app (in the **Cloud Configuration** step, choose **Use Existing** and point to the previously created app)


However, to avoid confusion, I will change the tutorial in two ways:

I will add a disclaimer stating the tutorial is only valid for pre v2.2 versions of the SDK (since 2.2, this tutorial is deprecated)

I will also add clarification everywhere it mentions `ESPMContainer`, you can replace it with `MyServiceClass` or whatever name your service class may have.

Hope this explains, and apologies for any confusions,

Robin

**Comment by carstenhag** [comment]
Ahh thanks, I see. I didn't see that the app used a sample odata.

For me, the file that I was searching for is called `ZFMOBINCIDENTSRVEntities.swift`. The screenshot cleared that up.

If anybody else has this issue, look for a class with this header (without the ZFM... obviously):  
`open class ZFMOBINCIDENTSRVEntities<Provider: DataServiceProvider>: DataService<Provider>`

**Comment by carstenhag** [comment]
Another note, `import SAPOfflineOData` is missing from this tutorial
https://www.sap.com/developer/tutorials/fiori-ios-hcpms-offline-odata-introduction.html
```swift
let teacherDQ = OfflineODataDefiningQuery( name: "Teacher", query: "Teachers", automaticallyRetrievesStreams: false )
```
