### ISSUE TITLE
Step 17: Implement Table View Controller

### ISSUE THREAD

**Issue by goubin510** [SAPDocuments/Tutorials#2219]
Hi,
I found a bug doing the tuto : "Create custom iOS app with SDK Assistant"
(https://www.sap.com/developer/tutorials/fiori-ios-scpms-custom-app-creation.html)

Step 17, it says : **Use of undeclared type 'MyPrefixMyServiceClass'**
I switch **MyPrefixMyServiceClass** to **MyServiceClass**

**Comment by goubin510** [comment]
this is still wrong in the tutorial... what a reactive team...

**Comment by qualiture** [comment]
@goubin510 

Apologies, I somehow missed the notification for this issue.

Nevertheless, the tutorial is correct. 

In the tutorial you should choose to use the **Sample OData** service, and then the prefix **MyPrefix** is set by default, with no option to change it for the generated proxy classes:

![Image](https://i.imgur.com/qh3LOwP.png)

If you choose **Create** or **Use Existing**, then the prefix is omitted by default (but you can change it to your own):

![Image](https://i.imgur.com/tOoq9Ap.png)

So I suspect you choose the latter option rather than selecting the same OData service

Of course, if you don't follow the tutorial to the letter both options are correct, but you should be aware of the differences in the prefixes used.

Hope this explains,
Robin

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
