### ISSUE TITLE
AngularJS as a Front End - Getting Started

### ISSUE THREAD

**Issue by lutraki-yavan** [SAPDocuments/Tutorials#2223]
Hi,
I don't understand why you create the project from the "SAPUI5 Application" template, if you delete its entire content. And obviously this tutorial is about Angular, so why create something with SAPUI5?
Why not simply create a folder?
It looks strange..

**Comment by jonathanbaker7** [comment]
That's because we want a few things that are part of the project structure (specifically the settings files that are used by the web server).  

The Web IDE was originally created to write UI5 projects.  So, it's very UI5 centric.  We can use it for other things, but that usually involves taking out the UI5 stuff first.  And, unfortunately, they don't have an option (yet) to start an empty project without the UI5 stuff, which would be one way to skip it.

The important takeaway:  WebIDE can build in multiple frameworks, and the web server is just serving files, and acting as a "pass-through" for the Northwind data.  All of the real work is being done on the browser.  So we can use the same web server for Angular, or for UI5, because the framework is just a file being sent to the browser.

I hope that helps answer your question.  Feel free to email or re-open this bug if you want to discuss further, I'm happy to help.
