### ISSUE TITLE
SAP Cloud Platform SDK for iOS Assistant

### ISSUE THREAD

**Issue by goubin510** [SAPDocuments/Tutorials#2224]
Hi everyone,

I'm looking to link an odata from my HANA database with the assistant to pre fil the app with the controllers and link of my project, but after severals try I always get the same error : 
**Metadata download failed**
> CSDLError: /var/folders/jm/szqjxxp52d72pn13mddkkh6h0000gn/T/com.sap.HCPSDKforiOSAssistant/temporaryMetadata/283C8387-B604-4E46-A75E-EC3AD7957C48-28828-00016AD3489EFD17_7439B993-D59A-4E93-95F5-789DFA516155.xml: Expected root element 'Edmx', found 'error'.

any tips on how to pass that ?

**Comment by qualiture** [comment]
Hi @goubin510, 

You may have more success finding a solution too your issue if you post it to https://answers.sap.com/tags/73554900100800000743

This repository's issues page only deals with issues with the tutorials itself.

But since you're getting an error instead of the metadata, I suspect your destination in SAPcpms is not configured correctly (incorrect path, invalid user credentials, etc)

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.

If you still have questions, feel free to reopen the issue.
