### ISSUE TITLE
Is there a way to connect with HANA Studio to HANA Express in docker?

### ISSUE THREAD

**Issue by jochensteinmetz** [SAPDocuments/Tutorials#2259]
could not get a connect where local connect is possible

**Comment by adadouche** [comment]
Hi @jochensteinmetz,

When using Docker, the port numbers are slightly different (39017 instead of 39013 and 39041 instead of 39015), and in addition when starting your container you have to publish these port using the "-p" switch.

in step 5 of  [Installing SAP HANA, express edition with Docker](https://www.sap.com/developer/tutorials/hxe-ua-install-using-docker.html), yu can see the run command which publish these ports:

```
sudo docker run -p 39013:39013 -p 39017:39017 -p 39041-39045:39041-39045 -p 1128-1129:1128-1129 -p 59013-59014:59013-59014 -v /data/express_edition:/hana/mounts \
--ulimit nofile=1048576:1048576 \
--sysctl kernel.shmmax=1073741824 \
--sysctl net.ipv4.ip_local_port_range='40000 60999' \
--sysctl kernel.shmmni=524288 \
--sysctl kernel.shmall=8388608 \
--name express_edition \
store/saplabs/hanaexpress:2.00.022.00.20171211.1 \
--passwords-url file:///hana/password.json \
--agree-to-sap-license
```

Then when configuring the SAP HANA Tools for Eclipse, you can check the following tutorial: [Use the SAP HANA Tools for Eclipse as a SQL query tool for SAP HANA, express edition](https://www.sap.com/developer/tutorials/mlb-hxe-tools-sql-eclipse.html) which explains that with Docker you have to use a little trick (see step 3 and 4).

Hope this helps.

@bdel

**Comment by jochensteinmetz** [comment]
Hi Abdel,
thank you so much, that did the trick.
"In order to connect to the System Database, you will need to select then select Tenant database, and input SYSTEMDB:39017 in the name field. This is due to a specific port binding configuration"
Best regards,
Jochen
