### ISSUE TITLE
Translate a sample Fiori app

### ISSUE THREAD

**Issue by amysy** [SAPDocuments/Tutorials#2268]
Hi,

Thanks for a complete step by step. Want to suggest an improvement. When I change languages and test the app it works fine but I can't revert to en language. I'll have to log out and then preview the app to get to the default that is EN language screen. 
There should be a control to switch to default screen. 
Hope it's useful for larger developer community.
TIA.
![app1](https://user-images.githubusercontent.com/13893456/37441647-87eece88-27d0-11e8-934a-8ec993c59822.PNG)
![app2](https://user-images.githubusercontent.com/13893456/37441648-8805582e-27d0-11e8-9a6b-50ea3b8305c1.PNG)

**Comment by thecodester** [comment]
@ianarm Ian, can you respond? Thanks.

**Comment by ianarm** [comment]
Hi @amysy, 
Thanks for your feedback. The issue is caused by English not being one of the languages specified in the project settings in the reference app in SAP Web IDE. All you have to do is add 'en' to the list of supported languages in the project.json file in SAP Web IDE (see step 8 in https://www.sap.com/developer/tutorials/sth-prepare-fiori-app-translation.html). 
I've just updated the tutorial source with this information; it should be live in a couple of days.
Best, Ian

**Comment by thecodester** [comment]
Thanks Ian. :-)

The tutorial is updated (the pictures may take up to a week to update, since they are cached)
