### ISSUE TITLE
SAP HANA XS Classic, Develop your first SAP HANA XSC Application

### ISSUE THREAD

**Issue by jeremyyuSAP** [SAPDocuments/Tutorials#2366]
Hi, I'm getting a 403 Forbidden when I try to log in as a copied user (of "SYSTEM).  It also happens when I log in as the SYSTEM user in Step 1 after creating the codejam db

**Comment by Lsubatin** [comment]
Hi, Jeremy, 
I am assuming you are using HANA Express. Because of the deprecation of XS Classic (and the web editor workbench, among many others), the editor is no longer installed by default as it also has some bugs.

If you still want to do XS Classic development, you can use the plug in for eclipse. If you want to do development on the replacement for XS Classic, you can use XS advanced. Here is the starting tutorial series for that:   https://www.sap.com/developer/groups/hana-xsa-get-started.html (you will need an instance of HANA Express that has the XS Advanced applications)

@adadouche , I think HXE should be removed as an option for anything requiring the web editor workbench

**Comment by entmike** [comment]
@Lsubatin - Re: your comment to @adadouche about removing Web-based development workbench, I think that would have a negative impact.  XSA is a memory hog and takes a long time to start up, especially on developer machines that might be running HXE in a very small VM.  Also unless there's a straightforward way to use SDI/DP Agent/Remote Source tables within XSA (and perhaps there is and I am overlooking it), it's currently very difficult to expose these "non HDI" schema tables to an XSA Application in my experience.  Also, can the newer Web IDE even do things like a .hdbdd that's not tied to an XSA DB schema?  (For instance, can it tie back to a schema not generated in XSA?)  The only way I've managed to do this is in XS Classic Web-based Development workbench.  HANA Studio may be also an option, however it's clunkier to manage there with the constant need to push and activate every incremental save.  Other things still remain easier in Web-based Development workbench vs HANA Studio such as creation of .hdbroles.  In HANA Studio it's just a text editor but there's quite a nice IDE in the workbench.  Same goes for Flow Graphs.  I like Web IDE's better, but I've yet to figure out how to tie back to a non-XSA managed schema without hitting many security hurdles and I cannot find good documentation on how to bridge something like this from XSA to "normal" schemas in the HANA DB.  So for lack of a better option, again web-based development workbench plays an important role.  I know it sounds like I hate XSA, but I don't.  But for all the reasons I mention (probably among others I cannot recall at the moment), I'd hate for the workbench to be removed entirely from future releases.

**Comment by Lsubatin** [comment]
Hey, Mike, 

The Web editor workbench is still there, but I cannot tell for how long. As you know, this has been deprecated being part of XS Classic, thus getting little attention to the nasty bugs it shows since SPS02, this is why it is not installed automatically and, unless there is a specific use case, I do not recommend it where something fully functional can be used.. 

I'm not sure I got your question on "XSA to normal schemas". You mean accessing an HDI container from outside? Or accessing a classic schema from an HDI container?

Cheers,
Lucia.

**Comment by Lsubatin** [comment]
Closing this as Mike resolved this through community channels.
