### ISSUE TITLE
"Learn the basics of the SAP Cloud Platform SDK for iOS and its key concepts" tutorial is empty

### ISSUE THREAD

**Issue by carstenhag** [SAPDocuments/Tutorials#2436]
https://www.sap.com/developer/groups/interactive-ios-sdk-1.html

Rated at 4 hours, but it's empty ^^

**Comment by qualiture** [comment]
@thecodester Can you maybe have a look? Probably something related with the `tutorial-grouping` file. It looks OK to my eyes, but you know best where to look for ;-)

**Comment by qualiture** [comment]
On second's thought, looking at the four missing tutorials in the empty tutorial group it mentions "Xcode 9.2" which makes me think these four tutorials may be a bit outdated already (we're currently on Xcode 9.4)

But again, since I'm not the author of these specific tutorials, I can't vouch for their validity.

**Comment by carstenhag** [comment]
Hey Robin,
thanks for the extensive answer.

Somehow I must have missed the Tutorial Navigator site, thanks for that!

I will have a look at the barcode ones. I had a quick look at one of them 2 weeks ago, and it seemed to be only for the search bar.

Once I test and figure out some more things, I'll report back :)

**Comment by qualiture** [comment]
Hi Carsten,

You are right, the barcode scanner tutorial uses the barcode scanner implementation of the `FUISearchController` indeed. At the time of writing the barcode scanner tutorial, the search bar scanner was the only supported method.

Looking at the documentation for the standalone `FUIBarcodeScanViewController`, however, I also agree there might be some essential documentation missing. But since the implementation of the `FUISearchBar` in the tutorial seems pretty similar, you may be able to connect the dots between it and the API doc for `FUIBarcodeScanViewController`.

Nevertheless, I will contact someone from the development team, and hopefully get some valuable  insights for this standalone controller.

Apologies for the current inconvenience!

Best,
Robin

**Comment by thecodester** [comment]
@qualiture Did you get any additional information? Is this issue resolved?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
