### ISSUE TITLE
Create a Destination for an External API (Slack)

### ISSUE THREAD

**Issue by Jarlein** [SAPDocuments/Tutorials#2438]
The step 4 is not working, error message returned:
"404: Not Found"

**Comment by mhassett92** [comment]
Hi,
You can ignore this error. When creating destinations for APIs, we only use the API stub (not the full URL) so that you can use 1 destination for multiple methods. Otherwise, we would need a destination for all methods we wanted to use. As long as a stub has the same authentication method for all methods, this is the best practice.

Thank you! 
Meredith
