### ISSUE TITLE
demo services available in ES5 demo system

### ISSUE THREAD

**Issue by softy12** [SAPDocuments/Tutorials#2483]
Hi,

I'm working with demo system ES5 of SAP NW Gateway. I obtained an account to that system via page https://register.sapdevcenter.com/SUPSignForms/
What is strange to me is that I do not see any demo services available in SAP Gateway Service Builder (tcode SEGW). 
Does anybody have an idea how to try out any service in there?
thanks

**Comment by jonathanbaker7** [comment]
Some demos had to be left out, as they were either too hard to support on a shared system, or they couldn't run because there is no HANA system behind ES5.

Feedback on the internals of that system are best asked on the [ES5 system blog post](https://blogs.sap.com/2017/12/05/new-sap-gateway-demo-system-available/).  Alternatively, ask the question in SAP Q&A, and tag it ES5.   The teams that support the ES5 demos can explain any of the decisions on what to include, and what they can't include.
