### ISSUE TITLE
Create a Destination on SAP Cloud Platform

### ISSUE THREAD

**Issue by LaurenceNicolas** [SAPDocuments/Tutorials#2490]
Hello,

I followed this tutorial until the end. Now when I click for this destination on the button to:
"Check availability of destination connection"
I get:
Connection to "Northwind" established. Response returned: "301: Moved Permanently"

**Comment by thecodester** [comment]
The URL given in that tutorial is https://services.odata.org/, which redirects to https://services.odata.org/ with a 301 status code. Probably if you use HTTPS, it will give you a 200 status code. Besides the message, does the destination work in your apps?

**Comment by thecodester** [comment]
@qmacro Anything to add? Should the URL be changed in the tutorial?

**Comment by qmacro** [comment]
Hi @LaurenceNicolas - the URLs should be https, rather than http (this might be historic). Please use https as @thecodester suggests. But even if you don't, the destination will still work (I've just tested it, please see screenshot). 

In parallel we'll look at getting the tutorial updated. Thanks.

![screen shot 2018-08-06 at 17 32 02](https://user-images.githubusercontent.com/73068/43729014-cc16f226-999e-11e8-80a2-6170fdd7a41c.png)

**Comment by qmacro** [comment]
Tutorial: https://www.sap.com/developer/tutorials/hcp-create-destination.html

The tutorial is now updated (the Northwind services URLs now have the HTTPS scheme)
