### ISSUE TITLE
SAPUI5 User Interface - Missing exercisesMaster.xsjs

### ISSUE THREAD

**Issue by git-ashish** [SAPDocuments/Tutorials#2505]
In the tutorial https://www.sap.com/developer/tutorials/xsa-sapui5.html, when the webapp is run, there is an error which relates to a missing xsjs service named exercisesMaster.xsjs. Can a link be provided to suitable tutorial which guided/involved creation of this service? It is not apparent in the Prerequisite article as well.

Thanks!

**Comment by git-ashish** [comment]
I found a file here https://raw.githubusercontent.com/MarcusNotheis/hana-workshop/master/core_xsjs/lib/xsjs/exercisesMaster.xsjs

This seems to be working properly and returns the session user's name.

Could you please confirm?

**Comment by Lsubatin** [comment]
Hi, Ashish, 

It will depend on what path you have done so far. You can copy it from here: 

https://github.com/SAP/com.sap.openSAP.hana5.templates/blob/hana2_sps03/ex3/ex3_7 

Or you can also remove the call from Component.js .

I'm changing these paths so that dependencies are more clear and do not lead to these errors. 

Thanks, 
Lucia.

**Comment by git-ashish** [comment]
Thanks Lucia. That would be very helpful.
