### ISSUE TITLE
Image Classification example with Java

### ISSUE THREAD

**Issue by kawaiipooptato** [SAPDocuments/Tutorials#2511]
has the sap image classifier service been taken down? I can no longer find the api. What would be a similar api I could use?

**Comment by adadouche** [comment]
Hi @kawaiipooptato, 

Apparently the service has been renamed to **Inference Service for Customizable Image Classification**

Therefore the URL is now:

 - https://sandbox.api.sap.com/ml/imageclassification/classification 

instead of:

- https://sandbox.api.sap.com/ml/imageclassifier/inference_sync

I'll update the tutorial with the change

**Comment by adadouche** [comment]
Hi @kawaiipooptato 

Any feedback on this? 

Thanks

**Comment by kawaiipooptato** [comment]
Yup I actually noticed that as well. I tried it and it worked really well. Thanks for the tutorial!

**Comment by adadouche** [comment]
Fixed in [af4c7b8](https://github.com/SAPDocuments/Tutorials/commit/af4c7b87d88b718af0ff812cbb828abaa1cd11fd).
