### ISSUE TITLE
Create a Business Service Using CDS

### ISSUE THREAD

**Issue by BiggiKi** [SAPDocuments/Tutorials#2512]
- The screenshots are very helpful. Maybe, you could insert the "save" Icon, or highlight it in the screenshot (step 2: Define a Data Model)
- it would be good to have the possibility to copy the sample code as in the Help Portal (probably not possible on GitHub?)
- Step 4: Test-run your Service (same as in the Help Portal): I'd insert something like
"Note: You must define the URL of the API Endpoint of your account on SAP Cloud Platform in the Project Settings first.
To access the Project Settings, right-click on your project (bookshop) and open the context menu. In the Cloud Foundry section, define your API Endpoint, enter your credentials, and install the builder. "

**Comment by qmacro** [comment]
Hi BiggiKi, thanks for the comments, we appreciate you taking the time. I'll take each one in turn:

- there is already a substep "Save the file" in Step 2. As this is an intermediate tutorial, we are deliberately moving away from telling the learner how to do the most basic things. There is definitely a balance to be had (and I too have made remarks like this one that you've made) but I think on reflection adding more info about how to save a file may very well only add to the clutter, rather than richness, of this tutorial.

- I'm guessing you're referring to the "copy sample code to clipboard" feature in the help portal? That would be useful, but (a) only marginally and (b) only making sense to offer this feature globally in the tutorial system, rather than this single tutorial. There are some changes coming to the tutorial system - I'm not sure if it includes this feature, but perhaps we should wait and see. It's very easy to highlight the code and copy it in to the buffer directly. 

- This is indeed an important step, but the prerequisites do actually point to this activity ("Select a Cloud Foundry space...."). 

Based on these thoughts, I'll close this issue. Thanks.
