### ISSUE TITLE
Error "statuscode": 504 - gateway timeout (Gateway Demo system)

### ISSUE THREAD

**Issue by agl-phenr** [SAPDocuments/Tutorials#2527]
Hi there,

I am following [this](https://www.sap.com/developer/groups/te2016-sapui5.html) tutorial group and I got the below error in tutorial 4 - step 17 (Launch your app):

Sorry, a technical error occurred! Please try again later.

\{
	"message": "HTTP request failed",
	"headers": [],
	"statusCode": 504,
	"statusText": "Gateway Timeout",
	"responseText": **"HTTP Status 504 - Socket connection timed out for host https://sapes5.sapdevcenter.com. Reason: Read timed out (local port 40902 to address 10.117.12.163 (vsa4345881.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz))**"
}

May someone help me out?

Best Regards,
Pietro Henrique

**Comment by douglasmaltby** [comment]
I have the same issue with the same tutorial, I think. I've created this te2016 app twice, with no luck getting past this error. 

I've used the full-stack WebIDE since the old/regular WebIDE is being deprecated 12.31.2018 and we're being told to migrate all apps.

Below is my error message, and a screenshot of a badly formatted and un-resizable/unresponsive error window.

Error: 
Sorry, a technical error occurred! Please try again later.
\{
	"message": "HTTP request failed",
	"headers": [],
	"statusCode": 504,
	"statusText": "Gateway Timeout",
	"responseText": "HTTP Status 504 - An internal application error occurred.\nRequest: 2379986827 s<myID>trial:te2016b"
}
![te2016b_error](https://user-images.githubusercontent.com/19276339/44323713-46c54200-a47d-11e8-8feb-28a4389114ee.png)

**Comment by mhassett92** [comment]
Hi all,
There are a couple open issues on this. As I mentioned in those other issues, the BusinessPartnerCollection is unavailable. To continue with the content, please use another collection, like ProductCollection, while we have the Gateway team resolve this.

Thanks!
Meredith

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by jc-corrales** [comment]
> Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue.
> 
> If you still have questions, feel free to reopen the issue.

Good afternoon

I'm currently following this tutorial:
[SCP3C03 - Create an App Using the SAP Gateway System.docx](https://github.com/SAPDocuments/Tutorials/files/4761910/SCP3C03.-.Create.an.App.Using.the.SAP.Gateway.System.docx)

And I'm having the exact same error here explained.

Also, I have reasons to suspect that this tutorial might be outdated and that the related database might not work as it once used to. I also had to access to "Access Neo Trial" in order to get the connection working.

I'm also using the same parameters depicted in: "https://github.com/SAPDocuments/Tutorials/issues/2340"
Including the "sap-client" field with a value of "002"

I've also set my brower to english, which reduced some of the errors but didn't fix the main problem.

I'd appreciate if you could help me with this situation.
