### ISSUE TITLE
Deploy your app to Fiori Launchpad

### ISSUE THREAD

**Issue by rayatus** [SAPDocuments/Tutorials#2547]
Hi, althoug I manage to deploy the app in Cloud Platform and registered into LaunchPad successfully I'm not able to execute it because a "duplicate id" error showned in the console

![image](https://user-images.githubusercontent.com/12736990/44302352-0f448180-a327-11e8-806b-2d8f01211eba.png)

My app runs correctly if I execute it from WebIDE as "Run as SAP LaunchPad Sandbox"

![image](https://user-images.githubusercontent.com/12736990/44302362-52065980-a327-11e8-9187-9ef3b7e5443e.png)

![image](https://user-images.githubusercontent.com/12736990/44302367-7a8e5380-a327-11e8-9065-ab06d2738bec.png)

I skip validation of step 9 as mentioned in issue #2545 and decided to continue but in this step 10 I'm not able to validate the tutorial step because of the "duplicate id" error. Also in step 5 I had to import my BUILD prototype via ZIP file because if I select "importing from BUILD system" nothing was executed (nor the login popup appears)

Could it be related to the way I imported the prototype from BUILD?

**Comment by ireps** [comment]
I get the same error. Maybe due to the older version of UI5 that has been selected ? 

> Error: failed to load 'sap/m/markers.js' from https://sapui5.hana.ondemand.com/1.40.18/resources/sap/m/markers.js: 404 - error

**Comment by mhassett92** [comment]
Hi Jorge,
I have not seen this error before, but there was recently an update to the code generated when importing from BUILD to Web IDE. I will dig into a little more to see if it is the new code that's creating the issue. In the mean time since you have completed all activities, you can use the test FLP url for the validation in Step 10. This will enable you to register for the ticket drawing. The issue your reference for step 9 has also been resolved, so don't forget to complete that so we have you as completed in the database!

Thank you! 
Meredith

**Comment by mhassett92** [comment]
ireps, you appear to be having a separate issue which may actually be related to UI5 version. Please open another issue with detailed information/screenshots of that problem. 
Thank you!
Meredith

**Comment by rayatus** [comment]
Thanks @mhassett92 I managed to validate the step 10.
