### ISSUE TITLE
SAP HANA 2.0, express edition Troubleshooting

### ISSUE THREAD

**Issue by jmalla** [SAPDocuments/Tutorials#2560]
It would be good to add a section about WebIDE related issues.  We had major issues getting the WebIDE to work correctly on HANA express.  We had to make quite a few adjustments.  That would really help.  Increasing the memory setting to di-core, di-builder, and the Webide.  Also we needed to refresh the WebIDE when we started seeing issues.

Thanks,
Jay

**Comment by Lsubatin** [comment]
Just a comment here, the solution I provided and fixed your problem is already documented in different places. The problem with your question was that although you flooded different channels, you provided completely unrelated information. I had to insist in three answers with the same recommendation to get you to scale the two services. If you search for Web IDE crashes you will see this two-step solution in different posts and the proper forums.

So, on the one hand, scaling should not be necessary for anyone and agree it is an issue, on the other, troubleshooting takes longer when there is hardly any useful information and you choose not to follow instructions from whoever is trying to help you.

**Comment by Lsubatin** [comment]
Hi, Jay, 

The most effective way next time is through the Q&A. You can at-mention me or the authors of any tutorials or community members who seem to have worked with something so we get a notification (just don't abuse that resource). I for one get a notification for every channel. Then, the more information you post (logs, what you have tried and failed, what you have searched), the easier it is on the other end to help.

If you Google "Web IDE crash" you will see the scaling recommendation in a lot of answers from me. However, you will not see a blog post about that. The reason is that recommending it without understanding the root cause can lead to people destroying their instances. In other words, the symptoms may be the same but in some cases scaling the services can make a different problem even worse.  It is a tricky error and scaling is not always the solution, so I would advise against your creating that blog post with my solution and the little information you have. 

On the bright side, I am using your example as why we need those services scaled up from scratch.  

Regards, 

Lucia.
