### ISSUE TITLE
SAP Leonardo Machine Learning and the iOS SDK

### ISSUE THREAD

**Issue by cristianosalla** [SAPDocuments/Tutorials#2648]
The tutorial could be smaller. For example, the configuration of the UI (table view, pickers, labels) could be given in a separated archive, so users could download this starter pack and init the tutorial in the most relevant part: the machine learning API. Thanks!

**Comment by qualiture** [comment]
Hi Cristiano,

Thank you for your feedback. Unfortunately, due to legal reasons, we are not allowed to provide downloadable application code (archive, Git, etc) for iOS SDK apps. 

I agree it would have reduced the time to complete the tutorial, but then, the main goal of this tutorial is to learn how to connect to the ML API, and how to invoke / bind its functions / events using the SAP Cloud Platform SDK for iOS. The focus really is on the iOS SDK, not on SAP Leonardo.

I hope this explains a bit!

Kind regards,
Robin

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
