### ISSUE TITLE
MovieLens recommendation machine learning tutorial : data.hdbti error

### ISSUE THREAD

**Issue by FireFighter1017** [SAPDocuments/Tutorials#2759]
When trying to save the data.hdbti file I get the following error:
Error while writing file /public/aa/movielens/hdb/data.hdbti: allocation size overflow

**Comment by adadouche** [comment]
Hi

Just make sure, you are using SAP HANA, express edition server + apps on an instance that has at least 24gb of RAM.

Can you tell which SP of HXE you are using?

Have you tried running the hxe_gc.sh to clear up some resources?

Thanks

**Comment by FireFighter1017** [comment]
HANA Cloud Platform

> Hi
> 
> Just make sure, you are using SAP HANA, express edition server + apps on an instance that has at least 24gb of RAM.
> 
> Can you tell which SP of HXE you are using?
> 
> Have you tried running the hxe_gc.sh to clear up some resources?
> 
> Thanks

HCP

**Comment by FireFighter1017** [comment]
I just restarted HCP and I still get the same error message

**Comment by adadouche** [comment]
Can you share the tutorial link? As I have one for HANA on SCP and one for HXE, so I want to make sure we are talking about the same

**Comment by FireFighter1017** [comment]
> Can you share the tutorial link? As I have one for HANA on SCP and one for HXE, so I want to make sure we are talking about the same

https://developers.sap.com/tutorials/cp-hana-aa-movielens-01.html#3bc347f0-6026-4509-a868-82ebf651b7b0

**Comment by adadouche** [comment]
Thanks. So you are using the SCP HANA MDC instance scenario.

Did you create the instance for the tutorial series or was it there before?
The reason I'm asking is because these instances only have 6GB of RAM allocated which is very limited.
So I'm wondering if you may have other things in there already.

The other possibility (which I won't be able to help much), is that the HANA MDC server you were assigned to is experiencing memory issue.
Unfortunately, there is nothing I can do if this is the case except ask you to create a new SCP account with a different email address. You should get assigned to a different HANA MDC server who may be ok.

Off course you can export your current content, and import it back in your new account.

Sorry for the inconvenience.

**Comment by FireFighter1017** [comment]
I created this database for the sole purpose of this course and created the account right before I started this course.
I have attached a snapshot of services.  maybe it can give you a hint about storage?

![capture](https://user-images.githubusercontent.com/23411416/48109937-81867d00-e217-11e8-9231-90a6f8c95bda.PNG)

That being said, I find pretty interesting your comment about the server I'm on having some memory issues... Ain't HANA in-memory DB?  If the server has memory issues, how reliable can that be?

Anyway, thanks for your help

**Comment by adadouche** [comment]
Hi @FireFighter1017 

It is definitely in memory, but not just a database. As you saw (or trying to see), you can create app, run machine learning etc.

The trial environment still use the HANA 1.0 SP12 and is shared across multiple users. The boxes used beneath it are usually between 244GB and 512GB of RAM each, but as a user you get allocated around 6GB of that. And for your instance to run, it will consume about 4.8 GB upfront, leaving only 1.2 GB for you to use.

Also after the creation of your instance, I found out that some processes will remain, and consume some resources which is why I added a "restart" step to clear that up and make sure you have enough to run my scenario.

Here is for example my MDC instance:

![2018-11-07_08-39-37](https://user-images.githubusercontent.com/1446764/48117382-5298f700-e269-11e8-81a5-e78c0b58f45b.png)

I7N only have 247 GB of RAM, and I get my 6 GB allocation limit, but I'm currently only using 3.3 GB out of that.

Anyway, let's try to debug that.

Can you enable the all the columns in the Cockpit so we can see how much heap is used?

Thanks

@bdel

**Comment by adadouche** [comment]
I just tried the tutorial on a fresh HANA instance and I was able to import the data.

And here is the cockpit content:

![2018-11-07_08-54-39](https://user-images.githubusercontent.com/1446764/48117870-d6071800-e26a-11e8-8a50-cc7b09beeff3.png)

**Comment by FireFighter1017** [comment]
Ok, I reaaaallly feel bad for this one... 
I found traces on the server reporting a bad data format in the movies file... 
Soooo... I openned the csv and ... DOH!  it was an HTML file... I download a webpage instead of the actual file.
I copied the content directly in the csv files on HANA and saved the data.hdbti file again and it got through...!!!!

I'm soooo sorry for bothering you with this and I feel terribly stupid.
Won't happen again!

Thanks for your quick support

**Comment by adadouche** [comment]
Hi @FireFighter1017 

No worries this happens to the best too. 

Usually when you face this problem the message use to be different, something more around "format" not "allocation". So this is why I jumped onto the conclusion that it was more a memory issue.

Don't be sorry, at least you learned how to debug the log files. Having problems and facing errors is the best way to learn for me.

Hope to hear from you soon.

@bdel
