### ISSUE TITLE
Use the Application Router in Cloud Foundry to Connect to ABAP System

### ISSUE THREAD

**Issue by joymike** [SAPDocuments/Tutorials#2911]
Question: 
I have followed this guide and got to the step 7 in testing the app router and it failed. 
I was redirected to the login screen, and after that I get an error showing "Internal Server Error".
URL was routed to https://approuter-demo-xxxxtrial2.cfapps.eu10.hana.ondemand.com/
Nothing in the browser console.
I can see in the network tab, the call failed with error 500.

I can see in the application log:
`{"written_at":"2018-12-19T23:47:42.430Z","written_ts":1545263262430000000,"csn_component":"-","correlation_id":"03de10b9-2222-4832-79cc-cf4631065ef6","type":"log","logger":"nodejs-logger","layer":"/Handler","level":"error","container_id":"10.0.138.82","component_type":"application","component_id":"612342c-f9a2-4fd7-94ca-23ddd8803333","component_name":"approuter-demo","component_instance":-1,"source_instance":-1,"organization_id":"-","organization_name":"-","space_id":"d732222-8607-4e0c-9761-61c81ff2221","space_name":"dev","request_id":"033330b9-d3dc-4832-79cc-cf4631065ef6","msg":"GET request to /favicon.ico completed with status 500 - JWT token does not include scope \"uaa.user\"."}`

I cannot see any errors in the Cloud Connector.

Any help would be much appreciated.

**Comment by JensHaley** [comment]
Could you maybe share your file xs-app.json that you used for your approuter?

One mistake I could imagine is that you may have used a different name for the destination that you created in step 1. If the name of the destination does not correspond to what you have used in file xs-app.json the routing will break. In the tutorial I used **abapBackend1**.

Did you check if the service of the ABAP system is exposed as described in tutorial [Configure your ABAP System to Activate OData Services of Fiori Reference Apps](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html)?

**Comment by johanngoltz** [comment]
I found a [solution](https://answers.sap.com/questions/737207/get-request-to-completed-with-status-500-jwt-token.html) that works for me. Maybe try that one.

**Comment by johanngoltz** [comment]
@JensHaley, any update on this?

**Comment by JensHaley** [comment]
It worked for me when I published the tutorial.
I tried again today and got "internal server error".

I'll check with XSUAA colleagues if they can imagine why the solution you linked to works.

**Comment by JensHaley** [comment]
Hi everybody,

I checked with the XSUAA colleagues and the outcome is:

- it is required to define scope uaa.user as described in this [solution](https://answers.sap.com/questions/737207/get-request-to-completed-with-status-500-jwt-token.html) to make it work.
- the reason is that during the message flow between the application router and the involved components there has to be a token exchange between the application router and the destination service. So the destination instance acts as a service which requires that the JWT token contains the uaa.user scope. It seems to be a similar scenario as the one described in [Accessing Business Service Data](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/783809d7e52f4e14a45945f3f2bad751.html) in the official documentation.
- why it worked before without the uaa.user scope could not be clarified. Probably someone implemented a check that didn't exist before.

I will update my tutorial soon.

**Comment by JensHaley** [comment]
Hi everybody,

I have adjusted step 4, substep4 in my [tutorial](https://developers.sap.com/tutorials/cp-connectivity-consume-odata-service-approuter.html#09e3259a-5398-49c3-a9d7-12679a2def8f). 

Thanks again for reporting this.

@joymike : Could we close this issue now?

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
