### ISSUE TITLE
Import GDELT Data in Amazon Athena

### ISSUE THREAD

**Issue by Funkmyster** [SAPDocuments/Tutorials#3027]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aws-athena-02.html

For "Step 2: Create the database objects"
The expected answer is 40, but the query "select count(distinct year) from gdelt_athena.events" returns 41.

![screenshot](https://user-images.githubusercontent.com/401350/52167112-40055100-26e4-11e9-96c3-fa7d1895469a.jpg)

**Comment by adadouche** [comment]
Hi @Funkmyster,

Thanks for raising this issue, I'll update the validation rule right away.

The S3 bucket file in use as a datasource keep growing which explains why the the result (40) is not correct anymore since Jan 1st.

I'll see how I can limit the loaded data to a smaller amount to both speed up the queries and avoid this issue in the future.

Thanks

**Comment by adadouche** [comment]
In the end I decided to replace the existing validation to avoid this issue in the future. For more details please check [commit](https://github.com/SAPDocuments/Tutorials/commit/cb3bbfd62f1e94427001ed7b01acea13de670e92)
