### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by brighida** [SAPDocuments/Tutorials#3030]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

First of all:  I am a new adept of the fantastic world of HANA.

I'm following some tutorials trying to understand the various development tools.
In this tutorial I came across an error that I can not overcome.

I followed all the steps up to the eighth; at this point when I try to activate the DB module I get the following error:

**Processing grants files... 
Processing "cfg/plain.hdbgrants"...  
Using service "ServiceName_1" of type "sql"
Error: Error executing: GRANT "SELECT","SELECT METADATA" ON SCHEMA "PLAIN" TO "DB_1#OO" WITH GRANT OPTION; 
(nested message: invalid user name: DB_1#OO: line 1 col 55 (at pos 54))
grantor service: "ServiceName_1", type: "sql", user: "SYSTEM"**

[Step logging.docx](https://github.com/SAPDocuments/Tutorials/files/2825872/Step.logging.docx)

**Comment by Lsubatin** [comment]
Hi, 

Please search the community for technical answers (answers.sap.com). You will find this error is quite frequent and happens if you have created the user-provided service pointing to a different database.

If you mapped the tenant database (HXE) to your developer space, you need to stick to the HXE tenant (and not SYSTEMDB). Otherwise, the default for the development space is SYSTEMDB. 

The port when creating the user-provided service is affected by this. If you have the mapping done, the port for the HXE tenant will be 39015 . Otherwise, it will be 39013.

Regards, 

Lucia.
