### ISSUE TITLE
Create a Global ABAP Class

### ISSUE THREAD

**Issue by f4abap** [SAPDocuments/Tutorials#3051]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-create-new-class.html

Please specify the step you are referring to
The validation is to tricky. It's not possible to get a validation of the code easy. That will frustrate people while doing it.

**Comment by BaerbelW** [comment]
I agree with f4abap, that it's not really clear if there's anything substantially wrong with the code entered in the box, or if it's just not recognizing the provided solution (which seems okay if actually added to the class where it doesn't give any syntax warning).

Perhaps these types of "test yourself" exercises where code-snippets are involved need to be done differently, e.g. by providing 3 suggested solutions of which only one is correct and you just have to pick the correct one.

As of right now I cannot complete this tutorial as I don't have a clue what is still wrong after having tried various options. And this is frustrating ....

**Comment by julieplummer20** [comment]
Hi Florian, hi Baerbel,
OK, there seem to be several aspects here.
1. I will start by simplifying the test, so that you only have to create a method definition, not a table type.

2. In the meantime, here is the solution. Did you try this? 
If so, this is a bug. I'll loop in Daniel.
If not, what did you try instead - so that I can word the question better? I mean, if you tried loads of things, one or two examples would be helpful.

TYPES: ty_table_of_customers TYPE STANDARD TABLE OF SNWD_BPA WITH DEFAULT KEY.
METHODS get_customers_from_db
RETURNING
VALUE(result) type ty_table_of_customers.

3. I find the "3 suggested solutions" / multiple choice thing difficult to implement in practice. I honestly can't imagine what the "wrong" answers should like. If you have any suggestions, that would be great. Either way, I think we need to sort out the underlying issue with the evaluation tool - make it more tolerant, or have a "Contact" button or something (These are just my ideas. Not official.)

4. I have your other issues in my inbox, so will deal with them asap. I will start, however, by simplifying the validation.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Hi all,
Created a new issue for this: [#3086](https://github.com/SAPDocuments/Tutorials/issues/3086)

**Comment by julieplummer20** [comment]
Hi [https://github.com/BaerbelW], hi [https://github.com/f4abap],
Since I have created a new issue for this, do either of you object if I close this?
I will simplify the code.
Thanks for the feedback; it is good to tighten these tutorials up asap.
Cheers Julie.

**Comment by f4abap** [comment]
No problem, you can close this one. I have a look at the other:-)
