### ISSUE TITLE
Configure the SAP HANA R integration with SAP HANA, express edition

### ISSUE THREAD

**Issue by xanderrijken** [SAPDocuments/Tutorials#3057]
Tutorial URL: https://developers.sap.com/tutorials/mlb-hxe-setup-r.html

Could you pls help regarding step 3?
How to get the SAPJVM on suse in VirtualBox?
I tried to use curl, but no succes.... :(

Or is this on the localhost?

Hoping to hear from you soon.

Kind regards

Xander

**Comment by adadouche** [comment]
Hi @xanderrijken 

In order to download the SAP JVM, you will need to accept the term and condition which is not straight forward using cURL.
It also implies that your VM has access to the internet which is not always the case.

When trying to do it from wget/cURL you will need to skip the certificate check and then add the cookie in the header.

Your link should/would look like this:

```
wget --no-check-certificate -c --header "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt" <<paste the link here>>
```
An alternative way would be to download it and transfer it from the host to the VM.

Regards
