### ISSUE TITLE
Create a CDS view (ABAP)

### ISSUE THREAD

**Issue by f4abap** [SAPDocuments/Tutorials#3072]
Tutorial URL: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html

All steps do not have the button "Done" below. That lead to that the group says that I stay at 50%

**Comment by julieplummer20** [comment]
Hi Florian,
I have not yet added validation to this tutorial. It needs a thorough overhaul.
The tutorials that should be up-to-date are all in the mission: https://developers.sap.com/mission.abap-dev-get-started.html . 
I cannot add validation to the other group at the moment, since I have a deadline for ADT 3.0 / ABAPPaaS 1902. 
Do you want me to quickly add DONE statements? Does it make sense without validation?
PS: I will deal with your other issue asap - feedback is always good.
Best wishes Julie.

**Comment by f4abap** [comment]
It does make sense also without. No problem if this will take a while. Just wanted to put attention on it. 
IF you need help and I can do it in a proper way, let me know.
BTW: The tutorials are awesome. I love it and it makes it so much easier to onboard people.
Best Florian

**Comment by julieplummer20** [comment]
"BTW: The tutorials are awesome. I love it and it makes it so much easier to onboard people." - thanks - always good to know.

"IF you need help and I can do it in a proper way, let me know." - well actually, yes. The hardest part for me is gauging the difficulty of the validation questions - too hard, too easy, too hard to explain etc. So, if you are unhappy with any of the validation questions, please let me know - and *if possible* could you perhaps suggest an alternative? (I realize this is actually my job, but that would be really helpful.)
Anyway, I will start work on validation for CDS this week. May not be finished though, and I will be on vacation (Fasching!) next week.
Best wishes Julie.

**Comment by f4abap** [comment]
I will do, what way do you prefer for the answers. Just a comment here or mail / slack

**Comment by julieplummer20** [comment]
Thank you. I don't have many people messaging me on Slack, but email and GitHub are both fine - whichever of those 2 works for you.
Cheers Julie.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
