### ISSUE TITLE
Connect to Microsoft Graph

### ISSUE THREAD

**Issue by equilibrium999** [SAPDocuments/Tutorials#3077]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-ms-graph-connect-graph.html

Please specify the step you are referring to:
I've done the tutorial and it's successful.
However, I have a scenario: the UI5 application is running via a launchpad, not a standalone application.
Can anyone please show me how to configure the redirect url in App Registration since it doesn't allow a long url or with query parameters?
Thanks
Tri

**Comment by IObert** [comment]
Hi,

awesome that you were able to finish the tutorial successfully. This is a really good followup question and  I have to admit I don't know the answer to this question :( . 
I'll close this issue here since github issues are for technical issues with the tutorial.

I've seen that you asked the same question[ in the SAP Community ](https://answers.sap.com/questions/752284/how-to-connect-to-microsoft-graph-api-through-an-u.html) and will post a answer to this once I come up with one.
