### ISSUE TITLE
Import the MovieLens dataset (MovieLens App)

### ISSUE THREAD

**Issue by stephenkringas** [SAPDocuments/Tutorials#3084]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-movielens-03.html

Step 10 - Validate Import
I'm trying to submit the number of rows that have been loaded into the table "ratings" - 100,836

It says the answer is incorrect. I have uploaded the small dataset found here - https://grouplens.org/datasets/movielens/latest/

**Comment by adadouche** [comment]
Hi @stephenkringas,

As stated in step 1:

***If you have additional capacity resources, you can run this tutorial series with the larger datasets, but the validations steps implemented were built based on the small dataset.***

Which is why I provide links to the dataset files in Step 5: Import the dataset CSV files.

Please make sure to use the provided links instead.

Thanks

**Comment by adadouche** [comment]
clarification added in https://github.com/SAPDocuments/Tutorials/commit/6688e84dda30a1c3b16a10b3adcc74f6c43e09fd

**Comment by stephenkringas** [comment]
Thanks for the clarification. Regards,
 Stephen
