### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by dazowens** [SAPDocuments/Tutorials#3089]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

Please specify the step you are referring to Step 5

The data has changed in the sandbox, so when the results are pasted, they do not match the values that it is being checked against once the answer is submitted..

**Comment by thecodester** [comment]
@shilpavij Do you know someone who can review this issue?

**Comment by shilpavij** [comment]
Meredith Hassett is the owner of this tutorial. Kindly contact her

**Comment by MichaelCzcz** [comment]
@mhassett92 any updates?

**Comment by mhassett92** [comment]
Hi all,
I apologize for the delay. I have transferred into a new roll at the company last year and am behind on managing my older tutorials.

I looked into this and it appears as the data in the Sandbox has changed which is why you are seeing an incorrect result. Unfortunately at the same time we are also having an issue with the authentication for the SFSF APIs in the Sandbox, so I cannot adjust the data to match the current set. I have updated the rule to match the value of User('1') which is pasted below while I wait to hear from the API Product team so you can mark the tutorial as complete.

Apologies and thanks for your patience!
Meredith

**Comment by mhassett92** [comment]
"lastName" : "Trombley", "firstName" : "Francois", "jobTitle" : "Assembly Manager"

**Comment by mhassett92** [comment]
same as issue #3542
