### ISSUE TITLE
Create a sample application on SCP Neo using SAP S/4HANA Cloud SDK

### ISSUE THREAD

**Issue by scurry888** [SAPDocuments/Tutorials#3185]
Tutorial URL: https://developers.sap.com/tutorials/s4sdk-scp-neo-sample-application.html

Please specify the step you are referring to:

*** I am able to get 'remote deployment'(step 6) to work, but not 'local deployment' (step 5).  I'm trying to use IIS on Windows 10.  Should I be using Tomcat instead?

**Comment by karstenmelato** [comment]
It is recommended to use ‘local deployment’ for testing your application in a SCP-like environment; with similar behavior as having it run remotely on SCP Neo or CloudFoundry. This “SCP-like” environment is established with a modified tomcat container, which is started from a Maven plugin and includes particular SAP libraries into the application classpath.
 
Hence running your packaged application *.war file on ANY server (private Tomcat, IIS) will not work, because of the missing SAP libraries. You are required to use the Maven commands as described in the tutorial. The maven command “mvn ... scp:push -pl application” will create the temporary (SAP-branded) tomcat server in the application folder to host the generated *.war file.

**Comment by scurry888** [comment]
Thank you for your explanation and insight.

**Comment by scurry888** [comment]
Karsten - I decided to re-open the issue:  I get a 404 when I try to navigate to http://localhost:8080/hello in the Chrome browser.  Attached is the output from the mvn scp:clean scp:push -pl application command, along with logs from SAP's temporary Tomcat server:

[Mvn_clean_push_output.txt](https://github.com/SAPDocuments/Tutorials/files/2993182/Mvn_clean_push_output.txt)


[jpaas_audit_log.log](https://github.com/SAPDocuments/Tutorials/files/2993173/jpaas_audit_log.log)

[ljs_trace.log](https://github.com/SAPDocuments/Tutorials/files/2993174/ljs_trace.log)

[localhost_access_log..2019-03-21.txt](https://github.com/SAPDocuments/Tutorials/files/2993175/localhost_access_log.2019-03-21.txt)

**Comment by karstenmelato** [comment]
Hi,

“HTTP Error 404” shows us the web server is running, which is good.

For more recent versions of S/4HANA Cloud SDK, we changed the path on which the application is being hosted from “/” to “/[NAME]-application”. So assuming your application is called “firstapp” you will find your website on http://localhost:8080/firstapp-application/hello

**Comment by scurry888** [comment]
Thanks, Karsten - that worked!

**Comment by scurry888** [comment]
For others' benefit:  Another issue I had encountered with this was symbolic link creation was failing until I ran my (Windows 10) command-window as an administrator: "Successfully created symbolic link to SAP CP Neo SDK: C:\SCP_Java_Projects\masssalesorders\application/scp/sdk -> C:\SCP_Java_Projects\masssalesorders\application/scp/sdk-1.44.12"
