### ISSUE TITLE
Import the dataset in your SAP HANA instance - STEP 10

### ISSUE THREAD

**Issue by gcasilva** [SAPDocuments/Tutorials#3350]
Tutorial URL: https://developers.sap.com/tutorials/cp-hana-aa-movielens-01.html

STEP 10: 
[11:34:55] Error while activating /public/aa/movielens/hdb/user.hdbrole:[public.aa.movielens.hdb:user.hdbrole] role "sap.pa.apl.base.roles::APL_EXECUTE" is unknown

It seems that i don't have the schema SAP_PA_APL on my Catalog, what can i do?

**Comment by adadouche** [comment]
Hi @gcasilva 

Have you run the script from step 3 successfully? Then are you now connected as the MOVIELENS_USER as described in step 4?

Thanks

@bdel

**Comment by gcasilva** [comment]
Hi @adadouche i have run the script from step 3 successfully and i'm connected on MOVIELENS_USER

This is a screenshot of all the schemas i have on my MOVIELENS_USER after running script on step 3 and being connected on MOVIELENS_USER: https://www.evernote.com/l/AIE8jDVdpLdGIZ1af-ctvRA1icFg_uPpZj4

**Comment by adadouche** [comment]
Are you using the trial environment? You are using 1.120.34 but trial is only 1.120.20.

If you are not using the trial on SAP Cloud Platform, then you need to install APL on your HANA system.
In trial, this is preinstalled for all instances.

@bdel

**Comment by gcasilva** [comment]
I'm using the trial on SAP Cloud Platform on their NEO infrastructure, my HANA started on version 1.120.34 by default.
I think they must have already upgraded from 1.120.20 on SAP Cloud Platform.

Screenshot: https://www.evernote.com/l/AIGxpCBHNlBOPK5dhsKOW0LqjxsPqWZDSf4

Is there a quick guide i can follow to install APL on this scenario?

**Comment by adadouche** [comment]
ok, interesting.

Can you go to the **SAP HANA Cockpit**, click on the **General Information** tile.
Then from here, select the **Installed Plug-ins Details** tab and then search for **APL**.

there should be an entry for **SAP_AFL_SDK_APL**.

**Comment by gcasilva** [comment]
Here's the screenshot: https://www.evernote.com/l/AIFb7quVdhpKzo-rc487e2EP4vZ4lLv4Qx8

**Comment by adadouche** [comment]
so, it's installed. that's a good thing.

can you run the following as SYSTEM:
```
select * from "SYS"."AFL_FUNCTION_PARAMETERS" where AREA_NAME='APL_AREA';
```

it should return all the APL functions.

can you run the following as SYSTEM:

```
grant AFL__SYS_AFL_APL_AREA_EXECUTE to MOVIELENS_USER;
grant AFLPM_CREATOR_ERASER_EXECUTE to MOVIELENS_USER;
call _SYS_REPO.GRANT_ACTIVATED_ROLE ('sap.pa.apl.base.roles::APL_EXECUTE', MOVIELENS_USER);
```

**Comment by gcasilva** [comment]
https://www.evernote.com/l/AIF6-BZh_AZMUpk75D2KoB0cTBd3fObw7hs
https://www.evernote.com/l/AIGG4HvD0bVCL5Yt86mG5FpDEpbKwARmJMs

**Comment by adadouche** [comment]
The APL DU was not properly uploaded which is causing the issue with 'sap.pa.apl.base.roles::APL_EXECUTE' role.

This means that you cannot use the procedure mode, and only the direct mode where you need to create the wrappers, all the table types and so on.

You can try dropping your current instance and recreate but usually you get assigned to the same instance in the end.

I was planning on deprecating this series as HANA 1.0 will be retired when HaaS become available on CF.

There is not much I can do to help you since this is the trial environment and there isn't much support available internally for this environment.

The only recommendation I can do is to switch to HXE where I have the following series: https://developers.sap.com/group.hxe-aa-movielens-sql.html

**Comment by adadouche** [comment]
The APL DU was not properly uploaded which is causing the issue with 'sap.pa.apl.base.roles::APL_EXECUTE' role.

This means that you cannot use the procedure mode, and only the direct mode where you need to create the wrappers, all the table types and so on.

You can try dropping your current instance and recreate but usually you get assigned to the same instance in the end.

I was planning on deprecating this series as HANA 1.0 will be retired when HaaS become available on CF.

There is not much I can do to help you since this is the trial environment and there isn't much support available internally for this environment.

The only recommendation I can do is to switch to HXE where I have the following series: https://developers.sap.com/group.hxe-aa-movielens-sql.html

**Comment by gcasilva** [comment]
Ok, thanks for the try anyway @adadouche 
Will try other labs.

**Comment by adadouche** [comment]
Hi, 

Thanks and hope to hear from you soon.
