### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by laksyelugoti** [SAPDocuments/Tutorials#3366]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

Please specify the step you are referring to Step 5. 

I have successfully executed and submitted the result for Step 5., but it appears that the answer is incorrect. I have tried results that I got for including Top 5 and without  Top 5.  It didn't in both cases.
Attaching the query and results.
[APT - cCURL top 5.txt](https://github.com/SAPDocuments/Tutorials/files/3077926/APT.-.cCURL.top.5.txt)

**Comment by pushnparekh** [comment]
Any update on the issue? What is the format in which the result to be pasted?

**Comment by mhassett92** [comment]
Hi all,
I apologize for the delay. I have transferred into a new roll at the company last year and am behind on managing my older tutorials.

I looked into this and it appears as the data in the Sandbox has changed which is why you are seeing an incorrect result. Unfortunately at the same time we are also having an issue with the authentication for the SFSF APIs in the Sandbox, so I cannot adjust the data to match the current set. I have updated the rule to match the value of User('1') in your attached text file while I wait to hear from the API Product team so you can mark the tutorial as complete.

Apologies and thanks for your patience!
Meredith

**Comment by mhassett92** [comment]
same as issue #3542
