### ISSUE TITLE
Add API Business Hub API to a UI5 Application

### ISSUE THREAD

**Issue by laksyelugoti** [SAPDocuments/Tutorials#3368]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-api-ui5-app.html

Please specify the step you are referring to Step 7.

Code needs to be corrected or fixed..
I have this code working after modying as below..
Instead of using : var userResults = new JSONModel({"data": {}});
I used:    var userResults = new sap.ui.model.json.JSONModel();

**Comment by mhassett92** [comment]
Hello, 
The reason the provided code would have not worked is because you forgot to include the define statement in your controller. In the future, make sure to follow along with each code snippet. By defining the JSONmodel in the function definition, you can reuse JSONModel throughout the controller without having to specify the sap package path.

**sap.ui.define([**
	"sap/ui/core/mvc/Controller",
	**"sap/ui/model/json/JSONModel"**
], function(Controller, **JSONModel**) 

Thanks!
Meredith
