### ISSUE TITLE
Set up Secure Tunnel between ABAP System and SAP Cloud Platform (CF)

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#3434]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-create-secure-tunnel.html

Please specify the step you are referring to:

I followed the steps in this tutorial for my cloud foundry trial, but still cannot seem to connect to my backend system. I checked that my internal host details are correct. What are the possible reasons why the status is Not Reachable? Thanks!

**Comment by JensHaley** [comment]
One thing that comes to my mind is that it's always safer to use the IP address (x.y.z.n) as internal host to avoid that the connection is broken due to DNS issues.

Another good check is to see whether you can connect to your OData service independently from the Cloud Connector, so just by using transaction /n/IWFND/MAINT_SERVICE in your ABAP system. See step 6 in the first tutorial of this group ([Configure your ABAP System to Activate OData Services of Fiori Reference Apps](https://developers.sap.com/tutorials/cp-connectivity-configure-fiori-reference-apps.html)). To be absolutely sure, use the "Call Browser" option (substep 7). Did this work for you?

If that's all fine, the next step for me would be to check the logs of the cloud connector.

Let me know if this helped to solve your issue.

**Comment by jinigirl** [comment]
Hello Jens,

I tested again today, and status is now reachable.
Probably there was an issue somewhere earlier, but now its working fine.
Thanks!

Jini

**Comment by JensHaley** [comment]
That's great! - Could you please close this issue then?

Thank you,
Jens

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
