### ISSUE TITLE
Extend a Workflow Definition with an Exclusive Gateway

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3443]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-03-add-excl-gw.html

Please specify the step you are referring to Step 4.
Hello,

I think the definition of defining the User Interface is a litte bit tricky because you don´t need the definition of the SAPUI5 Component.

Best regards

Marco

**Comment by qmacro** [comment]
Hi @marcobuescher - thanks very much for the feedback. I'm not quite sure what you mean, but I'm guessing you're referring to the fact that a custom UI5 component is not absolutely necessary here because Workflow Forms can be used. 

If that is what you mean, you are right, but this tutorial is deliberately using a UI5 component for the reason given in the referenced and directly preceding tutorial [Add a User Task and Generic UI to Your Workflow](https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html): 

_"The Workflow Forms feature is great for building UIs without any coding, but if you want to take the first steps towards building your own custom UIs, this tutorial will show you what’s involved."_

In the same area as this reason, there's also a link to a [beginner tutorial group](https://developers.sap.com/group.cp-workflow-service.html) showing the use of Workflow Forms.

We've kept this UI5 Component usage in here because folks sometimes struggle to know how to start if they want to build special UIs that go beyond what Workflow Forms can offer.

Hope that clarifies things. Thank you!
