### ISSUE TITLE
Display List Element Details

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#3471]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-webide-display-list-details.html

Please specify the step you are referring to

In the step3 ther is not any question.

In the step6 my url is not valid but it should be correct:
https://xpmgpqomdun7uwzfmta-app-approuter.cfapps.eu10.hana.ondemand.com/sapcpcftutorialapp-1.0.0/extended_runnable_file.html#/undefined

**Comment by IObert** [comment]
Hi @RubenRollano,

thanks for mentioning this.
You're absolutely right. There should be a "Done" button after step 3. I'll fix this.

About your other issue: It seems that there's something wrong with your code. The URL should end in
`/Detail/<Number>`. This is the part of the URL the regex is checking for.

Please let me know if you can't find the root cause of this bug.

**Comment by IObert** [comment]
keeping it open until I get a confirmation (it might take some time until the change arrives in the production system)
