### ISSUE TITLE
Install the MultiApps Cloud Foundry CLI Plugin

### ISSUE THREAD

**Issue by marcobuescher** [SAPDocuments/Tutorials#3481]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html

Please specify the step you are referring to Step 3 Install the Plugin.

I tried to install the Plugin, but it didn´t work. (I started the console also with admin priviledges.)

Can you help me?

![Unbenannt](https://user-images.githubusercontent.com/10000063/57569413-f750e880-73f4-11e9-9e3a-9f43c7090d3c.JPG)

**Comment by IObert** [comment]
Hi @marcobuescher,

this error is odd. According to the [CF doc](https://cli.cloudfoundry.org/en-US/cf/install-plugin.html) it should work like this on Windows as well. 
It seems that this is in "internal CF CLI" issue as it says it cannot execute `mkdir` in the path `.cf/plugins/temp...` and the issue is reported [here](https://github.com/cloudfoundry/cli/issues/1259) and [here](https://www.pivotaltracker.com/n/projects/892938/stories/152311600).

Do those suggested solutions work? Please let me know, so I can add a note to the tutorial.

**Comment by IObert** [comment]
Since a couple of weeks, you can also install this plugin from the community repository directly:
```bash
cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
cf install-plugin multiapps
```

Please reopen this issue if this doesn't work for you.

**Comment by marcobuescher** [comment]
Thanks a lot! This works for me...

Regards

Marco
