### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#3484]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to

Steps 1 - 4:
There's a template, "SAPUI5 Application", that creates the MTA + HTML5 module in one wizard.

**Comment by IObert** [comment]
Thanks for your feedback. Currently, there are some "issues" with this wizard, which is why we currently stick with "manual setup".
a) This generated doesn't ask the user if (s)he wants to use the html5 app repo server. This service is atm only available in the EU10 region. E.g. users of other regions shouldn't use this service
b) The generator creates a destination service, but doesn't bind it to the app router. This step would also have to be done manually.

Later, when the other regions offer the same service, we might change the recommended wizard in this tutorial.
Obviously, you can already use this tutorial today, if you wish.
