### ISSUE TITLE
Extend a Business App to Consume an S/4HANA Service

### ISSUE THREAD

**Issue by lambavikas** [SAPDocuments/Tutorials#3508]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-s4hana-01.html

Please specify the step you are referring to
While following this tutorial we are getting a lot of errors in that refer to build failures. Specifically once we import the external S4HANA files into the project (Step 4)
 and try to run the Java service it simply fails. I tried replicating it in our production as well as trial accounts and get same problems.

![Error](https://user-images.githubusercontent.com/47255819/57871852-50939000-77d8-11e9-9171-bb39bc30710b.png)

I had done this project 2 months back and then it worked perfectly fine but now it seems the underlying templates use newer build resources when we create a Web IDE project and those are failing to build.

Any pointers will be greatly appreciated.

**Comment by chgeo** [comment]
This has been identified as an issue, and is fixed with the upcoming version of cds this week.
See the this commit for a workaround. Apply it on the top-level package.json (not the one in db/).

Background: the new Web IDE version converts the imported service into a CDS model that is too new for the latest publicly available CDS compiler, hence the strange internal error.
