### ISSUE TITLE
Import your TechEd BUILD project into SAP Web IDE

### ISSUE THREAD

**Issue by jinigirl** [SAPDocuments/Tutorials#3540]
Tutorial URL: https://developers.sap.com/tutorials/teched-2017-build-import.html

Hello,

I have cloned a prototype in BUILD, but when I try to import in Web IDE, it says that I don't have a prototype. What should I do to resolve this issue? Should I make changes to the cloned project from BUILD?

**Comment by mhassett92** [comment]
Hello,
Apologies for the delay. There were many updates to the SAP Cloud Platform and SAP Web IDE. This feature was one of the items removed during the update, so unfortunately you cannot proceed this way any longer which is why the tutorial is no longer available.

As a workaround if you are interested in still importing a prototype from BUILD into SAP Web IDE, from the prototype you can download a zip and import using the Import feature in SAP Web IDE.

Again apologies and thank you for your patience.
Meredith
