### ISSUE TITLE
Testing API Business Hub APIs with Curl

### ISSUE THREAD

**Issue by raz-korn** [SAPDocuments/Tutorials#3542]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-test-locally.html

Please specify the step you are referring to: Step 5.
I run the following curl:
curl --request GET  --url "https://sandbox.api.sap.com/successfactors/odata/v2/User?$top=6&%24select=firstName%2ClastName%2CjobTitle"  --header "APIKey: NRjtHA1A7cFhmXgeAiKU3aRWISybFvqW"  --header "Accept: application/json"  --header "Content-Type: application/json"

I attached the results (APITest.txt).

[APITest.txt](https://github.com/SAPDocuments/Tutorials/files/3211227/APITest.txt)

the first user that seemed relevant was with 
"uri" : "https://sandbox.api.sap.com/successfactors/odata/v2/User('1')

the result is
"lastName" : "Trombley", "firstName" : "Francois", "jobTitle" : "Assembly Manager"

I tried putting it into the answer text area, but always received "Sorry that's incorrect...".

Perhaps the service data changed.
I suggest to provide an example of how exactly the answer should look like, e.g. Francois, Trombley, Assembly Manager.

**Comment by VivekRajKM** [comment]
Facing a similar issue.

**Comment by VivekRajKM** [comment]
Any updates ?

**Comment by thecodester** [comment]
@rbrainey @mhassett92 Any updates?

**Comment by mhassett92** [comment]
Hi all, 
I apologize for the delay. I have transferred into a new roll at the company last year and am behind on managing my older tutorials. 

I looked into this and it appears as the data in the Sandbox has changed which is why you are seeing an incorrect result. Unfortunately at the same time we are also having an issue with the authentication for the SFSF APIs in the Sandbox, so I cannot adjust the data to match the current set. I will update the rule temporarily to your above response while I wait to hear from the API Product team so you can mark the tutorial as complete.

Apologies and thanks for your patience!
Meredith

**Comment by mhassett92** [comment]
This issue has been resolved by the API PMs. Thank you!
