### ISSUE TITLE
Add a UI to Your Business Application

### ISSUE THREAD

**Issue by gregorwolf** [SAPDocuments/Tutorials#3561]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-02-add-ui.html

Step 2: Test-run the UI

The tutorial asks you to choose "Choose flpSandbox.html". But the menu entry is called "Run as SAP Fiori Launchpad Sandbox":

<img width="633" alt="Screenshot 2019-05-26 at 16 33 59" src="https://user-images.githubusercontent.com/2639535/58383333-bef50100-7fd5-11e9-80b5-9265241e229f.png">

**Comment by gregorwolf** [comment]
The same issue is also in Tutorial URL: https://developers.sap.com/tutorials/cp-apm-03-add-database.html, Step 5

**Comment by renejeglinsky** [comment]
Hi Gregor,

thanks for your feedback. Let me answer it step by step.
1. Actually it says you should choose Run | Web Application (which should be Run as Web Application) instead of Run | Run as SAP Fiori Launchpad Sandbox. If you follow this, does it work for you?
2. It is kind of the same issue. Step 5 asks you to choose Run | Run Configurations. Inside the run configurations dialog you can the make the described changes. Does that work for you?

Hope this helps. Let me know if you have more feedback or proposals.

Thanks René

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
