### ISSUE TITLE
Add a User Task and Generic UI to Your Workflow

### ISSUE THREAD

**Issue by thecodester** [SAPDocuments/Tutorials#3592]
Tutorial URL: https://developers.sap.com/tutorials/cp-wf-02-add-user-task.html

Please specify the step you are referring to

1) After creating genericusertask, I get these errors in the Problems window. They don’t seem to stop me but made me nervous. I don’t see these errors any more, so not sure why they appeared.

![errors](https://user-images.githubusercontent.com/11659786/58852264-7eb11500-869e-11e9-8682-a4529622e9c9.jpg)

2) In step 7, I'm told to add "webapp" to field "Component Name"  but the field is "Component URL". (This happens in several places.)

3) When I go to MyInbox, the product is "Chai" and not "Tofu" as in screenshot.

**Comment by qmacro** [comment]
Hi @thecodester 

1. The problems are not relevant (they are related to the manifest.json file) and can be ignored. Drawing attention to them in the tutorial was deliberately omitted for simplicity purposes (also because the errors don't always appear). 

2. I have fixed the name of the field - it now says "Component URL".

3. The screenshot is just to show an example, and indeed the learner is explicitly encouraged to try out different product IDs. Nonetheless I have updated the screenshot to refer to Product ID 14 to be consistent with the Tofu product shown later.
