### ISSUE TITLE
Add Annotations to a Managed Association with Core Data Services

### ISSUE THREAD

**Issue by shenjiansj** [SAPDocuments/Tutorials#3593]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-itelo-product-catalog-01.html

Dear colleagues,

I follow the tutorial and build my UI using annotations, but I faced two strange issues:
1.When I open it using sandbox without mock data, it will return internal error when I press error.
![image](https://user-images.githubusercontent.com/5859271/58859237-e5085880-86db-11e9-9237-dab9164971e7.png)

2.I using @lineitem with my table column but the first column is disappear no reason..
![image](https://user-images.githubusercontent.com/5859271/58859266-f5b8ce80-86db-11e9-8ee0-45693591c530.png)

Could you please guide me?

Best Regards,
Jay.

**Comment by thecodester** [comment]
@renejeglinsky Also, your name on this one is your GitHub ID. When you commit to Git, make your name the name used for the commit.

**Comment by renejeglinsky** [comment]
Hi @shenjiansj ,
from your sceenshots I can tell that you are not following the tutorial but I can't tell what exactly the problem is. Let me ask some questions:

In which region is Neo and in which is CF in your scenario?
What kind of annotations have you used?
Have you build the CDS files?

Regards,
René

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
