### ISSUE TITLE
Import your SAP Build project into SAP Web IDE

### ISSUE THREAD

**Issue by DI9-dev** [SAPDocuments/Tutorials#3705]
Tutorial URL: https://developers.sap.com/tutorials/build-import-webide.html

Please specify the step you are referring to while selecting Available prototypes it is only showing SAP CSR but not the Inventory Dashboard. I am using the Trial version. 
![Sap build system](https://user-images.githubusercontent.com/52600567/61143026-2213f780-a49f-11e9-9d63-7c7baa9e339f.PNG)

**Comment by mhassett92** [comment]
Hello,
Apologies for the delay. There were many updates to the SAP Cloud Platform and SAP Web IDE. This feature was one of the items removed during the update, so unfortunately you cannot proceed this way any longer which is why the tutorial is no longer available. 

As a workaround if you are interested in still importing a prototype from BUILD into SAP Web IDE, from the prototype you can download a zip and import using the Import feature in SAP Web IDE. 

Again apologies and thank you for your patience.
Meredith
