### ISSUE TITLE
Create an SAPUI5 App from the Command Line

### ISSUE THREAD

**Issue by eprsonline** [SAPDocuments/Tutorials#3724]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-sapui5-local.html

Please specify the step you are referring to Step 5

Befpre deployment npm configuration has to be updated for SAP specific npm registry
"npm config set @sap:registry https://npm.sap.com"

Otherwise the Build fails as it is unable to process SAP specific npm registry

**Comment by IObert** [comment]
thanks for opening this bug! 

You're right that we don't specify the npm registry globally here, good catch! I don't think this is necessary as there's the `.npmrc` config file of the project. 

The issue is that this file isn't set up correctly by the generator. I'll fix this issue directly in the generator, thanks for pointing this out!
