### ISSUE TITLE
Manage APIs with Policies "Unable to update API"

### ISSUE THREAD

**Issue by HubertWeber** [SAPDocuments/Tutorials#3854]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-apis-manage.html

Step 3: Set limit -> 5. Click Save on the next screen. does not work, get a simple error message "Unable to update API".

If I want to delete API_SALES_ORDER_SRV (Sales Order - Create, Read, Update, Delete (A2X)) I get the error message Cannot delete API wit a more detailed description: Unable to delete the API Proxy API_SALES_ORDER_SRV; API Proxy is associated with one or more API Proxies.
[Req ID: 29e2d5b6-7f78-4aa8-869d-a56716eadbcb]

**Comment by shilpavij** [comment]
Hello Colleagues,
Two things here..
1. Check if all the mandatory fields are filled correctly.
2. You can delete the proxy, since it is associated with one more proxy you get this message.
Solution: Delete the other proxy first and then try to delete this or You can start creating a new proxy by selecting a new base path.

Regards
Shilpa

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
