### ISSUE TITLE
Prepare and upload your Dataset for Image Classification Retraining

### ISSUE THREAD

**Issue by NoaJunod** [SAPDocuments/Tutorials#3861]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-retrain-image-classification-02.html

Hi there, I am pretty new to SAP and I was following your tutorial "Customize the Image Classifier Machine Learning Foundation services on your trial SAP Cloud Platform for Cloud Foundry" to get started into Machine Learning. 

When I reached Step 4 of the "Prepare and upload your Dataset for Image Classification Retraining"-part I ran into an error: When trying to execute the "cf sapml fs put"-command I get the error message "The specified bucket does not exist.". 

Do you have an idea what the problem might be?

Thanks in advance 
Noa

**Comment by sebastianduque7** [comment]
Hello:
I have the same issue. I could execute "cf sapml fs init" but then i cannot execute put command.
Did you find a solution ?
Could you help me , please?

**Comment by NoaJunod** [comment]
> Hello:
> I have the same issue. I could execute "cf sapml fs init" but then i cannot execute put command.
> Did you find a solution ?
> Could you help me , please?

No I haven't found a solution yet, sorry.

**Comment by karimmohraz** [comment]
it seems that there was a misconfiguration regarding the trial account. This is fixed now.
Please do cf logout and logoin again. After command 'cf sapml fs init' it should work.
Note: you can get the storage credentials here:
<IMAGE_RETRAIN_API_URL>/storage
(The endpoint should look like xxxx.files.yyyy....com rather than xxxx.storage.yyyy....com.)
As an alternative to cf sapml fs put you can also use a [3rd party tool](https://help.sap.com/viewer/ed8bf217360e4ad7bcbec7707c017a82/1908B/en-US/73c2e6275a414b52a7bb94f287aa7821.html) or the minio browser for uploading the data.

**Comment by sebastianduque7** [comment]
Hi all, I comfirm that this is already fixed. I could execute the example correctly.
Best regards
Sebastián
