### ISSUE TITLE
Connect with Eclipse to HANA on GKE

### ISSUE THREAD

**Issue by wilchemh** [SAPDocuments/Tutorials#3935]
After followign this tutorial.
https://developers.sap.com/tutorials/hxe-k8s-advanced-analytics.html

I want to connect to the hana instance thru eclipse with the hana tools, but when I put in the external IP, instance number and tenant name it just says the host is unreachable.

Curious if anyone know what is missing that would allow this configuration to be reachable from Eclipse with hana tools.

**Comment by Lsubatin** [comment]
There is no reason for HANA studio not to work if SQLPAD works, though I haven't tried it since its deprecation.

This forum is for problems with the content of the tutorial and not tech support. Please ask a question in answers.sap.com including screenshots of how the same parameters work in SQLPAD and the trace log from HANA Studio.
