### ISSUE TITLE
Set Up a Basic Mock S/4HANA Service

### ISSUE THREAD

**Issue by adadouche** [SAPDocuments/Tutorials#3958]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-1-mock-service.html

This is for step 3.

The link to the Download for API_BUSINESS_PARTNER.json should be something like this so that you can directly save instead of going to GitHub, then switch to the raw viaw:

https://raw.githubusercontent.com/SAPDocuments/Tutorials/master/tutorials/cap-cloudsdk-1-mock-service/API_BUSINESS_PARTNER.json

**Comment by qmacro** [comment]
I'd prefer to leave this as it is - it seems nobody had an issue with this in Day 1 of SAPTechEd and I like to expose people to how tools like GitHub actually work, rather than try to mask it from them. So on reflection, I will leave this as it is. But seriously, thanks for this sort of feedback, keep it coming!
