### ISSUE TITLE
SAP HANA XS Advanced - Clone and run SHINE applications

### ISSUE THREAD

**Issue by jiayiwangjw** [SAPDocuments/Tutorials#3992]
Tutorial URL: https://developers.sap.com/tutorials/xsa-ml-e2e-access-shine.html

I have completed step 5.

In step 6, I only see folder user-db, core-db, user-xsjs, but I don`t see user-js, core-js, user-java so that I am not able to run as node.js application in these 3 folders.

I run as node.js application in folder user-xsjs successfully. But failed in running launchpad in the web folder. 

Could you confirm if it is correct that I dont have folder user-js, core-js, user-java?

**Comment by Lsubatin** [comment]
This tutorial is pending deletion. I would recommend following the instructions in the README file for the SHINE repository: https://github.com/SAP/hana-shine-xsa/blob/master/SHINE-XSA.md 

You would run core-node and core-xsjs for SPS04. Also, please check the dependencies listed ion the readme as there are some that will be missing for the SPS04 version: https://github.com/SAP/hana-shine-xsa/blob/master/SHINE-XSA.md 

It is correct that you do not have such folder in SPS04.

**Comment by thecodester** [comment]
I cannot delete the tutorial because:

  - This tutorial makes use of the access-shine tutorial: https://developers.sap.com/tutorials/xsa-cross-container-access.html

  - This tutorial make use of the access-shine tutorial: https://developers.sap.com/tutorials/xsa-cross-container-access.html

I can remove the links from those 2 tutorials, but it seems the user would need help of the access-shine tutoriAL -- or something similar to do them.

@rbrainey Can you help here?

**Comment by Lsubatin** [comment]
Then a not saying it works for sps03 and sps04 should follow the
instructions in the SHINE readme?

**Comment by rbrainey** [comment]
I have updated the instructions in https://developers.sap.com/tutorials/xsa-cross-container-access.html to instruct folks to use the SHINE XSA-readme rather than this (https://developers.sap.com/tutorials/xsa-ml-e2e-access-shine.html) tutorial.

@jiayiwangjw -- you can refer to the README files in the Shine GitHub repo as the most current reference on how to install and run SHINE on XSA.
