### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by andersonmorita** [SAPDocuments/Tutorials#4020]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to 4

I've been trying to get through that step for a couple of days but I am getting the message "Tenant provisioning failed. Please try after sometime." 

Additionally, I did google that issue and I've found some complaints about that as well.
<img width="510" alt="Screen Shot 2019-10-06 at 11 19 10 AM" src="https://user-images.githubusercontent.com/29006425/66263290-2eec8100-e82b-11e9-87c9-3eb90dd3957a.png">

**Comment by gauthamkrishna-sap** [comment]
Hello,
Thank you for the feedback.
Dev team is investigating this issue and an internal VH incident has been raised on Friday. Will keep you posted on the progress.
Best Regards, Gautham

**Comment by andersonmorita** [comment]
Hi Gautham,

I am glad to hear from you. 
I am looking forward to getting some good news.

Kind regards,
Anderson

**Comment by gauthamkrishna-sap** [comment]
Hi Anderson,

Issue is fixed now. Can you please try the tenant provisioning process again?

Best regards, Gautham

**Comment by andersonmorita** [comment]
Hi Gautham,

I've just created the tenant provisioning.

Thank you. Have a good day.

Best regards,
Anderson

**Comment by rdshankar-coder** [comment]
Hi there, 
Im getting the same error "Tenant provisioning failed. Please try after sometime." , been trying for 2 days
Best Regards,
RDS

**Comment by gauthamkrishna-sap** [comment]
Hi RDS,
Our team is working on this issue & have already identified the root cause. I will update you as soon as it is fixed. 
Apologies for the inconvenience and thank you for your patience. 
Best Regards, Gautham

**Comment by svbhagwat** [comment]
Hi there, I, too am receiving the same error "Tenant provisioning failed. Please try after sometime." even after repeated attempts.  Today is October 30, 2019 - is there a system issue happening now as well?

**Comment by angrasi** [comment]
I have the same problem. I'm trying for the 3rd time. It before was stopping in 52% and now stopped at 89%.
![image](https://user-images.githubusercontent.com/18231899/69013404-1e691380-095e-11ea-8d49-f6378f884798.png)

**Comment by gauthamkrishna-sap** [comment]
Hello All,
Apologies for the inconvenience. Our team is looking into this with high-priority. I will get back to you with an update as soon as I have one. 
Thank you for your patience.
Best Regards,
Gautham

**Comment by svbhagwat** [comment]
Hi Gautham, I have started receiving error when attempting to deploy iFlow
after changes.
Error looks like this:  [CONTENT][CONTENT_DEPLOY][GenerationFailed] : Did
not receive response from Generation and build service
Status gets updated to: "The Integration Flow is not operational."

Even the previously successfully deployed iFlows are not deploying
anymore.
I tried doing a copy of the iFlow and attempted to deploy the copy, no luck.
I tried deploying iFlow from a different trial account, still the same
error.
Things were fine last Friday (11/22); but not this weekend and today
anymore.
Also, is there an SAP mailbox to report such errors?  I do not want to
inconvenience you to the extent possible.
In case my user account details are needed, I am using either of these 2
subaccounts for my CPI trial:

https://p2001841370trial.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces/
https://trial1103subdomain.it-cpitrial01.cfapps.eu10.hana.ondemand.com/itspaces

Thanks and regards
Satish Bhagwat

**Comment by gauthamkrishna-sap** [comment]
Hello Satish,
Can you please admin access to avatar.mosaic@gmail.com in your accounts? Our team will check what the error is. 
About the email channel for reporting errors, we are in the process of setting it up. I will get back to you as soon as it is available. 
Thanks & Best Regards,
Gautham

**Comment by svbhagwat** [comment]
OK, I have now given  Organization Manager, Organization Auditor accesses
to this email ID -  avatar.mosaic@gmail.com in my 2 subaccounts.
Subaccount names are - *trial *(default one when first subaccount was
generated by system) and  *trial1103*.
[image: image.png]
Please let me know if this is what you needed me to do.

Thanks and regards
Satish Bhagwat

**Comment by gauthamkrishna-sap** [comment]
Hi Satish,
Kindly provide Tenant Administrator role collection to this email as well. 
Thanks & Regards, Gautham

**Comment by gauthamkrishna-sap** [comment]
For reference, you can check step 2 of this tutorial please: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

**Comment by svbhagwat** [comment]
OK, done.  Similar screenshot for the other tenant "trial1103" as well.
[image: image.png]
Thanks and regards
Satish Bhagwat

**Comment by chaitalib1** [comment]
Hi,

I am also getting same issue. It is getting stopped at 42%. please refer screenshot below. we have tried it many times, sometimes we get error that "tenant provisioning failed. please try after sometime."

![image](https://user-images.githubusercontent.com/58255812/69718641-e66b8880-1134-11ea-9b77-955a70249ce6.png)

**Comment by gauthamkrishna-sap** [comment]
Hi Chaitali,
Can you please share your global account ID also please? I will request my team to check this. 
Thanks & Regards, Gautham

**Comment by linhhbt** [comment]
Hi Gautham,

I have the same problem. I've tried many times. It was stopping in 36%. Tenant is ed975be5trial

Thanks.
Linh

**Comment by gauthamkrishna-sap** [comment]
@Vikramkulkarni01 can you look into this, please?

**Comment by Vikramkulkarni01** [comment]
Hi @linhhbt , 

Thanks for reaching out to us. 

I understand your concern that tenant provisioning is getting progressed half and then failing. 

Could you please share with me the details of the affected tenant to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by pradeepn15** [comment]
Hi this is Pradeep , I too tried to many times, but the tenant provisioning is not happening at all for the sub account -09177aeftrial

Global Account name & ID -09177aeftrial
Subaccount name and ID -09177aeftrial / 9135b7c5-95e2-40d7-be9a-59c7aab3ac4f
Error message or the screenshots as below

"Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances" Hangs in 0 percentage .

Please check .
![CPI error](https://user-images.githubusercontent.com/64581202/80699832-4c03dc80-8afa-11ea-84db-cc56e2da848c.PNG)

**Comment by svbhagwat** [comment]
All:  Not only these issues; but also for an established CF Trial CPI
setup, the previously successfully deployed iFlows are not deploying
anymore!
I have a CF trial CPI account.
This issue was noticed by me about a week ago.  Per my prior experience
(multiple occurrences!), any such deployment issues usually get fixed
(i.e., they start deploying successfully again) typically around end of the
weekend - is there some kind of restart process that occurs in the
weekend?  But this time, no such luck and the deployment failure issues
have persisted.
Attached is a screenshot of one such failure to deploy.
[image: image.png]
Thanks and regards
Satish Bhagwat

**Comment by teknologik999** [comment]
Hi @Vikramkulkarni01 This is Michael. 

Global Account name & ID ad75e1fctrial / ad75e1fctrial-ga
Subaccount name and ID trial / teknologik999
Error message or the screenshots as below

"Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances" Hangs in 81 percentage .
[New Microsoft Word Document.docx](https://github.com/SAPDocuments/Tutorials/files/4565532/New.Microsoft.Word.Document.docx)

**Comment by Vikramkulkarni01** [comment]
Hi @teknologik999  and @svbhagwat, 

Thanks for sharing the information with us. 

I involved an internal team to investigate the issue further and keep you posted with an update. 

Regards, 
Vikram Kulkarni

**Comment by gouravkumarjena** [comment]
Hello Team,

I am facing issues with my Tenant provisioning. The same is getting stuck after completion of 18 percent. Earlier I thought maybe I will try with a new account. But I faced the same problem. 
Here are my trial account details:

Global Account:  ba30d83atrial
Subaccount: trial
Error Message: 
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Global Account: 931506cctrial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Please do the needful so that I can set up the tenant provisioning successfully. 

Regards
Gourav Jena

**Comment by gauthamkrishna-sap** [comment]
@Vikramkulkarni01 can you please take a look?

**Comment by Vikramkulkarni01** [comment]
Hi @gauthamkrishna-sap , 

Already internal team involved for this concern and the investigation is in progress. 

Regards, 
Vikram Kulkarni

**Comment by Shreyashri91** [comment]
Hello Team,

I am facing similar kind of issues with my Tenant provisioning. It is getting stuck after completion of 18 percent. I closed the browser & retried multiple times. But I can see the same problem persists.
Here are my trial account details:
Global Account: 85aa4789trial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Please do the needful so that I can set up the tenant provisioning successfully.

Regards
Shreya

![thumbnail_image](https://user-images.githubusercontent.com/65550157/82286756-0da46380-99bc-11ea-94e3-bc6d2b6789ef.png)

**Comment by linhhbt** [comment]
Hi Vikramkulkarni01,

I am facing the error message when I access trial sub account. 

![image](https://user-images.githubusercontent.com/64533503/82401957-67bd2b80-9a85-11ea-8d7b-607a060b2a07.png)

Thanks and Regards,
Linh

**Comment by svbhagwat** [comment]
Hi Vikram Kulkarni / SAP expert, Has the renewal of the SCP subaccount
"trial" resulted in the "Cloud Connectors" link disappearing?
BEFORE renewing the "trial" subaccount Vs NOW:
[image: image.png][image: image.png]



Thanks and regards
Satish Bhagwat

**Comment by gauthamkrishna-sap** [comment]
Hi Satish,
We are unable to see the image you have uploaded. Can you kindly please upload it again?
Best regards,
Gautham

**Comment by svbhagwat** [comment]
OK, let me try with an attached MS Word file.

Thanks and regards
Satish Bhagwat

**Comment by svbhagwat** [comment]
Hello Gautham or Vikram, I hope you were able to open the Word file and
realize the issue with the Cloud Foundry trial SCP accounts.
I just want to make sure that the Cloud Connector link visibility is not
tied to any roles/role collections different than those for "Connectivity"
application, i.e., role templates Cloud_Connector_Administrator and
Cloud_Connector_Auditor.
Also, the below screenshot from the Cloud Connector Admin view shows
clearly that the SCP trial instance is successfully created under Cloud
Connector.
[image: image.png]

Despite these, no Cloud Connector link is showing up on the SAP Cloud
Platform, and hence the On-premise Destination entries are not working.
Thanks and regards
Satish Bhagwat

**Comment by mittalnidhi20** [comment]
Hi Gautham,

I have the similar problem..  Existing successfully deployed iflows stopped working at the moment. 
Deployment ends with error:
Error Details
[CONTENT][CONTENT_DEPLOY][InstanceError] : {"message":"TIMEOUT_START","parameters":[1425]}Tenant is ed975be5trial

Tenant: b6a6655ftrial
Subdomain
b6a6655ftrial
Environment
Trial
![image](https://user-images.githubusercontent.com/67317502/85803781-defa7500-b73f-11ea-8d41-09d87e9aec53.png)

Please let me know for nay details further. ALso please confirm if this is something taht can be addressed.

Thank you!
Nidhi

**Comment by svbhagwat** [comment]
Hi Gautham/ Vikram:  Is there issue with the Trial Cloud Foundry CPI?  The
deployment of the integration flows is not completing.  The deployment gets
stuck in status "The Integration Flow is starting."

I would like to make a request to SAP - There needs to be a more formal way
(a web page) for the trial users to communicate ongoing operational issues
with the trial cloud foundry CPI, where we can see the list of issues
logged and status of their resolution by SAP.  If such a setup already
exists, I am not aware of it.

Thanks and regards
Satish Bhagwat

**Comment by svbhagwat** [comment]
Hi Gautham / Vikram:  The deployment issue appears to be resolved sometime
yesterday.  I was able to have my iflows deployed last night; and they were
getting deployed fast as well, sometimes under a minute; but in general
within 2-3 minutes.
So thank you very much for your help with this!

Thanks and regards
Satish Bhagwat

**Comment by sequeirajosebr** [comment]
Hello,

I'm trying to deploy iFlows to my new CPI Trial tenant for days now...:
![image](https://user-images.githubusercontent.com/52257110/88922252-3d86a780-d246-11ea-9022-5d632cb0d5af.png)
 
All the iFlows were on a previous CPI trial tenant, so they're all working (no errors) iFlows. Even tried creating new simple ones, but got the same issue...

Already sent an email to the cpitrialfeedback@sap.com but no response...

Regards.

**Comment by gauthamkrishna-sap** [comment]
Hi Satish,
Thank you for confirming. 
Best Regards, Gautham

**Comment by svbhagwat** [comment]
Hi Gautham, if I may have your attention on one more topic that's remained
unresolved for a very long time - at least since April... that is *on the
Cloud Foundry trial, the Cloud Connector link has been gone from the
"Connectivity" link *- please see enclosed screenshot.  I can create an
entry for the Cloud Foundry SCP trial instance in the Cloud Connector Admin
and it shows a connection in working order; but since there's no Cloud
Connector link present in SCP, any Destinations entry created for
"On-Premise" with the Cloud Connector Location ID reference does not work.
For the same base account, I can establish a Cloud Connector link on my Neo
trial SCP account and set up 'On-Premise' type Destinations, which show
proper connection.
I have checked and can confirm that the user authorizations are proper in
Cloud Foundry SCP (Cloud Connector Admin roles, etc.).  There have been at
least a few instances of questions raised by users in online SAP-related
forums; but I haven't seen anyone addressing the issue.  This issue did not
exist in the early part of 2020, when I was able to make integrations via
on-premise connections established via Cloud Connector.
[image: image.png]

Thanks and regards
Satish Bhagwat

**Comment by gauthamkrishna-sap** [comment]
Dear Satish,
Thank you for your feedback. Can you please try this on our new integration suite trial?
Thanks & Best Regards,
Gautham

**Comment by svbhagwat** [comment]
Hello Gautham, per your nudge, I followed the very recent blogs on
Integration Suite trial from Vikram Kulkarni (
https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html)
and Vinayak Adkoli (
https://blogs.sap.com/2020/08/03/kickstart-your-integration-suite-experience-with-the-launchpad/)
as guide and installed the Integration Suite on Cloud Foundry trial
accounts, using 2 different ways - (i) with active existing user on SCP,
with (a) existing subaccount "trial" as well as (b) a newly added
subaccount "anothertrial", which only had the Integration Suite
subscription and (ii) two instances of brand-new users who had not been set
up on SCP account before.  However, in all of these cases, I noticed the
same - The Cloud Connector link is absent from under the Connectivity
dropdown, despite making sure that proper roles authorizations were made.
Interestingly, in both blogs by Vikram Kulkarni and Vinayak Adkoli, the
Cloud Connector link shows in the screenshots!
[image: image.png]  [image: image.png]

Is there anything missing from role authorizations or configuration setup?

Thanks and regards
Satish Bhagwat

**Comment by gauthamkrishna-sap** [comment]
@svbhagwat The screenshots are missing. Can you please upload the proper screenshots so that I have a context?

**Comment by svbhagwat** [comment]
Hi Gautham, please see the screenshots captured in attached Word file.
Please let me know if any other details are required.

Thanks and regards
Satish Bhagwat

**Comment by vlingutla** [comment]
Hello Gautham, I also followed the very recent blogs on
Integration Suite trial from Vikram Kulkarni (
https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html)
and Vinayak Adkoli ( https://blogs.sap.com/2020/08/03/kickstart-your-integration-suite-experience-with-the-launchpad/ ) but noticed Cloud connector option missing in cloud foundry. Screen shot captured in attached document. Can you please kindly advise what setup need to add get cloud connector and let me know if you need any further details.
[Cloud Connector Link Issue in Cloud Foundry Screenshots.docx](https://github.com/SAPDocuments/Tutorials/files/5042007/Cloud.Connector.Link.Issue.in.Cloud.Foundry.Screenshots.docx)

**Comment by gauthamkrishna-sap** [comment]
Hi,
Can you please entitle your account with the connectivity service? You will be able to add destinations. 
Best Regards, Gautham

**Comment by vlingutla** [comment]
> 
> 
> Hi,
> Can you please entitle your account with the connectivity service? You will be able to add destinations.
> Best Regards, Gautham

Hi Goutham, Thanks for your reply. I can able to add destination using "Destinations" option in Connectivity but I don't see "Cloud connector" option in Connectivity section showing only Destinations in Cloud Foundry trail account. Attached screen shot has details. Please advise and let me know if you need any other information.
[Cloud_Connector_Missing_From_CloudFoundry_TrailAccount.docx](https://github.com/SAPDocuments/Tutorials/files/5051528/Cloud_Connector_Missing_From_CloudFoundry_TrailAccount.docx)

**Comment by gauthamkrishna-sap** [comment]
Hi,
It might be the case is cloud connector is not available on trial anymore. I have to double-check this, sorry!
Best, Gautham

**Comment by Arathi2104** [comment]
Hi Team,

Even I am facing  a similar issue for tenant provisioning and there is no  progress.

![image](https://user-images.githubusercontent.com/70535515/91747952-c2b20300-ebdc-11ea-8f5c-0560aac7e30f.png)


PFB my trial account details:
Global Account: 73f0e391trial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Please do the needful so that I can set up the tenant provisioning successfully.I have been trying it for the last 2 days with no success.

Thanks & Regards,
Arathi

**Comment by svbhagwat** [comment]
Hello SAP team, I am taking this route to check on the CPI outage on the
Cloud Foundry Trial environment which has gone for almost a whole week now!
I had posted that CPI Trial on CF has been not working at least from August
26, 2020 (
https://answers.sap.com/questions/13126640/sap-cpi-cf-trial-not-working-from-8-26-2020.html).
There are a number of similar posts that other people have also posted.
Can you inform the community when a fix may be done and the CPI Trial CF
setup will become available?
Appreciate a status update!

Thanks and regards
Satish Bhagwat

**Comment by haricahy** [comment]
Hi SAP Team,

I cannot access my CPI trial tenant.
Kindly help since I need to backup my iFlow.
the URL : https://d276e0adtrial.it-cpitrial.cfapps.us10.hana.ondemand.com/itspaces

Thanks,
Hari

**Comment by techvaib** [comment]
Hi Team,

I am facing an issue for tenant provisioning and there is no progress.

PFB my trial account details:
Global Account: 7e295650trial
Subaccount: trial
Error Message:
Tenant provisioning activation with Message Queues is in progress. This may take up to 60 minutes.

Please do the needful so that I can set up the tenant provisioning successfully. 

Thanks,
Vaibhav Maheshwari
