### ISSUE TITLE
Enable SAP Cloud Platform Mobile Services in Cloud Foundry

### ISSUE THREAD

**Issue by k-younghwan** [SAPDocuments/Tutorials#4022]
Tutorial URL: https://developers.sap.com/tutorials/fiori-ios-hcpms-setup.html

I tried to create the mobile service on my trial Cloud Foundry account,
I got some warning like this.
[ Mobile Services is not enabled. The service is required for upgrade. Check SAP Help Portal for instructions. ]
Is it general available to all trial accounts, or did I miss something?

![image](https://user-images.githubusercontent.com/55276918/66280087-11cdb600-e8f0-11e9-8eee-0de50abf4a5d.png)

**Comment by jitendrakansal** [comment]
@k-younghwan  

in our recent release we introduced a new "Mobile Services" which is replacing all old mobile services. With this new "Mobile Services", mobile application will be created as a "Mobile Services" service instance instead of an mobile-approuter application deployed under customer space.
For any new trial accounts, we are adding this new service by default (and automatically).
For existing account, it requires manual work.

Please follow as per below:
1. In SCP cockpit, click Entitlements>Subaccount Assignments
2. Select subaccounts from dropdown and click "Go"
![Screenshot 2019-10-14 at 10 26 14 AM](https://user-images.githubusercontent.com/31536700/66737785-2ddfd300-ee6d-11e9-8990-4232be3d3180.png)
3. Click "Configure Entitlements" 
![Screenshot 2019-10-14 at 10 27 42 AM](https://user-images.githubusercontent.com/31536700/66737918-80b98a80-ee6d-11e9-9ba6-3586d83cf8e7.png)

4. Click "Add Service Plans"
![Screenshot 2019-10-14 at 10 28 06 AM](https://user-images.githubusercontent.com/31536700/66737928-84e5a800-ee6d-11e9-88c7-0ed70fb8bfd9.png)

5. In "Entitlements" pop-up window, select "Mobile" from dropdown, scroll down and select "Mobile Services" and then tick the checkbox "lite" and then click "Add 1 Service Plan"
![Screenshot 2019-10-14 at 10 28 29 AM](https://user-images.githubusercontent.com/31536700/66737961-9dee5900-ee6d-11e9-9ec1-7f054d520012.png)

6. Save the changes

![Screenshot 2019-10-14 at 10 30 43 AM](https://user-images.githubusercontent.com/31536700/66738371-9da28d80-ee6e-11e9-97ef-760aeab97214.png)

7. Clear the browser cookies & caches or open Mobile Services cockpit url in an incognito/private window.
Navigate to Mobile Applications> Native/Hybrid, you should see an Upgrade window popping-up , click "Upgrade Now"
![Screenshot 2019-10-14 at 10 33 50 AM](https://user-images.githubusercontent.com/31536700/66738255-4d2b3000-ee6e-11e9-977b-01477c57e2e9.png)

8. existing apps will start upgrading.... (it takes sometime depending on the apps you have in your existing account)
![Screenshot 2019-10-14 at 10 33 56 AM](https://user-images.githubusercontent.com/31536700/66738282-587e5b80-ee6e-11e9-9ef1-8baf32db8895.png)

Once done, that warning message should be gone.

**Comment by k-younghwan** [comment]
Thank you for details jitendrakansal.
With your help, I could solve the problem.
