### ISSUE TITLE
Install the Cloud Foundry Command Line Interface (CLI)

### ISSUE THREAD

**Issue by StargazerAlex** [SAPDocuments/Tutorials#4072]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-download-cli.html
Step 4: Connect the CLI to the cloud region

When connecting to the API endpoint an error appears:
```
cf api https://api.cf.eu10.hana.ondemand.com
Setting api endpoint to https://api.cf.eu10.hana.ondemand.com...
Invalid SSL Cert for https://api.cf.eu10.hana.ondemand.com/v2/info
TIP: Use 'cf api --skip-ssl-validation' to continue with an insecure API endpoint
FAILED
```

This can be circumvented using the "--skip-ssl-validation" parameter but that's not described inside the tutorial and probably not working as intended either. Do the HANA cloud API endpoints not support HTTPS?

**Comment by thecodester** [comment]
@qmacro Can you look at this and see if you can help? If someone else should be assigned to this, let me know (or you can assign yourself). Thanks.

**Comment by qmacro** [comment]
Hi @StargazerAlex thanks for reporting this. I have checked this morning, and a colleague has too, and the SSL warning does not occur any more. I can only think that there was possibly a temporary issue with the certificate which has since then been addressed, or there had been some connection issue. 

Should be working fine now.
