### ISSUE TITLE
Use OData Navigation Properties with the SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by ravipativenu** [SAPDocuments/Tutorials#4084]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-vdm-getbykey.html

Please specify the step you are referring to

I followed the tutorial and it is working. But when i am giving my code output in the last question, my answer is not getting accepted. My answer is as follows. Could you please help.

====================================
import { Request, Response } from 'express';
import { BusinessPartner, BusinessPartnerAddress } from '@sap/cloud-sdk-vdm-business-partner-service';

export function singleBusinessPartnerRoute(req: Request, res: Response) {
    getBusinessPartner(req.params.id)
    .then(businessPartner => {
      res.status(200).send(businessPartner);
    })
    .catch(error => {
      res.status(500).send(error.message);
    });
}

function getBusinessPartner(businessPartnerId: string): Promise<BusinessPartner> {
    return BusinessPartner.requestBuilder()
      .getByKey(businessPartnerId)
      .select(
        BusinessPartner.BUSINESS_PARTNER,
        BusinessPartner.LAST_NAME,
        BusinessPartner.FIRST_NAME,
        BusinessPartner.IS_MALE,
        BusinessPartner.IS_FEMALE,
        BusinessPartner.CREATION_DATE,
        BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS.select(
            BusinessPartnerAddress.BUSINESS_PARTNER,
            BusinessPartnerAddress.ADDRESS_ID,
            BusinessPartnerAddress.COUNTRY,
            BusinessPartnerAddress.POSTAL_CODE,
            BusinessPartnerAddress.CITY_NAME,
            BusinessPartnerAddress.STREET_NAME,
            BusinessPartnerAddress.HOUSE_NUMBER
        )
      )
      .execute({
        url: 'https://my.cloud.erp.com'
      });
  }
=========================================

**Comment by MatKuhr** [comment]
Hi, the question assumes you only pass the query (without return statements or function definitions around it). Also you don't need to select every single field manually. So in summary you can modify your query to look like this: 
`BusinessPartner.requestBuilder().getByKey('1').select(BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS).execute({ url: 'https://my.cloud.erp.com' })` which should get accepted ;)

Since the question just compares your input to the expected code a solution might get rejected based on syntax even if it is semantically correct.

**Comment by ravipativenu** [comment]
Thank you for helping me with this. that worked..:)
