### ISSUE TITLE
Create a Developer User in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by Suncatcher** [SAPDocuments/Tutorials#4087]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-developer-user.html

According to this tutorial there should have been a tile *Maintain employees* but there is not in my Trial Environment. As I get it, this tutorial for creating a user intended only for TechEd attenders, usual tenants on shared trial instance have no admin rights, yes?

**Comment by smile-ot** [comment]
Same issue for me as well.

**Comment by k-younghwan** [comment]
You don't need to maintain your employee in you trial environment.
You just create ABAP instance and you can create your test program.
I could make some samples following this tutorial.

https://developers.sap.com/group.abap-env-restful-managed.html

**Comment by mervey45** [comment]
Hi @Suncatcher  @smile-ot  @k-younghwan, 

this tutorial isn't possible in the trial, that's why we added the license tag. You need a license to do so. Yes, in the trial, you don't have admin rights. You have to check up if there is a license tag or not added to the ABAP tutorials. You can only do tutorials, which are without the license tag for the SAP Cloud Platform ABAP trial. 

Best regards, 
Merve

**Comment by Suncatcher** [comment]
Ok, got it. Just noticed _Requires Customer/Partner License_ tag. 
Closing the issue.
