### ISSUE TITLE
Create OData Entities with the SAP Cloud SDK's Virtual Data Model

### ISSUE THREAD

**Issue by ahusemann** [SAPDocuments/Tutorials#4135]
Tutorial URL: https://developers.sap.com/tutorials/cloudsdk-js-vdm-create.html

Please specify the step you are referring to
Step 4: Wire everything up

The provided JSON for the address creation does not fit the implementation of buildAddress.
As the keys are starting with an upper case character and the fromJson function expects them to start with a lower case.

Thus following does not work
 {
	"Country": "DE",
	"PostalCode": "14469",
	"CityName": "Potsdam",
	"StreetName": "Konrad-Zuse-Ring",
	"HouseNumber": "10"
}
while 
{
	"country": "DE",
	"postalCode": "14469",
	"cityName": "Potsdam",
	"streetName": "Konrad-Zuse-Ring",
	"houseNumber": "10"
}

is working.

Of course the same is true for the next step about entity update.

**Comment by jjtang1985** [comment]
@ahusemann, thank you for reporting this, you are definitely right, the tutorial should be fixed by using the lower case.

@mr-flannery, the attributes of the entity business partner address in edmx/json file are using the upper camel cases, while the generated vdms are using the lower camel case.

It's easy to fix the issue, making the json with the lower camel case.

**Comment by MichaelCzcz** [comment]
@mr-flannery @karstenmelato Has the tutorial been fixed and can the issue be closed?

**Comment by mr-flannery** [comment]
@MichaelCzcz The tutorial has been corrected, so in my opinion the issue can be closed.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
