### ISSUE TITLE
Cloud Integration 

### ISSUE THREAD

**Issue by takismart** [SAPDocuments/Tutorials#4161]
Tutorial: Design and Test Your First Integration Flow
Step 7: Deploy the integration flow

Hi @gauthamkrishna-sap,

I have failed to deploy the integration flow. Error message is as below: 

[CONTENT][CONTENT_DEPLOY][GenerationFailed] : Did not receive response from Generation and build service.

Also, there are no endpoints configured for intergration flow.

Would you please help?
![Image 5](https://user-images.githubusercontent.com/57156004/68255935-83398980-0093-11ea-8325-9088bf4a4e12.png)

**Comment by gauthamkrishna-sap** [comment]
Hello,
Due to high number of iflows deployed on trial tenants, this might occasionally happen. We are working to improve this and ensure the experience is seamless. 
As a short term workaround, kindly redeploy the iflow again. It will most likely work. 
Apologies for the inconvenience & thank you for your patience. 
Best Regards, Gautham

**Comment by takismart** [comment]
Thanks @gauthamkrishna-sap. I re-deployed the iflow. This time iflow was deployed successfully.

**Comment by emarcelino3** [comment]
The same problem here with a very small iflow.

![image](https://user-images.githubusercontent.com/49109616/91744801-63c69c80-eb90-11ea-9393-92da90ff74c8.png)
