### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by bcschaich** [SAPDocuments/Tutorials#4317]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html

Please specify the step you are referring to
In STEP 4.4: Choose Show Instances to see all workflow instances of the onboard workflow definition.
I get an error if using the SuccessFactors system call (so NOT inserting the provided fake data)
Error message:

TypeError: Cannot read property "team" from undefined in <eval> at line number 1Log ID: b5ca681f-54d9-4d61-8fa3-593cadf9f210 | Process Buddy List | 04.12.2019, 18:14:36 |  
-- | -- | -- | --
  | TypeError: Cannot read property "d" from undefined in <eval> at line number 1Log ID: 7a07c5a4-0d89-4c64-9eb5-90010bcb295d

I am not sure what is going on. I just left the values for connection to what was generated in there, so my email adress and the user cgrant.
In case this shall connect to SFSF, I set up this destination, but do not remember to have integrated it anywhere in the workflow. I mean: how does the workflow know where to connect to?

Thanks for any help.

**Comment by ArchanaShukla** [comment]
There are 2 parts of the tutorials. One with SuccessFactors and another without SuccessFactors. If you do not have the SuccessFactors system, please carefully follow the workflow tutorial and adapt the workflow as mentioned. 

You get this error because you have not configured any SuccessFactors system and the workflow definition expects some output from SF APIs.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
