### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by freilinger** [SAPDocuments/Tutorials#4348]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-behavior.html

Hi everybody, 

it is no big deal, but in Step 2.4 and 2.5 we are replacing the coding in Global Class and Local Types completly by copy/pasting something new in. Actually the only difference is, that we are adding the type tt_travel_update and this type is not used in the tutorial (probably in a further tutorial it is). 

Wouldn't it make more sense, to add the type in the later tutorial when it is actually needed and here we do not adjust the generated coding. 

IMHO replacing code with other code by just copy/pasting with no further explanation does not bring a lot of learning experience to the participant. 

Best regards, 
Sebastian Freilinger

**Comment by mervey45** [comment]
Hi @freilinger, 

thank you for your feedback. We will add more information to this step. We have to make these tutorials user-friendly and they also should be suitable for beginners, that's why we did it this way. But we will provide more information on the step you've mentioned. 

Thank you.

Best regards, 
Merve

**Comment by freilinger** [comment]
Thanks a lot for caring, Merve.

**Comment by MichaelCzcz** [comment]
@freilinger Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
