### ISSUE TITLE
Install the Cloud Connector in your System Landscape

### ISSUE THREAD

**Issue by vovaldj** [SAPDocuments/Tutorials#4353]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html

Please specify the step you are referring to Step 3: Install the Cloud Connector.

Facing an issue regarding a dll file missing while installing the Cloud Connector. Tried to reinstall all the prerequisites,  but still facing the same issue.

<img width="576" alt="dll file cc" src="https://user-images.githubusercontent.com/38584469/70770129-30d64180-1d92-11ea-829f-5f498e6fdd8f.png">

**Comment by JensHaley** [comment]
Sorry for the late reply, I was on a long vacation.

I checked with our developer and he thinks that the root cause of the issue might be missing MS visual studio C++ 2013 runtime libraries (vcredist_x64.exe).

Check the third bullet below section _Prerequisites_ in the [official documentation](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/204aaad4270245f3baa0c57c8ab1dd60.html).

Let me know if that helped.

**Comment by MichaelCzcz** [comment]
@vovaldj Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
