### ISSUE TITLE
SAP HANA XS Advanced, Access a classic schema from an HDI container

### ISSUE THREAD

**Issue by RubenRollano** [SAPDocuments/Tutorials#4417]
Tutorial URL: https://developers.sap.com/tutorials/xsa-create-user-provided-anonymous-service.html

Hello, I am in Step 7: Add a synonym of tutorial: SAP HANA XS Advanced, Access a classic schema from an HDI container

In de pop-up where I have to select the data source I can't find any result and I have the error: Error: Not able to find organization: undefined 
![image](https://user-images.githubusercontent.com/25760588/71471813-efea1e00-27d0-11ea-94ab-25048578ed96.png)

In the project setting I can see properly my orgniazation and space.
![image](https://user-images.githubusercontent.com/25760588/71471862-19a34500-27d1-11ea-9056-329e9d50959a.png)

I have build several times the project but with the same result.

**Comment by jungsap** [comment]
Off hand I think there might be something wrong in your mta.yaml since it the dialog doesn't seem to be able to parse and display your bound external services.  You can actually supply the object name and schema name directly in the editor without the value help.  Try building with the manual entry.  I suspect you will still get an error, but it might be more constructive and help find the true root of the problem.  The other thing you could do is post your mta.yaml contents here.  mta.yaml problems can be very difficult to diagnose and often lead to downstream errors that at first seem unrelated.

**Comment by MichaelCzcz** [comment]
@RubenRollano Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
