### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by krisho007** [SAPDocuments/Tutorials#4428]
Tutorial URL: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html

Please specify the step you are referring to
Step 9. 
It says ' @insertonly'. It should have been @readonly.

**Comment by iwonahahn** [comment]
Hi,

The description for step 9 is correct saying "Any GET or DELETE to an order fails since we’ve specified the Orders entity to be **@insertonly** in srv/cat-service.cds." cause we have modified in step 6.3. the cat-service.cds for the Order: "entity Orders @insertonly as projection on my.Orders;"

Best regards,
Iwona

**Comment by MichaelCzcz** [comment]
@krisho007 Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
