### ISSUE TITLE
Use the Optical Character Recognition (OCR) API from a REST Client

### ISSUE THREAD

**Issue by krishnak96** [SAPDocuments/Tutorials#4465]
Tutorial URL: https://developers.sap.com/tutorials/cp-mlf-rest-txt-ocr.html

Hey, there are no code snippets available to use this API in a code. I am trying to build a REST API which leverages the SAP OCR and will be deployed in SAP Cloud Foundry, but I am unable to find a snippet to make the API call.

**Comment by jung-thomas** [comment]
@krishnak96  - can you please specify what part of this tutorial is missing?  I don't see anything missing off hand. Are you just saying that you would like to see some additional content outside this tutorial on how to call this app from Code.  If so that doesn't seem to be within the scope of this tutorial.

**Comment by MichaelCzcz** [comment]
@krishnak96 Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
