### ISSUE TITLE
Get Started with SAP HANA XS Advanced Native Development

### ISSUE THREAD

**Issue by arazumov101** [SAPDocuments/Tutorials#4484]
An interesting and very important tutorial that includes 4 consecutive exercises/steps.
Could not complete / pass the second exercise: XS Advanced, Create Database Artifacts Using Core Data and Services.
The exercises were performed on SAP HANA 2 SPS 04, exactly the same version as indicated on the Project Details slide.
The first surprise you get immediately after creating the project: both builds.js in the folders db and the crv contain the same syntax error: “ESLint: (syntax-parse) Parsing Error: The keyword ‘const’ is reserved”.

It can be fixed by specifying Parser Options or maybe there is some other solution?
/* eslint-env es6 */
/* eslint-disable no-console */

But there is a question about the builds.js files again:
The first slide on the Step 2: Explore the generated artifacts does not have them. The tutorial nothing mentioned about their delete action. 
But actually it does not matter because with/without files in the second tutorial - after choosing Build > Build CDS action the Console provided about fifteen lines of records with final verdict: 

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^": Tags may not have any characters that encodeURIComponent encodes.

Last row include a link to the log with complete information: I did not count but it seems has a couple of hundred records with link to another logs with other hundred records, etc.    
Obviously, I, as a beginner to who this guide is intended, must have the time and patience to understand all this.
There is no information regarding the important package.json files in both db & crv folders. They still have the initial content or have been upgraded? 
As a recommendation, it would be very helpful for "beginners" if the creators of tutorial mentioned at the end of it a list of possible principal issues, or at least give some directions where to look for the necessary information.
Regards,
Andrew R

**Comment by thecodester** [comment]
@arazumov101 I assume you mean the set of 4 tutorials in this group: https://developers.sap.com/group.hana-xsa-cap-get-started.html ?

**Comment by arazumov101** [comment]
Dear Daniel,

Yes, you are right.
Regards,
Andrew Razumov

**Comment by jung-thomas** [comment]
The comment about .build.js:
Actually by default .build.js is a hidden file.  This is the editor default and it is reflected in the screenshots as well. Notice the eye Icon.  This means that technical files like .build.js are not displayed since they are really only used internally by the project and can be ignored.
![image](https://user-images.githubusercontent.com/12159356/72476585-94052a80-37bb-11ea-9ac9-3fa29ba5456e.png)

Based upon your description, you are seeing the .build.js, you must have activated the show hidden files option. Notice when you select this option, you are able to see these technical files:
![image](https://user-images.githubusercontent.com/12159356/72476667-c6af2300-37bb-11ea-8f4a-5263736ca672.png)

I would strongly recommend that you not deviate from the default setting and keep these technical files hidden to avoid any confusion (such as the JSLint message from them).  The files are fine as-is and can be safely ignored.  Please don't delete these technical files (or anything that is hidden by default) as they are all critical to the operation of your project.

**Comment by jung-thomas** [comment]
Now to your second issue:
_But actually it does not matter because with/without files in the second tutorial - after choosing Build > Build CDS action the Console provided about fifteen lines of records with final verdict:

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^": Tags may not have any characters that encodeURIComponent encodes._

I can say there is no general problem with the tutorial. I've just done the tutorial from scratch on a HANA Express system and I was able to complete this Build -> Build CDS step without any error.  Nor do I believe this error is a common error or a simple misstep deviating from the tutorial.  

You are getting an error from the NPM (Node Package Manager) which fetches dependent files for the build process. Doing a search on the internet for NPM and this error points to the possibility that something is incorrect in your package.json file.  Have you perhaps manually edited one of the package.json files?  This tutorial has not asked you to change package.json and according to my testing the standard package.json files generated by the project wizard should work just fine (and did for me in my testing). There is no step in the tutorial at this point to edit the package.json files, nor should any edit be needed. Therefore I have to assume that either there is something incorrect in your package.json file beyond the scope of this tutorial or there is some deeper infrastructure issue within your HXE system when it comes to running NPM.  

As this isn't really an issue with the content of this tutorial itself, I believe we should close this issue.  As this is a more general troubleshooting issue, I'd suggest posting a question in the SAP Community  Questions section. 
https://answers.sap.com/tags/73554900100700000996
I'd suggesting posting a short description, the NPM error, and the contents of your package.json file. I'll keep a watch on the forum and I'll be happy to engage with you there for further troubleshooting of your situation.

**Comment by arazumov101** [comment]
Dear Mr. Jung,



First, I would like to take this opportunity to express my appreciation and
gratitude for the huge role you play in the SAP educational and training
through educational courses, articles, comments, etc.

Actually I'm a big fan of yours and a subscriber to your YouTube channel.


Regarding the problem, I would like to say, as a consumer, the
product/thing doesn't work.

I am now saying the obvious, but from the consumer's point of view, it does
not matter that someone from the team successfully completed their part in
creating the product.

The goal set by its creators was not achieved: the consumer did not get
what was promised and as a result, the value of the product for him/her is
zero.


But I still want to share my experience in solving the problem.

First, I strictly followed all the instructions in the tutorials.

The test system included two computers:

·         desktop PC - Quad-core Intel Core i7 processor, 32 MB RAM, 1TB
SSD, Windows 10 Pro

·         Dell laptop Inspiron 15, Core Intel Core i7 processor, 16 MB RAM,
500 GB SSD, Windows 10 Home

I was combining two different SAP HANA Express 2.0 SPS 04 software
downloaded on October 24, 2019 and recently on Jan 15, 2020 with VMWare
Player versions 12 and 15.



I met this problem only by using the template project “SAP Clod Platform
Business Application”.

The tutorials with choosing other two project templates: “MTA” & “SAP HANA
Database Application” were completed successfully.



Interestingly, the first attempt when activating the project template “SAP
Clod Platform Business Application” always failed with the message on both
computers:
[image: image.png]

[image: image.png]

The second attempt was always successful:
[image: image.png]

The building CDS on both computers ended with the already mentioned issue:
[image: image.png]

Just in case here is the node versions at runtime:
[image: image.png]

I will follow your advice to post a question in the SAP Community Questions
section.

Once again, I would like to thank you for the cooperation and the time you
spent.

Best regards,

Andrew Razumov
