### ISSUE TITLE
SAP Screen Personas script open other tcode for get data

### ISSUE THREAD

**Issue by pataselano** [SAPDocuments/Tutorials#4566]
Hi Conrad,

In tcode VL02N (change delivery order), I can add other sales order through sub menu 'Outbound Delivery-Deliver Sales Order'.

In that sub menu, help for Order field is not suitable because I can't find order item and copy order item to 'Only from item' field.

So, I must open another tcode, i. e.: VL10C for get sales order number and order item. After that, I copy-paste sales order number and order item manually into VL02N.

Is it possible for create script button in tcode VL02N for open/running tcode VL10C? After user select/check/tick sales order- order item and press back button, then script will back to tcode VL02N with data of selected sales order-order item in VL10C and pass that data into submenu 'Outbound Delivery-Deliver Sales Order'.

Thank you for your help.

Best regards,
Andy Pataselano

**Comment by MichaelCzcz** [comment]
Hello @cjbernal. This seems to be for you. Can you please have a look and change the assignee if necessary? Thank you.

**Comment by cjbernal** [comment]
Hi Michael,

This doesn’t exactly pertain to the tutorial, but I can answer the question. No worries. Thank you for forwarding it.

Kind regards,
Conrad

**Comment by cjbernal** [comment]
Hi Andy,

Thanks for checking in. Even though this is a little outside the tutorial, this is something we can definitely help you with. 

Short answer: Yes, you should be able to do exactly what you suggested. You would simply use the script recorder to record those actions and attach that script to the button in VL02N. 

If you have any difficulties with that, please let me know!

Kind regards,
Conrad

**Comment by pataselano** [comment]
Hi Conrad,

Thank you for answering my question even though my question is not related to your tutorial.

I just upgrade SAP Netweaver related to SAP Support backbone change. During upgrade process, I must freeze server from coding and configuration until 2 weeks. I also must down production server almost 20 hours.

On my server, the version of Personas is 3 SP02. If I upgrade to SP10, do I have to follow the same procedure as for updating Netweaver?

In Personas wiki, I only found blog about SAP Screen Personas 3.0 Installation Guide, but I can't found blog about how to upgrade SP for SAP Screen Personas.

Best regards,
Andy Pataselano

**Comment by cjbernal** [comment]
Hi Andy,

Technically speaking, upgrading Personas is independent of the NetWeaver upgrade. It doesn’t require downtime, per se; but people using flavors while the upgrade is running may experience problems or even dumps due to syntax errors. This is because the upgrade is only partially done. The problems will be certainly gone once the upgrade finished. For this reason, it is advisable to perform the upgrade together with the NW upgrade, in the same downtime period.

The SAP Screen Personas upgrade process is much faster than the NW upgrade, although going from SP02 to SP10 will take a little longer than the usual one SP upgrade, since the upgrade queue is larger and pretty much all objects will be touched.
When upgrading from SP03 or below, existing flavors must be upgraded manually, as described in note 2465796.

Kind regards,
Conrad

**Comment by pataselano** [comment]
Hi Conrad,

Thanks for the explanation. It's better if you add this problem to the SAP Screen Personas wiki.

Best regards,
Andy Pataselano
