### ISSUE TITLE
Install and Configure unixODBC

### ISSUE THREAD

**Issue by mojomojo1** [SAPDocuments/Tutorials#4570]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-dbfundamentals-odbc.html

If SAP HANA Express is installed using https://developers.sap.com/tutorials/hxe-gcp-getting-started-launcher-xsa.html (Google Cloud Platform), these instructions dont work, i.e. yast, registration, software search - all of it is not available including also numerious other packages, path variables etc. Could you please check?

**Comment by mojomojo1** [comment]
to be more specific, SUSE is registered but all repositories are empty and no extra software can be installed. I.e. this recommendation does not help: https://www.youtube.com/watch?v=e6SIsAFVPoY

**Comment by JCurrie27** [comment]
Hi mojomojo1: I've forwarded this issue to the development team to investigate these GCP restrictions you've noted above. I'll update this issue when their investigation is over.

**Comment by JCurrie27** [comment]
@mojomojo1: Since this issue is now being investigated by Development, I'm going to close this issue. Could you please add this issue as a question on the Community's Q&A site in case other Community members have input, or could benefit from this experience? When Development's investigation concludes, we'll use your Q&A question to log any back-and-forth with development.
To add a question:

1. Go to [https://answers.sap.com/index.htm](https://answers.sap.com/index.htm)l and click **Ask a Question**

1. In the **Select Primary Tag** field, search for "express" and select **SAP HANA, express edition**

1. Enter this issue as your question and click **Submit your Question**

Thanks

**Comment by mojomojo1** [comment]
Thank you, I have been informed meanwhile by our development team that
issue is known and resolution is pending next production release. This
should happen shortly I was said.
