### ISSUE TITLE
Design and Test Your First Integration Flow

### ISSUE THREAD

**Issue by MartijnHulshofMB** [SAPDocuments/Tutorials#4608]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html

Please specify the step you are referring to: 7

The integration flow is successfully deployed. However, the iFlow is not starting. I could not finish the training because of this.

**Comment by gauthamkrishna-sap** [comment]
Hello,

Thank you for the feedback, this issue might be intermittent due to some unusual high loads on the trial landscape. Request you to please try again. 

If the issue does not get resolved in the next 24hrs, kindly send an email to cpitrialfeedback@sap.com with your Global account ID, subdomain ID, and the error message (if you see one). Our team will look into this and provide a quick resolution.

Thanks for your understanding & patience. 

Best Regards, Gautham

**Comment by MartijnHulshofMB** [comment]
Hi Gautham, 

Have send the mail to the support team you mentioned. Any outlook as to when I can expect a response?

Regards,

Martijn

**Comment by gauthamkrishna-sap** [comment]
Hi Martjin,
I hope you have heard back from the team by now.
Best Regards,
Gautham

**Comment by MartijnHulshofMB** [comment]
Hi Gautham, I did hear from the team. However, the issue is still unresolved. Any strings you can pull? Regards, Martijn

**Comment by gauthamkrishna-sap** [comment]
Hi Martjin,
Apologies for that. I will check with the team and get back to you. 
Best Regards, Gautham

**Comment by MartijnHulshofMB** [comment]
Hi Gautham, 
I have an update. The endpoint does return data as per the tutorial where the message monitoring also indicates successful message processing. However, the status of the integration flow remains in status 'starting', and not 'started', as it should be. So seems like some bug with the CPI front end. Stopping/restarting the integration flow does not resolve the issue. 
Regards, Martijn

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Are there any updates on this issue?

**Comment by gauthamkrishna-sap** [comment]
@MichaelCzcz Unfortunately, not yet. I will update you if I hear anything.

**Comment by MartijnHulshofMB** [comment]
Hi Both, the issue seems resolved. Thanks for the follow up. Regards, Martijn
