### ISSUE TITLE
Installing SAP HANA, express edition with Docker

### ISSUE THREAD

**Issue by 4effo** [SAPDocuments/Tutorials#4628]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-install-using-docker.html
Step 8

Hello, when I try to start the docker image I'm getting the following error message:
ERROR: Unknown host '42682bbe4c9a'. The container must be started with one of these host names:
ERROR: 	91c16ffc78f6
I can start the container only by specifying '--hostname 91c16ffc78f6'

**Comment by JCurrie27** [comment]
Hi 4effo:  Could you please log this issue on the SAP Community Q&A site?  The community has much more visibility than this repository, and is actively monitored by HANA express engineers, as well as other Docker users.

1.  Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.htm) 

1. Describe your issue.

1. In the **Select Primary Tag** field, search for "express" and select "_Software Product > Technology Platform > SAP HANA > SAP HANA, express edition_".

(Closing this tutorial issue.)

**Comment by 4effo** [comment]
Sure I'll do so next time. I repeated the setup yesterday, and I could to get it working. Regrethably, not sure what I was doing wrong. 
I came on the github issue, because when one clicks on the "Provide Feedback" button, it leads you to here.
Many thanks!

**Comment by lcasavola** [comment]
hello 4effo, I saw this old post . I have the same problem in my environment, did you sorted out? Can you give me som hints?
Thank you,

**Comment by 4effo** [comment]
> hello 4effo, I saw this old post . I have the same problem in my environment, did you sorted out? Can you give me som hints?
> Thank you,

Hey lcasavola,
as far I remember, I didn't changed anything. Later I couldn't reproduce the issue again.
Wish you good luck!

**Comment by greg2git** [comment]
Sorry for not having a solution to your issue but since it has been closed anyway, I might just leave a general comment. 
I'm under the impression that with every new HANA Express release (now at 54) it is designed to run in a more and more limited environment. 

A case in point: my ubuntu release has not been tested, so I need to switch to another distro to continue with an installation. 
Also, what's up with this limitation: **This installation does not support Docker for Windows or Docker for Mac.**

In any case, good luck with getting your Express setup to work again.
