### ISSUE TITLE
Maintain a Communication Arrangement for Inbound Communication

### ISSUE THREAD

**Issue by D029515** [SAPDocuments/Tutorials#4697]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html

Please specify the step you are referring to: Step 12
What for do I need the service key? Can you please give any examples?

**Comment by mervey45** [comment]
Hi @D029515 ,

in general, you need to service for e.g. to connect to an SAP Cloud Platform ABAP Environment system as a user. 

But in this example, you can basically test your communication scenario, if it's working. If it is not working, you will get an error message. Otherwise, you will be able to create your service key. 

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
