### ISSUE TITLE
Import Tables and Large Datasets (XS Advanced)

### ISSUE THREAD

**Issue by Demonium** [SAPDocuments/Tutorials#4798]
Tutorial URL: https://developers.sap.com/tutorials/xsa-import-shine-data.html

At step 3:
To be available to build the db files I have to change all by providing the corresponding namespace for example the PO.hdbcds file I had this lines at the begining:

`namespace HANA_APP_CALC.db.data;
using HANA_APP_CALC.db.data::Core as EPM;
using HANA_APP_CALC.db.data::MD;`

You can find all change in the file attached

[db.zip](https://github.com/SAPDocuments/Tutorials/files/4364852/db.zip)

After all change I was able to build everythings.

So my question is it the good way ? The project is for an SAP HANA 2 SP04 

Best regards

**Comment by jung-thomas** [comment]
No you don't need to change the zip file.  You are trying to import into a DB module where you choose to use namspaces.  If you import it like the provided SHINE example, those DB modules do not use namespaces: https://github.com/SAP-samples/hana-shine-xsa/blob/master/core-db/src/.hdinamespace

This sample content is designed to be used without namespaces. If importing this into your own project during the db module creation just clear the namespace field. Or instead of adjusting all the content in the zip; simply navigate to the .hdinamespace file and clear the name field as in the source example I linked to above.
