### ISSUE TITLE
Deploy an App to SAP Cloud Platform Cloud Foundry Environment

### ISSUE THREAD

**Issue by vogeltho86** [SAPDocuments/Tutorials#4830]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-dev-02-deploy-app.html

Please specify the step you are referring to

The deployment doesn't work by uploading the zip file via browser. The start command is missing.

**Comment by qmacro** [comment]
Hi @vogeltho86 - This issue system is for issues with the tutorial content itself, rather than specific instances of trying things out. Please refer to the [SAP Community Q&A](https://answers.sap.com/index.html) where you can ask your question and engage with others there for an answer that will hopefully not only benefit you but also others that will find the question and answer afterwards. 

Perhaps there's a step you missed? I've just gone through this tutorial (and the previous one which was a prerequisite) and all is working fine. You didn't specify an answer to the question "Please specify the step you are referring to" so I can only guess it might be a general problem with the deployment. Good luck! 
![Screenshot 2020-03-30 at 09 38 11](https://user-images.githubusercontent.com/73068/77892483-94657b80-726a-11ea-9a5f-1b908ce7d2b3.png)
