### ISSUE TITLE
Create a Communication Arrangement for Outbound Communication

### ISSUE THREAD

**Issue by specialword** [SAPDocuments/Tutorials#4873]
Tutorial URL: https://developers.sap.com/tutorials/abap-env-create-comm-arrangement-api.html

Please specify the step you are referring to stpe6, substep1:
communication arrangement tile is NOT available.
here is my screen:
![image](https://user-images.githubusercontent.com/52459595/78375871-115a6300-7593-11ea-9217-5f66bc6ce523.png)

**Comment by nomssi** [comment]
I have the same problem. I am not sure how to apply the solution described in
https://github.com/SAPDocuments/Tutorials/issues/4449

**Comment by specialword** [comment]
pfcg to assign this role? 
but this scp does not support sap gui. there has to be a cloud way to assign the role. now I think this is a bug because my trial user id by default, is not assigned this role, Nomssi.
George

**Comment by julieplummer20** [comment]
Hi, Can each of you please provide more information?
1. Are you internal SAP or external (eg customer, partner, student)?
If you are internal, please answer by email instead, since I cannot , eg give out internal URLs here.

2. @nomssi : Could you please open a separate ticket? Sorry, but I think this thread could become rather entangled very quickly. Thanks

Whether internal or external, I need to know:
2. What exact entitlement do you have? eg if you are working on an S/4 Cloud entitlement, then you cannot complete this tutorial. 
You need: An ABAP service instance in SAP Cloud Cockpit
[Connect to the ABAP [Environment](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/7379dbd2e1684119bc1dd28874bbbb7b.html)

3. Have you successfully completed the 2nd prerequisite : A business role has been created containing the business catalog SAP_CORE_BC_COM, and is assigned to your user [How to Create a Business Role from Scratch
](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/f65e51a7203443efb58fe535c3d13e5f.html) ?

4. If so, when you say " I am not sure how to apply the solution described in
#4449" - how far did you get?

NOTE: PFCG is not available in ABAP Environment - the Business Catalogs concept replaces PFCG.

Best wishes,
Julie.

**Comment by specialword** [comment]
thanks Julie. I have external sap account as trial user .
P1942041822trial is my ID.

George

**Comment by julieplummer20** [comment]
Hi George,
Thanks. Can you answer the other questions as well, please?
Best wishes Julie.

**Comment by specialword** [comment]
Hi Julie,
#4449 is merged  to #4492. what shall I do to anser #4492? this seems to be an authorization issue, at least for trial user...
George

**Comment by nomssi** [comment]
Hello Julie,

I am an external consultant using the SAP Cloud Platform Trial + ABAP CloudPlatform Trial environments. I think this is the limitation as I cannot complete the 2nd prerequisite.

Best wishes,
Julie.

**Comment by nomssi** [comment]
Sorry for the wrong signature
Jacques

**Comment by julieplummer20** [comment]
Hi Jacques, hi George,
Yes, this mission will not work on a trial version. This is indicated by the key in the title. However, several users have failed to notice this, so I will suggest to the team that we rethink the UI. 
Sorry for the inconvenience. 
Could you please close this issue? 
Thanks and best wishes,
Julie.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by Juanvictormanuel1188** [comment]
The same issue

**Comment by julieplummer20** [comment]
Hi Juan,
Same questions:
1. Are you using SAP Cloud Platform, ABAP Environment Trial or Licensed version? This tutorial does not work on the trial version.
2. Are you internal SAP or external (eg customer, partner, student)?
If you are internal, please answer by email instead, since I cannot , eg give out internal URLs here.

Whether internal or external, I need to know:
3. What exact entitlement do you have? eg if you are working on an S/4 Cloud entitlement, then you cannot complete this tutorial.
You need: An ABAP service instance in SAP Cloud Cockpit
[Connect to the ABAP Environment

4. Have you successfully completed the 2nd prerequisite : A business role has been created containing the business catalog SAP_CORE_BC_COM, and is assigned to your user How to Create a Business Role from Scratch
?

5. If so, when you say "Same issue" - what exactly is your issue? Next time, please create a new issue, telling me exactly what you tried to do, and what happened. However, check first that you have a licensed version, not trial.
Best wishe Julie.

**Comment by Juanvictormanuel1188** [comment]
Hello Julie, 

I will close it as I'm using a trial account.

Thanks!
Victor

**Comment by julieplummer20** [comment]
Hi Victor, 
Thanks for letting me know. I'm sorry you can't do the mission.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
@MichaelCzcz  - this can now be closed. Thanks
