### ISSUE TITLE
Secure your application with XSUAA (Forecast App)

### ISSUE THREAD

**Issue by jameslim87** [SAPDocuments/Tutorials#4898]
Tutorial URL: https://developers.sap.com/tutorials/hxe-aa-forecast-17.html

I believe it should be updated with new HANA Express version.

1. when we run the html or js app, it will automatically generated service instances
   therefore, step 3 and 4 should be updated because it will not use the service instance what we created. 

2. after I added new role with the generated application into the role collection, it worked

-> This is new feature of Hana Express 2.0 SPS03.
     Therefore, we don't need to create service but need to assign auto generated application to Role collection manually. 

3. Unfortunately, when I select auto-arima and click the 'Execute' button, it will return error.
  I believe we may need new code to fetch csrf token but not sure about it. 

#ERROR#/Handler#####k8q7nm48####pgzz6foq7Lr5FIIxIrFBCyODkS-Z9few######k8q7nm48#PLAIN##POST request to /xsjs/pal/auto_arima.xsjs completed with status 403 - **The request does not contain a x-csrf-token**#
4/7/20 2:02:00.253 PM [RTR] OUT   10.0.0.14 - - to hxehost:51054 "POST /xsjs/pal/auto_arima.xsjs HTTP/1.1" 403 sent 19 in 10 by 01A-5325bc98-16a1-43db-87de-2fb48f4a1a4a

-> I fixed it and put it into my git.
https://github.com/jameslim87/forecast.git

   1. we need to add a empty file to fetch a csrf token.
   2. we need to add a js file for fetching token
   3. index.html should include #2 js file.

**Comment by jarjarbentley** [comment]
i will look into these changes this week. thank you

**Comment by thecodester** [comment]
@jarjarbentley Any updates?

**Comment by jung-thomas** [comment]
I've made slightly different changes than suggested.  Rather than let the Web IDE create the resources, I kept the flow with creating the service manually. However I changed the resource type to org.cloudfoundry.existing-service in the mta.yaml. This way the Web IDE will not try and create the resources at run any longer.  I think this makes the flow easier for educational purposes since you aren't bouncing back and forth in order to add the generated role to the role collection after the run (and potentially having to log out of our browser in order pickup the role collection change).

I also removed the requirement for csrf in the configuration of the xs-app.json later in the tutorial.
