### ISSUE TITLE
SAP HANA XS Advanced, Creating a Node.js Module

### ISSUE THREAD

**Issue by GijsPruijmboom** [SAPDocuments/Tutorials#4901]
Tutorial URL: https://developers.sap.com/tutorials/xsa-xsjs-xsodata.html

Please specify the step you are referring to:
Step 6: Execute the js module
After running the web module (as a web application) the application just shows "Internal Server Error".
I don't see differences between my code and the tutorial
[CF_XSA_app.zip](https://github.com/SAPDocuments/Tutorials/files/4450276/CF_XSA_app.zip)

![image](https://user-images.githubusercontent.com/17499798/78781167-11e26780-79a0-11ea-92f8-4a9878f6163c.png)

**Comment by jung-thomas** [comment]
What is the content of the run console back in the Web IDE?  That should have much more details about the situation. 

Also please note that this tutorial is for XSA and Web IDE for SAP HANA.  You are trying to execute it on Cloud Foundry and Web IDE Fullstack.

**Comment by GijsPruijmboom** [comment]
Hi Thomas,

I am aware that i am using the tutorial although i am not using XSA.
However this tutorial comes closest to the scenario i am trying to study.
The strange thing is that the console doesn't give any details when running
the web module.

If the tutorial is not suited for WebIde FullStack then sorry for
the inconvenience.

regards, Gijs Pruijmboom


Op wo 8 apr. 2020 om 14:46 schreef Thomas Jung <notifications@github.com>:

**Comment by jung-thomas** [comment]
The steps of the tutorial are not tested on and most likely will not match since you are not doing it in the environment that the tutorial was designed for.  Also I see in your screenshot that you that might well be using the trial.  The trial doesn't necessarily provide you with enough quota for running multiple services as required for this tutorial.  For the best experience with this tutorial, we would certainly recommend performing it on a HANA on premise/XSA system (like HANA Express). 

There doesn't seem to be evidence here that there is a specific issue with the content of this tutorial. For general issues developing; we would request you instead post your question to the SAP community Q&A where it will certainly have more visibility.
