### ISSUE TITLE
SAP HANA, express edition (Database + XS Advanced) - Getting started with the Marketplace on Microsoft Azure

### ISSUE THREAD

**Issue by sdebruyn** [SAPDocuments/Tutorials#4934]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ms-azure-marketplace-xsa.html

This fails after I complete the initial configuration the VM.
```
10709: Connection failed (RTE:[89006] System call 'connect' failed, rc=101:Network is unreachable {10.1.0.4:39015} (10.1.0.4:39015))
Fail to set root key backup password for HXE!
```

**Comment by sdebruyn** [comment]
Instead of using `su` to login as hxeadm, I logged in with it directly. The installation continued, but then it failed with the following error message:

```
Get authentication token from UAA...
{"reason":"{\"message\":{\"key\":\"HDB_CONN_TLS_HOST_NAME_MISMATCH\",\"defaultText\":\"TLS certificate host name mismatch\",\"arguments\":[\"reason\"],\"attributes\":{\"reason\":\"JDBCDriverException: SAP DBTech JDBC: Host name verification failed, found CN=hxehost.localdomain,OU=HXE,OU=HANA SSL, expected CN=localhost.\"}}}","canContinue":false,"stage":1}
ERROR: Failed to register "HXE" database to Cockpit.
```

**Comment by jung-thomas** [comment]
If you are having issues with the installation process itself, please post a question to the SAP Community Q&A. We can't help with installation troubleshooting here.  This area is only for issues with the tutorial itself.

**Comment by sdebruyn** [comment]
The point is that the tutorial is not correct. This is an image provided by SAP and a tutorial provided by SAP so they should work together without issues. The tutorial should be fixed so that you can use the image and go through all the steps without issues.

**Comment by jung-thomas** [comment]
I'm not getting where the tutorial is wrong here.  It seems like you are having installation problems (Network is unreachable).  You haven't really said a particular step in the tutorial that is incorrect. Looking at your errors it really seems to me that something went abnormal here and not that the tutorial doesn't match up.  At least its not clear to me which step you specifically feel is out of line with the normal installation process.

**Comment by alxdean** [comment]
I had exactly the same issue when installing SAP on the Azure Image provided. 
which is triggered by the command: sudo su - hxeadm, fails with the mentioned error message. The install, 
"Host name verification failed, found CN=hxehost.localdomain,OU=HXE,OU=HANA SSL, expected CN=localhost."

**Comment by alxdean** [comment]
I think the issue is based on how the hxeadm user logs in. when following the steps using ssh as the main connection mode, the initial sudo su goes to hxeadm@localhost
but it needs to be hxeadm@hxehost. 
after changing to root and back the switch to hxeadm seems to be right and my summary screen shows hxehost as hostname and not localhost no more. running an install this time seems to have worked and I get to see the success message. 

Effectively the express summary screen needs to read. anything else will error out. 

ANA, express edition
  Host name                            : hxehost
  Domain name                          : localdomain
  Master password                      : ********
