### ISSUE TITLE
Use OData Metadata to dynamically create the columns

### ISSUE THREAD

**Issue by voxron** [SAPDocuments/Tutorials#4941]
Tutorial URL: https://developers.sap.com/tutorials/xsa-sapui5-metadata.html

Hello Thomas,

I've done all steps, but web app is not working. Please errors of browser and log from WebIDE
I would like to mention, that previous exercies works fine.
![problem](https://user-images.githubusercontent.com/58906219/79422052-ca259680-7fc4-11ea-8b60-4b599c4c6ed6.png)
[log.txt](https://github.com/SAPDocuments/Tutorials/files/4485271/log.txt)

**Comment by jung-thomas** [comment]
The previous exercise is working correct?  Because this error is for unable to load the shell (which is needed by the previous exercise as well). In this step we are only changing a few lines in the controller and that is no where near where this error is coming from. The error is staying startup.js is missing (which comes from the /common folder and a much earlier tutorial in the chain). However it would also have been a part of the step before this that you said was successful.  I'm struggling to understand that.

**Comment by voxron** [comment]
What is the shell? 
Resource environment which in index.html?

**Comment by jung-thomas** [comment]
The Fiori shell (header bar) of the UI.
Yes this is loaded in the index.html.
It does reference startup.js, but would have in the previous tutorial step as well. We've not made any change in this step.
`<script type="text/javascript" src="../common/startup.js"></script>`
That's the part I'm trying to understand. I can of course put a reference back to the tutorial where startup.js is first created.  I know not everyone might be doing all the tutorials in order.

**Comment by jung-thomas** [comment]
I have updated the previous tutorial in this group: https://developers.sap.com/tutorials/xsa-sapui5-odata.html 

It now explicitly contains the details for the startup.js to avoid a complex dependency to have to go back through.  Hopefully that should make things easier in this case.

**Comment by voxron** [comment]
Now, it's ok, thank you!
