### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by weltspion** [SAPDocuments/Tutorials#4946]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

at Step 4 --> "Click Go to Application in the Process Integration tile."

Next screen is no logon screen, as I had be logged in to start the application from subscription tiles.

After "Go to Application" I directly get

<oauth>
<error_description>Insufficient scope for this resource</error_description>
<error>insufficient_scope</error>
</oauth>

**Comment by weltspion** [comment]
I let the subscriptions page open overnight. Now I clicked on the link and it worked (the link opened, logged on via cookie and the desired page appeared).

Probably you have to save the link to the clipboard and log off. Then logon again by using the link.

**Comment by Vikramkulkarni01** [comment]
Hi @weltspion, 
Thanks for reaching out to us. 

Could you please confirm that the issue has been fixed now? 

If the issue seems to be persisting still, could you please share with me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hear from you. 

Regards, 
Vikram Kulkarni

**Comment by weltspion** [comment]
Hi Vikram!

Eventually everything worked out. There might me an issue to solve by logging out and in. I my case I was automatically logged in by cookie and went into an error. But however, this might also have happened due to an unfinished deployment. I do not know exactly, just guessing.

It happened, when I initially wanted to start the new application from the tile within "Step 4".

Do unfortunately do not have screenshots anymore.

Best
Torsten

Global Account: 09db0864trial
Subdomain: 09db0864trial 
ID: 75633932-387e-47f8-834d-0e58b128f0f5

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
