### ISSUE TITLE
Create a Basic Flow with a SOAP Endpoint

### ISSUE THREAD

**Issue by Skantheri** [SAPDocuments/Tutorials#4947]
Tutorial URL: https://developers.sap.com/tutorials/cp-integration-create-basic-flow.html

Step 9.
It is not accepting the right Answer which is Design. It is not Discover as mentioned in the course. Please correct it. 

Step 8.
I get below error when trying to POST.

Message processing failed.
Processing Time: 1 sec 2 ms
Error Details
javax.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target, cause: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by lalit74u** [comment]
@MichaelCzcz @MeghnaShishodiya @divyam3 can you please recommend / guide
This is great tutorial searies, but we are stuck at tutorial 1 itself.

Thanks

**Comment by thecodester** [comment]
@gauthamkrishna-sap Please update.

**Comment by jonkerpeter** [comment]
I had the same problem/error. I found on the internet that the Google certificate has to be uploaded in the key store. But after I have done that I am getting another error:
"javax.mail.AuthenticationFailedException: No authentication mechanisms supported by both server and client"
I have tried 2 way authentication in google with a special password for the CPI trial account, but it didn't change the error message.
I like these tutorials, but I think they should be tested better so users don't come across these errors. Also I see that this issue didn't receive no updatee from SAP since a long time.  Please assist I am sure that Skantheri and I are not the onbly ones with this issue.

**Comment by mrudula1412** [comment]
> @MichaelCzcz @MeghnaShishodiya @divyam3 can you please recommend / guide
> This is great tutorial searies, but we are stuck at tutorial 1 itself.
> 
> Thanks

Hi,

Please check comments of jonkerpeter in below issue.
I have followed the steps which he has mentioned in his comments and I received correct response.

https://github.com/SAPDocuments/Tutorials/issues/4782

**Comment by MichaelCzcz** [comment]
@mrudula1412 Sorry, but I am neither the author nor the owner of this tutorial.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Any updates?

**Comment by gauthamkrishna-sap** [comment]
Dear All,
Please use this tutorial series as a workaround: https://developers.sap.com/mission.cp-starter-integration-cpi.html
This is designed with the new trial offering in mind. In the meantime, we will update this series with the latest screenshots post TechEd 2020. 
Thanks & Best Regards, Gautham

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
