### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by bvarwig** [SAPDocuments/Tutorials#5040]
Tutorial URL: https://developers.sap.com/tutorials/cp-ui5-webide-new-app.html

Please specify the step you are referring to

Hello,
if you are new to SAP CF and would like to know how to develop an html5 applicaiton you might find this tutorial. 

In Step1 you are using Webide to create the project stub. How should the user know, that your first screenshot already shows the Webide? Please guide the student so that he is able to fellow your tutorial. 

Thanks and
Regards Britta

**Comment by bvarwig** [comment]
.. and i think WebIde is the old way. I expect that its now possible to use  "SAP Business Application Studio"?

**Comment by IObert** [comment]
Hi,

thanks for your feedback. The tutorial you references is actually part of [a larger tutorial group](https://developers.sap.com/group.cp-ui5-first-app.html). And the first tutorial of this enclosing group explains [how to access the Web IDE](https://developers.sap.com/tutorials/sapui5-webide-open-webide.html).

Having said that, we are aware that many people who find this tutorial via Google might not be aware of what tutorial groups are and how to make sure if they are at the right starting point. @thecodester Do we already have a concept to indicate this to the users? I know we noticed this a couple of times so far.


Regarding the "WebIDE vs App Studio" question: You are right that the App Studio will replace the Web IDE mid-term. As of today there are still a couple of UI5-dev-related features in development which is why we still recommend the WebIDE tutorial.

I hope this explanation helped :)

**Comment by IObert** [comment]
Please reopen the issue if you have additional questions
