### ISSUE TITLE
Create Rule Services and Rulesets

### ISSUE THREAD

**Issue by dsilvahansen** [SAPDocuments/Tutorials#5049]
Tutorial URL: https://developers.sap.com/tutorials/cp-cf-businessrules07-ruleservice-ruleset.html

Please specify the step you are referring to

Step 2: has new fields: `Policy` and `Priority` that the tutorial doesn't speak of. 
![image](https://user-images.githubusercontent.com/31363815/80598953-c0317800-8a47-11ea-9ed8-18733cdf4e4e.png)

Also there is no "Advanced mode" selection for new rules creation.
in Step 1 at https://developers.sap.com/tutorials/cp-cf-businessrules06-dt-textrule.html

**Comment by VandanaVasudevan** [comment]
Hi,

Thanks for pointing this out. In the first case, you can leave Policy and Priority fields as is since we only brush up on the basics of business rules here. I will mention that explicitly in the tutorial. If you want to know more about the service, you can refer to the help documentation mentioned at the beginning of the first tutorial in the mission.

The second scenario is a new UI change which I'll be updating soon.

Thanks and Regards,
Vandana

**Comment by thecodester** [comment]
@VandanaVasudevan Has the tutorial been updated?

**Comment by VandanaVasudevan** [comment]
Yes it is updated.

**Comment by thecodester** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
