### ISSUE TITLE
Display Data from the Northwind Service

### ISSUE THREAD

**Issue by MartinStenzig** [SAPDocuments/Tutorials#5094]
Tutorial URL: https://developers.sap.com/tutorials/sapui5-fiori-cf-display-data.html

*small stuff*

Step 7 part 1: There is a trailing comma in the javascript code to copy that should not be there... and there are also some spaces between the comma after onInit and the begin _onRouteMatched that VS Code is complaining about.

**Comment by IObert** [comment]
Hi,

you are right that the comma is not really needed here. I added it because the user will add more methods to this object in the next tutorial and then it is easier (especially for JavaScript-beginners) when they can simply paste the next method under it. Otherwise, I would have to ask them to add the comma then, which can lead to confusion.

But again, you are absolutely right, this is not needed. Feel free to remove it.

PS: I'm not sure about the issue with the additional spaces. My VS Code doesn't complain here.

**Comment by IObert** [comment]
I'll close this one due to inactivity, please reopen if needed :)
