### ISSUE TITLE
Create Data Model and Lock Object in SAP Cloud Platform ABAP Environment

### ISSUE THREAD

**Issue by veeraa83** [SAPDocuments/Tutorials#5131]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-lock-object.html

Issue in Step#5. I get the following error,when I try to create a new Data Definition with the code given in step#5.
"use of entity i_businessuser is not permitted".
![e](https://user-images.githubusercontent.com/8470543/81628448-55584780-941e-11ea-9c60-7382e180bd7d.JPG)
use of Entity I_BUSINESSUSER is not permitted"

**Comment by mervey45** [comment]
Hi @veeraa83 ,

which system are you using? Please also ensure, that you have activated everything so far. If something is not activated, then sometimes issues like this can appear. Otherwise please contact me again.

Best regards, 
Merve

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by OscarPuin** [comment]
I am having the same error , but I dont know why, i activated everything 

![image](https://user-images.githubusercontent.com/12472633/87205204-82b15c80-c2cc-11ea-81a2-41004fc5b0d1.png)


Help me please 

Best regards

**Comment by mervey45** [comment]
Hi @OscarPuin ,

which system are you using?

Please make sure, you are using the latest ADT update: https://tools.hana.ondemand.com/#abap

**Procedure:**
To install the front-end component of ADT, proceed as follows:

Get an installation of Eclipse 2020-06 (e.g. Eclipse IDE for Java Developers)
In Eclipse, choose in the menu bar Help > Install New Software...
Enter the URL https://tools.hana.ondemand.com/latest
Press Enter to display the available features.
Select ABAP Development Tools and choose Next.
On the next wizard page, you get an overview of the features to be installed. Choose Next.
Confirm the license agreements and choose Finish to start the installation.

Otherwise, feel free to contact me again.

Best regards, 
Merve
