### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by shivakumar-p-sap** [SAPDocuments/Tutorials#5147]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

In Step 4 on 4th instruction screenshot showing  Provision button, but in application there is no  Provision button instead there is "Activate" button.

**Comment by Vikramkulkarni01** [comment]
Hi Shivakumar, 

Thank you for reaching out to us. 

I understand your concern, could you please share with me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by gouravkumarjena** [comment]
Hello Team,

I am facing issues with my Tenant provisioning. The same is getting stuck after completion of 18 percent. Earlier I thought maybe I will try with a new account. But I faced the same problem.
Here are my trial account details:

Global Account: ba30d83atrial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Global Account: 931506cctrial
Subaccount: trial
Error Message:
Tenant provisioning is in progress and it can take 20 minutes. Please wait for the provisioning to complete before creating service broker instances.

Please do the needful so that I can set up the tenant provisioning successfully.

Regards
Gourav Jena

**Comment by Vikramkulkarni01** [comment]
Hi Gourav, 

Thank you for sharing the requested details. 

I involved the internal team to check and provide the necessary fix for the concern you raised. I am working closely with them and keep you posted with an update. 

We truly appreciate your support and patience. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi @gouravkumarjena, 

Could you please share the complete application URL?

Click in the Process Integration--> Click Go to Application --> and share that URL with us. 

We truly appreciate your support and looking forward to hearing from you.

Regards, 
Vikram Kulkarni

**Comment by gouravkumarjena** [comment]
Hi @Vikramkulkarni01 

Please find the below URL: (for Global Account: ba30d83atrial)
https://ba30d83atrial.it-cpitrial01-app-prov-sap.cfapps.eu10.hana.ondemand.com/manageTenant/cpi-tenant/v1.0/goToApplication

Kindly let me know if you need any further information. 

Regards
Gourav

**Comment by Vikramkulkarni01** [comment]
Hi @gouravkumarjena , 

Thank you for sharing the information with me. 

I am working closely with them and keep you posted with an update.

We truly appreciate your support and patience.

Regards,
Vikram Kulkarni

**Comment by gouravkumarjena** [comment]
Hi @Vikramkulkarni01 

Could you please let me know the status of the issues which I raised? 
Did you get any kind of solution for the same?
Regards
Gourav

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
