### ISSUE TITLE
SAP HANA Plugin for Microsoft Visual Studio - Working with Tables

### ISSUE THREAD

**Issue by specialword** [SAPDocuments/Tutorials#5176]
Tutorial URL: https://developers.sap.com/tutorials/hxe-ua-visual-studio-tables.html

Please specify the step you are referring to,
Step 1: Open HANA SQL Script Editor
right click on connection to seleect "New HANA Script", I got error:
"The type initializer for 'Sap.Data.Hana.HanaConnection' threw an exception".

George

**Comment by specialword** [comment]
![image](https://user-images.githubusercontent.com/52459595/82087168-2c9daf80-96b5-11ea-8127-2b2930226e10.png)

**Comment by JCurrie27** [comment]
Hi @specialword: It looks like you've encountered a software bug, or an installer package bug, rather than a problem with the tutorial text. Could you please log this issue on the HANA Express community **Q&A** page to take advantage of the community support model? The Q&A page receives much more traffic, and is monitored by Support experts. Other community members may be able to provide answers immediately. 

To log your questions on the **Q&A** page:

1. Go to [https://answers.sap.com/questions/ask.html](https://answers.sap.com/questions/ask.html)
2. Add a **Title**. Enter your GitHub question in the **Fill in the details...** form.
3. In **Select Primary Tag**, search for "express". Select **SAP HANA, express edition**.
4. Click **Submit your Question**.

**Comment by JCurrie27** [comment]
I'm going to close this documentation issue, but once you log it on the **Q&A** page it will remain open there. It will stay open on the **Q&A** page until the Community Support model resolves your issue.
