### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5195]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Region : US

Step 2
The [link](https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/07f62efe97544149bf637f9b67c2e838.html) given under the **Important**   doesn't show additional information on roles in SAP Cloud Platform Integration as mentioned in tutorial.

Actual result after clicking on link:
![image](https://user-images.githubusercontent.com/50734023/82414978-79a6ca80-9a95-11ea-90f2-fbdd5a80296d.png)

Regards,
Nidhi

**Comment by Vikramkulkarni01** [comment]
Hi Nidhi, 

Thank you for contacting us. 

I understand your concern. The link is not opening due to some technical glitch. 

I have shared with you the [link ](https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/c91046c2c8644462a9cabd7a79ecbb79.html) for ease of your reference. 

Please check it and you can close this ticket from your end. 

Regards, 
Vikram Kulkarni.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
