### ISSUE TITLE
Download SAP Mobile Cards to Your Device

### ISSUE THREAD

**Issue by nsreerambhatla** [SAPDocuments/Tutorials#5224]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-sales-tracker-download-card.html

Please specify the step you are referring to

Hi Team,

I use Iphone(ios) , installed sap mobile cards app it is not asking for QR code . when I tried to give my email id it i snot working. 

Some or the other way I am not able to complete any tutorial completely under API management.

Thanks
Nag

**Comment by shilpavij** [comment]
Dear Colleague,

Really sorry to hear this, if you are unable to complete any of the tutorials tagged with APIM, I fear the second last tutorial of this mission would work.  
 Anyways if you have completed the above 4 tutorials and QR code is not working, I would suggest we also have a simulator to check in the UI, you can try that option too.
Also, in addition to this, it will be really helpful to know exactly where you are facing the problem instead of a generic statement so that teams here can debug. 

I too have an iPhone and for me, QR code works perfectly fine.

Regards
Shilpa

**Comment by nsreerambhatla** [comment]
Hi Shilpa,

Good morning!!

For this one it is the create selected cards issue , none of them is creating QR code.

![image](https://user-images.githubusercontent.com/65887355/83318333-7bb91800-a251-11ea-9bb4-1c1343ab5ba9.png)

And for other tutorials , Web IDE is the issue . 

I have checked the destinations in CP for API management and API developer portal. They are OK and returning 200 Ok.

Below screenshot is for your reference.

![image](https://user-images.githubusercontent.com/65887355/83318428-5aa4f700-a252-11ea-9469-e2fb86d44e27.png)

Thanks
Nag

**Comment by thecodester** [comment]
@shilpavij Can you check this?

**Comment by shilpavij** [comment]
Dear,

Its a bug and we are fixing this.

Regards
Shilpa

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
