### ISSUE TITLE
Set Up Your SAP Cloud Platform Integration Tenant

### ISSUE THREAD

**Issue by gcsfred2** [SAPDocuments/Tutorials#5256]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-integration-cpi-onboard-subscribe.html

Please specify the step you are referring to

Step 4: Provision SAP Cloud Platform Integration tenant
Upon clicking on "Go to Application", the following error happens:

![Screenshot at Jun 03 15-31-56](https://user-images.githubusercontent.com/39340197/83680796-6fb1bb00-a5af-11ea-98d7-28aa4d951c2a.png)

**Comment by Vikramkulkarni01** [comment]
Hi @gcsfred2, 

Thanks for reaching out to us. 

I understand your concern, could you please share with me the below details to investigate the issue further?

1. Global Account name & ID
2. Subaccount name and ID 
3. Error message or the screenshots. 

We truly appreciate your support and looking forward to hearing from you. 

Regards, 
Vikram Kulkarni

**Comment by Vikramkulkarni01** [comment]
Hi Gustavo, 

I truly understand your concern. As this is a technical glitch and recently reported from you only and we are unable to categorize this as a generic error. It seems like a tenant-specific. 

However, I will forward your concern to the respective team to find out the root cause. 

Regards, 
Vikram Kulkarni

**Comment by gcsfred2** [comment]
Thank you, Vikram.

Best regards,

Gustavo
