### ISSUE TITLE
Test Hyperledger Fabric Chaincode API - Error 401 -  Error: Unauthorized

### ISSUE THREAD

**Issue by Yeiteotl** [SAPDocuments/Tutorials#5272]
Tutorial URL: https://developers.sap.com/tutorials/blockchain-test-chaincode.html

I executed the step 5 to test the chain code, Iam received the error code 401, unauthorized. I try to find some options about configure security or something but I dont find anything to solve this. Do anyone knows why or how to have authorization?
![image](https://user-images.githubusercontent.com/66337770/83951502-62870d00-a7f7-11ea-9e42-10a6e0a8e58c.png)

**Comment by greg2git** [comment]
i haven't recreated a channel in my newly created space, but are you connected to a cloud foundry host for your API environment?

**Comment by Yeiteotl** [comment]
Hello @greg2git , my account of SAP Cloud Platform is the frial account. Im not using a API connection yet, I just tried to test the chain code example "hello world", when I executed all the steps of the tutorial instead to create a block I received the mentioned error.

**Comment by greg2git** [comment]
Hi Yeiteotl,
i don't want to get too much ahead of myself but would rather let Chris address the issue. even though i'm on a 3rd trial now, i think, each time it's a little bit different. since the SCP (it's on a so-called feature set B) is changing as it's becoming all of cloud foundry now and no more neo, there may be some changes, which are not made public or are buried deep inside help pages. 

1. is your "hello world" chaincode installed and instantiated? 
2. has it ever worked for you? 
3. have you tried the api hub to test it? 

i'm not planning to go back and deploy the 'hello world' onto blockchain but since it's so basic if it doesn't work there may be something else going on, so again let's hear from SAP first and then see what's tripping the tutorial for you.
Cheers, gm

**Comment by chrisfries** [comment]
Hi @Yeiteotl 
this 401 unauthorized error is related to an issue that caused the authentication to the Hyperledger Fabric service to fail on new trial accounts.
Please try again, the fix was rolled out today :)

**Comment by greg2git** [comment]
not exactly sure, but it seems that authorizations and authentications are tied to spaces and API end points, so while i can have 2 channels (and 2 actual blockchains) for API development i can only use one channel at a time. 
in any event, thank for removing the authentication issue with the new trial account.

**Comment by Yeiteotl** [comment]
Hello @chrisfries 
Today I be able to do the chaincode test with succesfull response. Thankyou again.
@greg2git thank you too for some option to solve it.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
