### ISSUE TITLE
Set Up SAP Fiori Tools in Visual Studio Code

### ISSUE THREAD

**Issue by venkat-aluka** [SAPDocuments/Tutorials#5362]
Tutorial URL: https://developers.sap.com/tutorials/fiori-tools-vscode-setup.html

Hello Conrad  Bernal,
I was able to install the extension SAP Fiori Tools-Extension pack in  Visual Studio code.
I did try to implement the  steps mentioned in the second tutorial (Set Up and Generate a New SAP Fiori App Project) and I am facing an issue in implementing the Step 1: Launch Application Generator. I have entered the keyword application generator in command pallete but i get the below error( mentioned in the quotes) . When i have installed the extension ( SAP Fiori Tools-Extension pack) then the Application Modeler is also installed . I am not sure why i got below error . 

" In order to use the Application Generator, please install the Application Wizard extension from the VSCode marketplace.
Source:SAP Fiori Tools-Application Modeler(Extension)." 

Can you please help me in fixing this error. I appreciate all your help. 
Thanks in advance.
Venkat Aluka

**Comment by cjbernal** [comment]
Hi Venkat,

Sorry for the delay. Do you also have Node.js installed? This is also a requirement for using SAP Fiori tools with Visual Studio Code. The tutorial has since been updated to mention this. You can download it here: https://nodejs.org/en/download/\

If you have issues after installing Node.js, please let us know.

Kind regards,
Conrad (SAP UX Engineering)

**Comment by venkat-aluka** [comment]
Hello Conrad,
Thank you for the reply, I have installed the Node.js (version v12.18.1 ) on my system and I still get the same message(" In order to use the Application Generator, please install the Application Wizard extension. from the VSCode marketplace.).I went ahead and did install the extension(Application wizard-Provides rich user experience for Yeoman generators.) but still no luck this time 
I see a different message on the command pallete.
![App_Gen](https://user-images.githubusercontent.com/65474402/85802229-8791e000-b712-11ea-8e5b-e883bd773cc0.JPG)
Thanks
Venkat

**Comment by theStiggySpd** [comment]
Hi @venkat-aluka 
This may be due to missing authorisations when installing packages globally. In order to resolve please ensure you have node installed and do the following:
**MacOS**: open a terminal and execute `sudo npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org`
**Windows**: Open a command prompt or PowerShell with “Run as Administrator”and execute `npm i -g @sap/generator-fiori-elements --@sap:registry=https://registry.npmjs.org`
Once this completes successfully, reload VSCode and restart the generator from the Command Palette. The generator should now appear.

**Comment by Vivek-Vishal** [comment]
Dear Experts,

I'm facing a similar issue when using VS Code on Windows. I tried to install the above command in windows for npm-generator fiori but it still does not work.. I get the error cb() never called , there is an error with npm install. I've uninstalled, cleaned node/npm twice and tried again the same procedure but it still does not work.. Please help..

Thanks, Vivek

![image](https://user-images.githubusercontent.com/40817264/86561825-258d7200-bf7f-11ea-8785-94db03e7432a.png)
![image](https://user-images.githubusercontent.com/40817264/86561857-3342f780-bf7f-11ea-9369-d8d61e60df9f.png)

**Comment by reginasheynblat** [comment]
Hi Vivek-Vishal, 

Please see the FAQ,: https://help.sap.com/viewer/42532dbd1ebb434a80506113970f96e9/Latest/en-US
I believe its an authorization issue. 

Thanks
Regina

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
