### ISSUE TITLE
Get Started with the SAP API Business Hub

### ISSUE THREAD

**Issue by C5285186** [SAPDocuments/Tutorials#5488]
Tutorial URL: https://developers.sap.com/tutorials/hcp-abh-getting-started.html

Please specify the step you are referring to 
Step 3 There is no search box on the page after choosing APIs and View more.
Step 4 Execute didn't work. Probably because I have no API key: "Failed to resolve API Key variable request.header.apikey".

**Comment by IObert** [comment]
Thanks for your feedback. You are absolutely right, the UI has changed and the search box is not available in the "nested subpages" any longer (only on the main page).
We updated the tutorial to reflect that change.

In step 4, you probably see this error because you are not logged in. Can you please double-check?

Btw: It is possible that you are seeing an "Invalid company ID" error instead, this is something we are working on currently.

**Comment by C5285186** [comment]
Hi Marius,

I was definitely logged in. I quoted the fault message: it seems I didn’t have an API key.

Best,
Anja

**Comment by C5285186** [comment]
Hi Marius,

I was definitely logged in. I quoted the fault message: it seems I didn’t have an API key.

Best,
Anja

**Comment by IObert** [comment]
This is strange, normally the key should be attached automatically when you are logged in. Can you please try again?

**Comment by C5285186** [comment]
Tried again. I am logged in. If I press the Show API Key button I get the error message "We cannot display the key. Please try again later." Maybe I don't have the right authorizations as I'm an external UA developer.

**Comment by IObert** [comment]
Afaik everyone should have access to a key. Please send an email via the "contact us" template in the footer of the page to report the issue.
Thanks!

**Comment by C5285186** [comment]
Done

**Comment by IObert** [comment]
Thanks, I'll close the issue then.
