### ISSUE TITLE
Run the Employee Onboarding Sample Scenario

### ISSUE THREAD

**Issue by marianfoo** [SAPDocuments/Tutorials#5512]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-5-run.html#b43157df-372d-4270-808a-7f0c513fe7da
Step 1.4.

I could not start the workflow system from the booster, but had no problems until here.
Now I want to import the JSON here, but I get an error message.
I have actually given myself all roles that are related to workflow.
I have created a role collection "SAP_ALL" and added almost every role there.
I have also already logged out and logged in.
What else can I do here?

![image](https://user-images.githubusercontent.com/13335743/87658077-fbe10180-c75b-11ea-9155-2933983eec22.png)
![image](https://user-images.githubusercontent.com/13335743/87658093-fedbf200-c75b-11ea-8383-03fc67fe0d07.png)

**Comment by ArchanaShukla** [comment]
Hello, I do not see any process visibility roles assigned here. Did you run the booster as mentioned in the setup guide? Can you run it again if it failed for any reason. I do not think the screenshot you shared are from the trial account because we do not have workflow management in the trial yet :)

**Comment by marianfoo** [comment]
Hi @ArchanaShukla  you're right. It's not a standard trial account. The booster was probably not available because of this. 
So I had to do some stuff manually.
I added the ProcessVisibility roles and now it works.
Thanks for the help :)
