### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by harshitagrawal** [SAPDocuments/Tutorials#5546]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Hi Thomas,

In General - The tutorial is extremely helpful but needs an update now with regards to screenshots used.
In Step 6, when I try to create the artifacts - on doing the build there are multiple errors in console with respect to Python environment not being set and in the step by step tutorial it has not been mentioned to setup any Python environment.
In addition, when i open the HDI Container - System throws the below error - 
"Parameter resolution failed: Could not find specified hdi service: my-hdi".

PS: I am completely new to SAP HANA and to the SAP HANA Cloud Platform, so probably other people who are at my stage may also face similar issue.

Best Regards,
Harshit

**Comment by jung-thomas** [comment]
There is no Python environment setup needed. Nor do I believe there are updates to the tutorial screenshots need. I just tested this tutorial last week on the trial environment and revised. There was no python setup needed nor any errors that you mentioned. 

If the build wasn't successful, then you wouldn't be able to open the container. So we really need to know more about the build errors which you encountered.  What was the error.  What environment are you performing this tutorial in.  Some details would be helpful in diagnosing what is happening.

**Comment by harshitagrawal** [comment]
Hi Thomas,

Thank you for your response, please allow me to explain the issue faced in detail - 
Initially, I skipped the first 3 steps and directly went on configuring the [SAP WebIDE Full Stack](https://webidecp-fiori.dispatcher.int.sap.eu2.hana.ondemand.com/)  for HANA Development where I was unable to configure the API endpoint. I realized that CF space has not been assigned to me but I did not know how to assign the same.
<img width="1279" alt="CloudFoundry_Issue" src="https://user-images.githubusercontent.com/5724750/88094327-03b40200-cbb1-11ea-943f-654106948759.PNG">
Then I followed the steps and created a 'dev' space on the SAP HANA Trial account. I completed the configuration of the WEB IDE provided via the trial account. After cloning the project, started the build which had several errors in console regarding 'Python not found', although the build got completed (don't know if it was successful) as per the log. 
Please find the log from the console in the below file - 
[Console.txt](https://github.com/SAPDocuments/Tutorials/files/4955610/Console.txt)
Assuming build went successful, i went on to open the HDI and faced the below error - 
<img width="1251" alt="HDI_Container" src="https://user-images.githubusercontent.com/5724750/88096089-c00ec780-cbb3-11ea-89ba-29951ba94554.PNG">
I am not sure why there is an issue during the build, but it will be really helpful to know your thoughts on the same.

Thanks and Best Regards,
Harshit




`

**Comment by jung-thomas** [comment]
Well first of all I can see from the URL that you are using an SAP internal Canary version of the Web IDE. This tutorial is written for the public version of SAP Cloud Platform and specifically the public trial.  Canary is in a separate network setup since its SAP internal and isn't going to be able to access the trial landscape. Please don't cross over between SAP internal and public landscapes. That isn't going to work.

Second problem: you aren't building at the right level.  In the instructions it says:
Expand the cloned folder and right-click on the **db** folder, and choose Build.
I can tell from the log that you uploaded that you chose Build from the project level and not the db level. Therefore it was only building the MTAR archive.  

The python errors themselves, I'm not entirely sure on because you already have two mistakes before this.  I strongly suspect that it might be related to the fact that you are trying to do this exercise on Canary internal landscape where version numbers and new experimental features are being tested.

Finally there is nothing in the database explorer because you've not actually built the db folder.  You only built the project into an MTAR but never build the db folder so no content has been deployed into the database yet. 

But in summary. Please don't use Canary or other SAP internal landscape and certainly don't mix trial and SAP internal.  I'd recommend that you perform this complete tutorial on the public trial landscape. When you get to the step where you build, be sure to right mouse click on the **db** folder.

**Comment by jung-thomas** [comment]
I can confirm that you only receive those Python build messages if you incorrect perform the build at the project level. If you build at the db folder level as the tutorial describes you will not receive any Python messages.

**Comment by harshitagrawal** [comment]
Hi Thomas,

Thank you for your support. The error message did not appear on performing build at the right project level, although the build still continued to fail.  In my previous failed builds, the service instance had been created incorrectly so I changed the service name in 'mta.yaml' file and it works correctly now.

Best Regards,
Harshit
