### ISSUE TITLE
Set Up SAP Data Hub, Developer Edition

### ISSUE THREAD

**Issue by cljambo** [SAPDocuments/Tutorials#5620]
Tutorial URL: https://developers.sap.com/tutorials/datahub-docker-v2-setup.html

Please specify the step you are referring to

Hi everyone,

this week I have successfully followed above tutorial installing SAP Data Hub Dev Ed on Windows 10 using Docker for Windows. Everything works fine so far.

Upon trying to build an image from a docker file in the repository, e.g., com/sap/ml/rserve333, I get the following error message:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

How to fix this error? Building images from docker files from Windows PowerShell instead is working fine. Is it related to me using Docker for Windows but Data Hub thinking I am running it in a UNIX environment?

Regards

**Comment by dimvor** [comment]
Could you rerun the **docker run** command and add the following additional parameters:

**-v /usr/local/bin/docker:/usr/bin/docker**

This should load the docker daemon into the container when running on Windows.

**Comment by cljambo** [comment]
Thanks dimvor for the quick reply!

I have deleted my datahub container (docker rm datahub) and rerun it with:
docker run **-v /usr/local/bin/docker:/usr/bin/docker** -ti --env VORA_USERNAME=vora --env VORA_PASSWORD=SomeNicePassword19920706 --publish 8090:8090 --publish 9225:9225 --publish 30115:30115 --name datahub --hostname datahub --network dev-net datahub run --agree-to-sap-license

FYI, the following file contains the corresponding output of the docker run command:
[docker_run_DataHubDevEd.txt](https://github.com/SAPDocuments/Tutorials/files/5033867/docker_run_DataHubDevEd.txt)

However, I still get the same error messaga that the docker daemon cannot be found when trying to build a docker file from within Data Hub.

Do you have any other ideas or need further info?

BTW, I read in a SAP blog comment that this feature isn't offically supported in teh Developer Edition anyway:
https://blogs.sap.com/2017/12/06/sap-data-hub-developer-edition/#comment-457050

Regards!

**Comment by dimvor** [comment]
Just for some background, whenever you try to build a dockerfile inside the modeler it tries to connect to the docker runtime inside the container -- which as you see from the error message cannot be found. My suggestion from the previous reply was taken from here, where you mount the docker runtime from your actual windows machine into the container: https://stackoverflow.com/questions/36765138/bind-to-docker-socket-on-windows

Yes, technically this isn't supported because what you're essentially doing is running docker inside a docker container. It becomes particularly complex because you're running Docker on a Windows environment that simulates a linux environment. 

In any case, the SAP Data Hub Dev Edition is from 2018 and is very outdated from what is available today. At the moment your best bet is to use the T[rial Edition for SAP Data Intelligence](https://developers.sap.com/mission.dataintelligence-trial.html) (the successor to Data Hub). However, you will be happy to hear that we're also working on a developer edition for Data Intelligence.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
