### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by hearmonster** [SAPDocuments/Tutorials#5627]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to Step #8 ("Consume Services")
I created the Destination as instructed. 
Checking the connectivity of the Destination resulted in a 307 Redirect
![image](https://user-images.githubusercontent.com/8210748/89461893-396cf500-d732-11ea-9ba8-89856c5a8db8.png)
But Step #8 ("Consume Services") refuses to accept that my ES5 credentials are valid!  (even though I can sucessfully authenticate into the ES5 server.). I'm using a password manager to store my ES5 creds - so it's not a case of fat fingering the password
![image](https://user-images.githubusercontent.com/8210748/89461671-e5621080-d731-11ea-8058-c2cc6bce1d58.png)

**Comment by hearmonster** [comment]
Proof that my ES5 creds are valid:
![image](https://user-images.githubusercontent.com/8210748/89462394-f0697080-d732-11ea-922e-d8fbe6b4aa52.png)

**Comment by raz-korn** [comment]
Hi @hearmonster ,

The Check Connection" button only checks connectivity. It does not check credentials. That's why the 307 response is OK.
When you configure the destination using BasicAuthentication you are not expected to provide them as part of the app wizard in BAS.
therefore, I suspect that the password in the destination configuration (Cockpit) should be updated to the password you use to access ES5 using Web GUI.

Regards - Raz

**Comment by hearmonster** [comment]
Thanks Raz!
I edited my Destination and re-pasted my ES5 password from my password manager (Password Depot). And it now works!

But I cna't have fat fingered the password originally - I always paste it in using my password manager.  So when I created the Destination (and pasted my password into the field) is there any possibility that setting the additional parameters screwed it up?

And another thing.  Even if my creds were wrong in the Destination.  Re-supping them during the wizard should've worked!
???

Anyhow, thanks again
