### ISSUE TITLE
Use Machine Learning to Extract Information from Documents

### ISSUE THREAD

**Issue by rvodela** [SAPDocuments/Tutorials#5696]
Tutorial URL: https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html

I'am trying this in cloud foundry trial environment
Please specify the step you are referring
When I get to oauth token I got the following error
{
    "error": "unsupported_grant_type",
    "error_description": "Unsupported grant type"
}
Image attached
![mac1](https://user-images.githubusercontent.com/6215920/90317048-8479cb80-dedb-11ea-8314-7c8caa99762b.PNG)

When I try 
/document-information-extraction/v1 I got the following error
![mac2](https://user-images.githubusercontent.com/6215920/90317076-b723c400-dedb-11ea-8a9e-1bbb03929880.PNG)

I look forward to hearing from you.
Ramesh

**Comment by Juliana-Morais** [comment]
Hi Ramesh,

This tutorial (https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html) is part of the mission https://developers.sap.com/mission.cp-aibus-extract-document-service.html. Have you followed the previous tutorials (https://developers.sap.com/tutorials/cp-aibus-dox-service-instance-booster.html and https://developers.sap.com/tutorials/cp-aibus-dox-web-oauth-token.html)? Please follow the tutorials to get the service keys and the OAuth access token. Do not use Postman.

Best regards,
Juliana

**Comment by rvodela** [comment]
Juliana
Thank you very much for your reply.  I had followed right from tutorial 1 and followed all the steps.  Can you kindly check
in the trial version if this is an issue with the trial version?.   Please let me know if you need additional information from me.
I must say that I used chrome as well as postman the result is the same (error).
Best regards
Ramesh

**Comment by Juliana-Morais** [comment]
Hi Ramesh,

I've tested the tutorials with Google Chrome and everything worked fine. I got the service keys using the booster, then I got the token, authorized Swagger and I was finally able to create a client using the  Client API with Swagger UI.

As per your second screenshot, I think I know what went wrong with you. To get the token use the url value (from inside the uaa section of the service key) + /oauth/token?grant_type=client_credentials (for example: https://b123456atrial.authentication.eu10.hana.ondemand.com/oauth/token?grant_type=client_credentials), and then use the clientid value from your service key as Username. and the clientsecret value from your service key as Password (as described in https://developers.sap.com/tutorials/cp-aibus-dox-web-oauth-token.html).

To access the Swagger UI, use the url value (from outside the uaa section of the service key) + /document-information-extraction/v1 (https://aiservices-trial-dox.cfapps.eu10.hana.ondemand.com/document-information-extraction/v1), as described in https://developers.sap.com/tutorials/cp-aibus-dox-swagger-ui.html. 

I think you were mixing the 2 tutorials and using the Swagger value ("swagger": "/document-information-extraction/v1/") instead of /oauth/token?grant_type=client_credentials to get the service keys.

Can you please try again? I'm sure if you follow the steps, you'll be able to try out the service.

Best regards,
Juliana

**Comment by rvodela** [comment]
Juliana
Thank you very much for this information.  This works.  The url was
https://3a00e9e7trial.authentication.eu10.hana.ondemand.com/oauth/token?grant_type=client_credentials&cache-control=no-cache&content-type=application/x-www-form-urlencoded
The last part was in the screen shot for Cache and urlencoded.
Recently I had written a blog on CPI  
https://blogs.sap.com/2020/07/16/integration-suite-process-integration-sap-odata-with-splitter-gather/
I was wondering if I can try out end to end ie use the document extraction from CPI to create a record in SAP.  Can you give me
any links which can help me to do this.  I feel that this will give a good idea of the benefit of this service.
Further in the trial version I dont see Data Attribute Recommendation trial in the trial entitlement - Is this going to be added any time soon.
I look forward to hearing from you.
Best regards
Ramesh

**Comment by Juliana-Morais** [comment]
Hi Ramesh,

The screenshot needs to be updated, but it is supposed to work if you use only "/oauth/token?grant_type=client_credentials" or "/oauth/token?grant_type=client_credentials&cache-control=no-cache&content-type=application/x-www-form-urlencoded".

You should be able to find links with the service related documentation in https://discovery-center.cloud.sap/#/serviceCatalog/document-information-extraction.

Data Attribute Recommendation is only available in the Europe (Frankfurt) region. If your trial subaccount is in the US region, you need to create a new subaccount in the Europe (Frankfurt) region and then you should be able to find the service plan in your Europe subaccount entitlements.

Best regards,
Juliana

**Comment by rvodela** [comment]
Juliana
Thank you very much this was very helpful.
Best regards
Ramesh
