### ISSUE TITLE
Add Service Logic to Consume Remote Address Data

### ISSUE THREAD

**Issue by pietro-henrique** [SAPDocuments/Tutorials#5728]
Tutorial URL: https://developers.sap.com/tutorials/cap-cloudsdk-5-srv-logic.html

Please specify the step you are referring to = Step 6: Start the consumer-app service

Endpoint = http://localhost:4004/catalog/Orders?$expand=address
The endpoint above gives the issue as follows:

<error xmlns="http://docs.oasis-open.org/odata/ns/metadata">
<code>null</code>
<message>An error occurred during serialization of the entity collection. An error occurred during serialization of the entity with the following key(s): ID: 64e718c9-ff99-47f1-8ca3-950c850777d4. The entity contains data for 'constructor' which does not belong to the structural or navigation properties of the type 'Addresses'.</message>
</error>

Would you guys give me some hint on how to fix it?

BR,
Pietro

**Comment by qmacro** [comment]
Hello and thank you for engaging with us. However, this tutorials issues area is for problems with the tutorial content itself (typos, incorrect screenshots, and so on) rather than challenges you may face relating to specific or general runtime circumstances. May we please refer you the [SAP Community Q&A](https://answers.sap.com) where you can tag your question to have it appear in the appropriate section, and where others will also benefit from your question, and everyone from the answers you receive. Thanks!
