### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by qmacro** [SAPDocuments/Tutorials#5740]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

In the "Consume Services" part (8) of Step 1 in this tutorial, it has the learner connect to the ES5 system. In the prerequisites for this tutorial, the tutorial "Connect SAP Cloud Platform to Your SAP Gateway Demo System Account (ES5)" is referenced explicitly. However, this referenced tutorial is Web IDE centric. The "Additional Parameters" in the destination definition (see part 5 of Step 2) explained in this referenced tutorial are related to either the Web IDE, or not explained at all. So it's a mystery to the learner which parameter(s) are needed to make the destination appear in the App Studio. 

This would benefit greatly from some explanation of the parameters and which one (or ones) are needed to surface the destinations in App Studio.

**Comment by raz-korn** [comment]
Hi DJ,

I can relate to the source of the confusion.
The decision to use SAP Web IDE parameters for BAS is due to:
- Faster time-to-market of BAS. 
- Allow smooth migration from SAP Web IDE to BAS. 

If additional explanation is needed in the "[Connect SAP Cloud Platform to Your SAP Gateway Demo System Account (ES5)](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html)" tutorial - @LindsayBert should be looped-in.

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by qmacro** [comment]
Reopening as it's not resolved. There's still no clarity (or explanation at all) as to why the parameters are Web IDE "specific" and what needs to be in place for App Studio. Either in this tutorial or the referenced tutorial - either is good, but not "neither" :-)

**Comment by MichaelCzcz** [comment]
From Raz's email:
@Bert, Lindsay should be added to the discussion in order to update the tutorial.
The information for this issue should be based on:
•	The reply I posted in the issue.
•	https://help.sap.com/viewer/9d1db9835307451daa8c930fbd9ab264/Cloud/en-US/7e49887e6fd34182bebeca5a6841a0cc.html
•	https://help.sap.com/viewer/825270ffffe74d9f988a0f0066ad59f0/CF/en-US/5c3debce758a470e8342161457fd6f70.html

**Comment by MichaelCzcz** [comment]
@LindsayBert @raz-korn Any Updates?

**Comment by LindsayBert** [comment]
Hi - I updated the tutorial about 2 weeks ago.  I added this under the destination properties step:
Note that SAP Business Application Studio reuses SAP Web IDE properties. In this way, the destination configuration as well as the migration from SAP Web IDE to SAP Business Application Studio, is much simpler.

Thanks
Lindsay

**Comment by MichaelCzcz** [comment]
@LindsayBert @qmacro Is this issue resolved and can be closed?

**Comment by LindsayBert** [comment]
Yes we can close this issue
