### ISSUE TITLE
SAP HANA XS Advanced - Asynchronous Non-Blocking I/O within Node.js SAP HANA applications

### ISSUE THREAD

**Issue by FrankAsis** [SAPDocuments/Tutorials#5745]
Tutorial URL: https://developers.sap.com/tutorials/xsa-node-async.html

Please specify the step you are referring to : **Step 7**

Hi,

Installation scenario: Hana express edition on preconfigured VM on my laptop.

Issue: upon running the web module and accessing /exerciseAsync, the message "Websocket Connection Closed" appears immediately. Pressing the buttons does nothing.

I believe the message is coded in the App.controller.js. Unfortunately i couldn't debug whats happening, i am getting a "could not connect to websockets" error when trying to debug(i have raised that question [here](https://answers.sap.com/questions/13119896/opensap-hana-7-exercise-32-debugging-xsjs-or-nodej.html) as well).

Best,

Frank

**Comment by jung-thomas** [comment]
As you have asked the question already on the SAP Community Q&A I'll close the issue here. - Actually you have the same fundamental question in two places. The other one: https://answers.sap.com/questions/13126186/opensap-hana-7-exercise-44-websocket-connection-im.html  - I commented on that already.
