### ISSUE TITLE
Feedback on Tutorial: Developing and deploying a basic Java application on SAP HANA Cloud Platform

### ISSUE THREAD

**Issue by NG4321** [SAPDocuments/Tutorials#575]
Hello,
I got each time an error, that hanatrial.ondemand.com could not be reached. It happens on step 17. I've filled all fields as shown in your tutorial.
In the screen of your step 18, there is an error message:

"Cannot reach host [https://hanatrial.ondemand.com]. Check host name for typing errors and make sure your proxy and network settings are correct"

What is here wrong?

Thanks in advance and best regards,
N.

**Comment by sonaliddesai** [comment]
Hi,

Have you tried to browse hanatrial.ondemand.com in your browser? Is it successful? And if yes, another question is do you have a developer trial account on hanatrial.ondemand.com?

**Comment by jonathanbaker7** [comment]
This has happened in several environments, usually with corporate computers (like laptops).

There are two possible issues you may be facing.  First, your certificate store in Java may be out of date, or may have been modified.  This can result in an SSL error, where the certificate is not accepted by Java (and Eclipse runs in Java).  

Second, it may also be a proxy problem at your organization.  The Eclipse system may not be using the proxy server correctly.  In that case, the proxy server is responding to the request, and since it is not the same host, Eclipse throws an error.

There are several ways to debug the problem.  First, try using a separate Java installation for Eclipse.  You can download the Java VM from Oracle (or use our internal SAP Java VM).  Then point Eclipse to this Java VM directly (using the Eclipse.ini file).  This isolated environment usually solves any Java related issues, including configuration or Certificate mismatches.  

If that doesn't solve your problem, then the issue is likely a proxy or firewall issue.  Eclipse uses port 443 to communicate with the HCP server.  Try setting the proxy settings in the Java Control panel, and see if that fixes your issue.  [More information on that here](https://java.com/en/download/help/proxy_setup.xml)

Let us know how that works out.

**Comment by jonathanbaker7** [comment]
Hi there.  I haven't heard anything back, so I'm closing this.  If you are still having a problem, please reopen it.
