### ISSUE TITLE
Get to Know the ABAP RESTful Programming Model

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Tutorials#5751]
Tutorial URL: https://developers.sap.com/tutorials/abap-environment-restful-programming-model.html

Please specify the step you are referring to: all

All information is on the slides, but the slides are illegible. Yellow on white background, light green on white and light blue on white don't hav sufficient contrast.

Whe you doubleclick the slides to see a bigger picture, the slides have no backgground whicht make it even worse.

**Comment by thecodester** [comment]
@Nuube Do you mean you can;t see the screenshots within the slides? I don;t think you are meant to see them. As for text, it appears very legible for me. On what device are you viewing them?

@mervey45 There is one serious problem: Since the slides have no background, when you enlarge the image the white background disappears and it is like an overlay and you really can;t see anything. Can you fix by creating a white background?

**Comment by mervey45** [comment]
Hi @thecodester ,

I will fix the images with a white background.
Thank you for this information, I didn't know.

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
@Nuube 
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
