### ISSUE TITLE
Build Your First Chatbot with SAP Conversational AI

### ISSUE THREAD

**Issue by linoppi** [SAPDocuments/Tutorials#5756]
Tutorial URL: https://developers.sap.com/tutorials/cai-bot-getting-started.html

Please specify the step you are referring to

Not sure which step, a symptom experienced on chat, typing "tell a joke" results in fallback... jokes don't make it to the chatbox :(

**Comment by thecodester** [comment]
@linoppi I did the entire tutorial from scratch and it worked for me. Can you provide more information: Did the test in STep 7 work? Here you can tell if the ask-joke intent is getting triggered. 

If not, can you make sure there is an intent, that there are expressions. When I forked the bot, I took the first one, but if perhaps you are not forking a good intent, you can fork this intent https://cai.tools.sap/thecodester/my-first-bot/train/intents/ask-joke  go into and click fork into your own bot.

If yes, then is the skill created, does it have @ask-joke as trigger, does it have a message set. Also make sure you have made the logical operator OR instead of AND for the triggers.

**Comment by linoppi** [comment]
@thecodester Hey thank you for your reply - the ask-joke intent is in fact triggering when I test with the debug/trace window open, I did not change from the default "AND" value to "OR" so that must be my issue, I'll try changing it today and see what happens - I'll post my results afterwards

**Comment by linoppi** [comment]
Hi @thecodester  - looks like that was all I needed! Changing those ANDs to ORs did the trick :) thanks again
