### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by mrudula1412** [SAPDocuments/Tutorials#5778]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to STEP 11-Create the database

We are facing issue while doing below step.
Do this by using the context menu on the db folder and choosing Build > Build.

We are getting below error after choosing Build > Build option.

Error-

“There is no database available. Ensure that you have a database available in space 'dev' within organization ********trial” error when trying to build DB folder.

Could you please help.

Regards,
Mrudula

**Comment by qmacro** [comment]
Hi - sorry for the delay in replying. This issues area is for problems with the tutorial content itself; for questions like yours, we would please refer you to 

Hello @mrudula1412 and thank you for engaging with us (and sorry for my tardiness in replying!). This tutorials issues area is for problems with the tutorial content itself (typos, incorrect screenshots, and so on) rather than challenges you may face relating to specific or general runtime circumstances. May we please refer you the [SAP Community Q&A](https://answers.sap.com) where you can tag your question to have it appear in the appropriate section, and where others will also benefit from your question, and everyone from the answers you receive. Thanks!

Please also note that owing to the plans regarding Neo (see below), this and related tutorials will be deprecated and replaced soon by ones for the multi-cloud environment. Thanks for your understanding!

Plan message from SAP Cloud Platform:

_To support our strategy to provide SAP Cloud Platform on a multi-cloud
foundation, SAP will move the focus of our SAP Cloud Platform trial
offering completely to the SAP Cloud Platform, multi-cloud foundation
(Cloud Foundry environment)._

_We recommend that all users of the SAP Cloud Platform trial on the SAP
Cloud Platform, Neo environment, move to the multi-cloud environment.
Existing Neo-based trial accounts will continue to be available until
November 13, 2020._

_At that point, all existing trial accounts on SAP Cloud Platform, Neo
environment, and any related data will be deleted._

_Should you have any questions, please contact
SAPCPTrialSupport@sap.com_
