### ISSUE TITLE
Integration Advisor (ICA) CF Trial Error

### ISSUE THREAD

**Issue by sequeirajosebr** [SAPDocuments/Tutorials#5815]
Hello,

After setting up the Integration Suite CF Trial: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html (and the correct Roles).

My ICA is know showing this error message on every screen:
![image](https://user-images.githubusercontent.com/52257110/92673210-f7b30980-f2f0-11ea-8fa7-6f024a143441.png)

What else should we do?

Regards.

**Comment by Vikramkulkarni01** [comment]
Hi @sequeirajosebr , 

Thanks for the feedback. 

From the screenshot, it shows the error message is because of a technical glitch. 

Could you please re-activate the ICA from manage capabilities and try again. 

If the issue seems to be persisting still, please share the following details. 

1. Global Account details 
2. Sub account details  
3. Direct application link to access ICA. 

Appreciate your support. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
