### ISSUE TITLE
Deploy Your First SAPUI5 App to Cloud Foundry

### ISSUE THREAD

**Issue by vikasgith** [SAPDocuments/Tutorials#5866]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-sapui5-create.html

Please specify the step you are referring to

Please provide an example of creating a simple SAPUI5 app without using template, i.e provide examples where user will create all required folders and files.
This will help us understand the importance of each files and folder structure.
Right now, template does lot of things, and we do not understand how things happen in BAS

**Comment by IObert** [comment]
Hi,

I can understand that you ask for such a tutorial. But I believe should guide developers along the best practice path - otherwise, developers might be confused and expect that they need to create the files manually for every project.

In case you want to learn more about the folder structure of a SAPUI5 project, have a look at [this page](https://sapui5.hana.ondemand.com/#/topic/003f755d46d34dd1bbce9ffe08c8d46a)
