### ISSUE TITLE
Create an SAP Fiori App Consuming HubSpot Data

### ISSUE THREAD

**Issue by ludanyikristof** [SAPDocuments/Tutorials#5947]
Tutorial URL: https://developers.sap.com/tutorials/cp-apim-openconnectors-create-fioriapp.html

I think that the third step, where I have to configure the destination, is misleading because the whole URL is unique and not just the user code. Maybe you should attach a picture of the API Portal, where/ on which the unique URL can be found. I tried it with your URL and with my user code and it was not working.

**Comment by shilpavij** [comment]
Dear Sender,

Thanks for your feedback, anyways the complete Web IDE is moved to SAP Business Application Studio and teams are working on it to check the integration of APIM and SAP Business Application Studio. Till the time this tutorial is dicommisioned.

Regards
shilpa

**Comment by greg2git** [comment]
Hi Shilpa,

what does this mean and is there an SAP Note to confirm this statement:

_...the complete Web IDE is moved to SAP Business Application Studio..._

sorry for being a bit dense here and thank you, gm

**Comment by thecodester** [comment]
@shilpavij Can you update this issue?

**Comment by shilpavij** [comment]
Dear Colleague,
I mean in CF we have SAP BAS and as far as I know SAP WEB IDE will be decommissioned soon. You can read about SAP BAS https://help.sap.com/viewer/9d1db9835307451daa8c930fbd9ab264/Cloud/en-US/8f46c6e6f86641cc900871c903761fd4.html?q=WEBIDE

@MichaelCzcz  can confirm since I am not from the WEB IDE team. 
As part of Integration use-cases on CF ie on SAP BAS, dev teams are working on this use-case and hence this tutorial is decommissioned as of today.
@MichaelCzcz :Kindly remove these tutorials.

I hope this helps!
Regards
Shilpa

**Comment by thecodester** [comment]
@shilpavij This tutorial is part of a mission -- is the mission doable without this tutorial?

https://developers.sap.com/mission.apim-open-connectors.html

**Comment by thecodester** [comment]
@shilpavij Is the mission up to date, with no references to Web IDE?

**Comment by thecodester** [comment]
I am closing this issue as the mission is now up to date.
