### ISSUE TITLE
Publish and Receive MQTT Messages

### ISSUE THREAD

**Issue by torbinius** [SAPDocuments/Tutorials#6084]
Tutorial URL: https://developers.sap.com/tutorials/abap-connectivity-mqtt.html

the step i am referring to: 2 "Create the MQTT Client and connect to the broker"

Thank you for the great tutorial! I have one issue: I wanted to make an optional setting of proxy with a password and a username and send this in an i_proxy object with the i_url and the i_event_handler object as described in the tutorial to the method "i_event_handler".
![issue 1](https://user-images.githubusercontent.com/73276077/97439644-b5886a80-1926-11eb-9741-f263d977504d.png)
![issue 2](https://user-images.githubusercontent.com/73276077/97439779-eb2d5380-1926-11eb-94d3-64192ab71af2.png)

But if I do it with the proxy, i get the error: "ICM_HTTP_CONNMECTION_BROKEN, connection closed. What could be my mistake?

**Comment by torbinius** [comment]
Short update: I don't know why, but the error isn't there any more :D.
However, I have another question. I wanted to see, if i am able to build a persistent session and not a clear session, so that I can recive queued messages from the broker :)
I looked into the method IF_MQTT_CLIENT~CONNECT used when establishing the connection at _lo_mqtt_client->connect( )_ and saw, that the clean session flag is automatically set on true...

![clean session](https://user-images.githubusercontent.com/73276077/97984074-8a929080-1dd6-11eb-9737-ee95d2e72f1f.png)

So, am I right, that it isn't possible to set up persistent sessions with this frame?

**Comment by frarad** [comment]
You´re right, the ABAP MQTT client does not support connections with "CleanSession=0".

The ABAP MQTT client do not offer any built-in persistence. But a persistence is needed to support QoS 2 and "CleanSession=0" properly. Especially, "CleanSession=0" requires that the client stores sent QoS 1 message that have not been completely acknowledged.
See Section 3.1.2.4 of the MQTT 3.1.1 spec:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html
or
https://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages/

In the documentation of the ABAP MQTT client it is mentioned that QoS 2 is not supported:
http://help.sap.com/viewer/05d041d3df1a4595a3c45f57c15e2325/202009.001/en-US/a183c669e48a4fdbb7c188a3ac21d3f3.html
Although the "CleanSession=0" option is not mentioned explicitly there, it is not supported for the same reason.

For robustness reasons, my suggestion is to send messages with QoS 1 until they are acknowledged. If you want to avoid duplicates (usually this is the use case for QoS 2 and "CleanSession=0"), I suggest to add a unique ID to your message payload, so that every receiver is able to detect duplicate messages.

**Comment by torbinius** [comment]
Thanks for the quick reply :)

This is a good idea: _"For robustness reasons, my suggestion is to send messages with QoS 1 until they are acknowledged. If you want to avoid duplicates (usually this is the use case for QoS 2 and "CleanSession=0"), I suggest to add a unique ID to your message payload. Then, every receiver is able to detect duplicate messages."_

Probably my last question: Is it possible to connect only one time to the broker and to hold a clean sessions and subscriptions over a long duration?

In the template ( https://help.sap.com/viewer/05d041d3df1a4595a3c45f57c15e2325/201909.001/en-US/12cb4403a7e34317b59bced8b7127a76.html) we only wait a period of time for push notifications after subscribing...

WAIT FOR PUSH CHANNELS UNTIL 
                    lo_mqtt_event_handler->mv_on_publish_message_nr > 0 AND 
                    lo_mqtt_event_handler->mo_message IS NOT INITIAL 
                    UP TO 10 SECONDS.

My goal is to recive and store messages all the time (in the background), if there are any pushed by the broker.
Do you know a smart way to implement this function?

**Comment by frarad** [comment]
The lifetime of the connection is theoretically in control of the ABAP MQTT client program, but of course restricted to the lifetime of the ABAP sessions that opens the connection. Also in the case that the peer closes the connection or the network connection breaks down, you could try to reconnect.

But as already mentioned, the MQTT connection is bound to the lifetime of the ABAP session. And hence you have to think about how to keep the ABAP session alive. You already mentioned ABAP Daemon sessions, which is one concept to achieve this. A robust ABAP session that is used as a communication proxy is exactly one of the use-cases for which ABAP Daemons have been designed. See: https://blogs.sap.com/2018/10/18/abap-daemons-always-available-abap-sessions-to-handle-events/

Btw, you probably also like to take a look at the following:
- The ABAP Channels FAQ: https://blogs.sap.com/2016/10/13/faq-abap-channels/
- The 2018 TechEd Lecture about MQTT and ABAP Daemons: https://events.sap.com/teched/en/session/41250
- The official ABAP Daemon documentation: https://help.sap.com/viewer/753088fc00704d0a80e7fbd6803c8adb/latest/en-US/311af9b769d84fffa7b7384bae27109c.html

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
