### ISSUE TITLE
Help Thomas Get Started with SAP HANA

### ISSUE THREAD

**Issue by balajisag** [SAPDocuments/Tutorials#6089]
Tutorial URL: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html

Step 6: Create database artifacts: 1. Expand the cloned folder and right-click on the db folder, and choose Build.

I have trial instance in US East (VA) region on AWS. When trying to do a build in this step it fails and I always get the same error as below. I have deleted my trial instance couple of time and tried recreating all steps from scratch and its the same result.

Can you please advise if there is an issue with the US region HANA instance which is getting deployed for users? Or am I missing something here.

11:19:36 (git) Project hana-cf-get-started-trial: Git repository hana-cf-get-started-trial: Clone request completed successfully.
11:20:40 (Executor) The "task for hdb build" process started.
11:20:40 (Executor) Started the "task for hdb build" provision.
11:21:50 (Provision) Service provisioning for module: "/db"
11:21:50 (Provision) Created the 'my-hdi' instance of the 'hana' service type for the 'hdi_db' resource.
11:21:55 (Executor) Starting process: "cd /projects/hana-cf-get-started-trial/db; export DEVX_MTA_RESOLVED_PLACEHOLDERS="{\"services\":[{\"platformName\":\"my-hdi\",\"resourceName\":\"hdi_db\",\"resourceProperties\":{},\"resourceType\":\"com.sap.xs.hdi-container\",\"serviceKeyName\":\"SharedDevKey\",\"serviceTarget\":{\"endpoint\":\"https://api.cf.us10.hana.ondemand.com\",\"org\":\"ffe7745atrial_trail-US\",\"space\":\"dev\"}}]}"; export CF_HOME=/projects/.webide/cf/64eeb57f4955f277ded3105ff710495a; export DEVX_MTA_HDI_BUILD_OPTIONS="{\"IsSelectiveBuild\":false,\"SelectedFiles\":[],\"IsSimulateBuild\":false,\"AdditionalOptions\":{\"migrationtable-development-mode\":true}}"; export PROJECT_PATH=/projects/hana-cf-get-started-trial/db; mkdir -p $CF_HOME/.cf/plugins/ && cp -u $CF_PLUGIN_PATH/config.json $CF_HOME/.cf/plugins/config.json 2>/dev/null || :;hdi-space-builder build -f /usr/local/resources/hdi-space-builder/manifest.yaml"
11:21:55 (HDB) Executing Build command:
11:21:55 (HDB)  HDI BUILDER VERSION:1.1.8-20200610150748
11:21:55 (HDB) temp folder created at: /tmp/hdispacebuilder760214117
11:21:55 (HDB) Starting pre-hdiBuild operations...
**11:22:00 (HDB) Build command failed : failed to prepare payload on pre build stage: service hdispacedeployd04b50b4-9f18-4a94-8e36-198f7b90e42c is not valid: failed install hdispacedeployd04b50b4-9f18-4a94-8e36-198f7b90e42c application: Failed to execute install command: failed to install Service: failed to push docker image service : You have exceeded the total routes for your organization's quota.
11:22:00 (HDB) Build of /hana-cf-get-started-trial/db failed due to The "task for hdb build" process finished with code 1.**

**Comment by jung-thomas** [comment]
Did you create more than one trial sub account perhaps?  This is the main error:
You have exceeded the total routes for your organization's quota.

This actually isn't anything to do with HANA directly. Its that the HDI deployer (which is a Node.js application) can't be setup to run in your target space because you have exceed your quota.  Perhaps you have already used up all of your trial quota for application runtime or routes with other work. Or perhaps you've created more than one sub account in your trial account and don't have the proper quota assigned to this secondary sub-account.  Normally you would only have one sub-account into a trial account and all your maximum quota gets assigned to it automatically.
