### ISSUE TITLE
Define a Simple Data Model and OData Service with CDS

### ISSUE THREAD

**Issue by MikeHua2019** [SAPDocuments/Tutorials#6108]
Tutorial URL: https://developers.sap.com/tutorials/odata-05-data-model-service.html

Please specify the step you are referring to:
Step 11 - Create the database
Get the error as below:
11:38:29 AM (Provision) Could not create the 'Products-Products-db-hdi-containerwXERTYdnNe24v13x' instance of the 'hana' service type for the 'Products-db-hdi-container' resource. CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker hana-broker failed with: Can not create service instance 'Products-Products-db-hdi-containerwXERTYdnNe24v13x': There is no database available. Ensure that you have a database available in space 'dev' within organization 'XXXXXX'.

please help to check it, thanks.

**Comment by qmacro** [comment]
Hello @MikeHua2019  and thank you for engaging with us (and sorry for my tardiness in replying!). This tutorials issues area is for problems with the tutorial content itself (typos, incorrect screenshots, and so on) rather than challenges you may face relating to specific or general runtime circumstances. May we please refer you the [SAP Community Q&A](https://answers.sap.com) where you can tag your question to have it appear in the appropriate section, and where others will also benefit from your question, and everyone from the answers you receive. Thanks!

Please also note that owing to the plans regarding Neo (see below), this and related tutorials will be deprecated and replaced soon by ones for the multi-cloud environment. Thanks for your understanding!

Plan message from SAP Cloud Platform:

_To support our strategy to provide SAP Cloud Platform on a multi-cloud
foundation, SAP will move the focus of our SAP Cloud Platform trial
offering completely to the SAP Cloud Platform, multi-cloud foundation
(Cloud Foundry environment)._

_We recommend that all users of the SAP Cloud Platform trial on the SAP
Cloud Platform, Neo environment, move to the multi-cloud environment.
Existing Neo-based trial accounts will continue to be available until
November 13, 2020._

_At that point, all existing trial accounts on SAP Cloud Platform, Neo
environment, and any related data will be deleted._

_Should you have any questions, please contact
SAPCPTrialSupport@sap.com_
