### ISSUE TITLE
Screenshot Update: flipped card screenshot to be put - SAP Mobile Cards

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Tutorials#6157]
Hello, 
Scenario URL: https://developers.sap.com/tutorials/cp-mobile-cards-content-actions.html

Step   5: Tap MobileCardsIcon ‘Back’ to to see the latest cards downloaded on the   device.

As we   have flipped the card in previous action, now when we have to click on back,   the screenshot should be same of flipped card only

![image](https://user-images.githubusercontent.com/66831161/98907159-6d4f7780-24e4-11eb-9cb5-5bbdde6e6ae9.png)

![image](https://user-images.githubusercontent.com/66831161/98907169-704a6800-24e4-11eb-8575-24149058bacb.png)

Thanks,
Shubham

Labels to be added:
Sprint Label: SCPTest-2010A

Scenario Label:SCPTest-mcard 
Landscape Labels: trial1, trial2, trial3
prio: low-prio

**Comment by sandeep-tds** [comment]
Hi @PriyankaShivakumar,

Thank you for your feedback. I will add the required details.
The changes will be available next week.

Warm Regards
Sandeep T D S

**Comment by thecodester** [comment]
@sandeep-tds Please let us know when this issue can be closed and changes are published?

**Comment by sandeep-tds** [comment]
Hi @i353590 

The updated tutorial has been released, can you please verify the changes and update the ticket? 
Thank you so much for your support.

@thecodester thank you for your support. The changes have been released. We can close the ticket after @i353590's inputs.

Warm Regards
Sandeep T D S

PS: The step in question may have been deleted due to the update.

**Comment by i353590** [comment]
Hello @sandeep-tds ,

Yes, after the tutorial release, the issue is resolved.
Thanks for the update :)
You may close the ticket now.


Thanks,
Shubham
