### ISSUE TITLE
Push A Sales Order Card To Your Mobile Device

### ISSUE THREAD

**Issue by QNBee** [SAPDocuments/Tutorials#6187]
Tutorial URL: https://developers.sap.com/tutorials/cp-mobile-cards-push-sales-card.html

From the second step and on the guide is not relevant, as currently there is no such tab as "Service Keys".

**Comment by sandeep-tds** [comment]
Hi @QNBee, 

Thank you for raising this issue. As mentioned in the [tutorial](https://developers.sap.com/tutorials/cp-mobile-cards-push-sales-card.html), if you don't see the Service Keys tab, please refresh the page. 

Also, please note that due to a recent release this feature is not working as expected. We are working on providing a resolution at the earliest. 

Thank you for your patience. 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
@sandeep-tds Any updates?

**Comment by sandeep-tds** [comment]
Hi @MichaelCzcz 

Thank you for the reminder. The issue has been resolved. @QNBee can you please verify the issue? 

Warm Regards
Sandeep T D S

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
