### ISSUE TITLE
Install the Cloud Connector in your System Landscape

### ISSUE THREAD

**Issue by greg2git** [SAPDocuments/Tutorials#6207]
Tutorial URL: https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html

Please specify the step you are referring to Step 3

The installation version in the tuturial is 2.11.0.3 but the tools.hana website already has 2.12.5. 

Can this tutorial be updated and also the steps to linux OS portable and installer versions be provided?

ty,gm

**Comment by greg2git** [comment]
just checking how things are going 10 days in.

**Comment by JensHaley** [comment]
Sorry for the late reply.

I can look into this, but my capacity is limited at the moment.

In step 3, the tutorial links to the [official documentation](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/57ae3d62f63440f7952e57bfcef948d3.html) for the installation on other OS than Windows. I had hoped that this was sufficient.

With regards to the new version: I provided my version to give a hint about the version with which the [whole tutorial group](https://developers.sap.com/group.cp-connectivity-odata.html) worked for me. If I started to update this tutorial to meet the new version, I would have to re-test the whole scenario and increase the versions of other components as well. I would only want to spend this effort if it is worth it, in other words, if for due to a version change the overall tutorial group does not work any longer.

Is that the case here?

**Comment by greg2git** [comment]
thank you for the documentation link  and i do realize this is extra work that may not be funded at the moment, but let me put it this way, if the tutorials were prepared for versions before the deprecation of Neo, they definitely need to be updated to work for the new BAS world, which is the closest SAP have decided to let their front end users work in a linux, however virtualized that may be. 
unless the decision has been made to let Microsoft keep the keys to the kingdom via VSCode and Windows Subsystem Linux and it can be interpreted as such, i would continue updating tutorials to be more 'linux-friendly'
thanks again for not closing the issue outright and putting this question out there.

**Comment by JensHaley** [comment]
One concern I had when writing the tutorial was that covering different OS would make it unreadable. I recently discovered that by now, the tutorial layout allows me to use tabs for each step, for example, to distinguish between a Windows installation and a Linux installation. I'll see what I can do...

At the first review of this tutorial the missing information for linux was already mentioned, so even before the changes with regards to Neo, so I see the point.

**Comment by thecodester** [comment]
I will close this issue since it doesn't directly have to do with a problem with the tutorial. @JensHaley will decide what's feasible, and otherwise you can continue the conversation in the community. Thanks.
