### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by pavanmulpur** [SAPDocuments/Tutorials#6290]
Tutorial URL: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html

Please specify the step you are referring to Step 8 

Step | Parameter | Value
-- | -- | --
A | Select a system | My SAP systems
B | Select a source | ES5 [Catalog]
C | Select a service | GWSAMPLE_BASIC

When I copy and paste the term GWSAMPLE_BASIC in the field "Select a service", I see that the NEXT button is still greyed out. Also I see two additional fields asking me to enter my User Name and Password. These two fields do not appear in the screeshot shown in Step 8 mentioned above. Nothing appears in the dropdown menu for Select a service. Please advise how do I proceed further.

**Comment by raz-korn** [comment]
Hi @pavanmulpur ,

Please refer to issue [5493](https://github.com/SAPDocuments/Tutorials/issues/5493).

Regards - Raz

**Comment by pavanmulpur** [comment]
Hi @raz-korn ,

I referred to the issue 5493. As described therein I am already logged in to ES5 system https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui?sap-client=002&sap-language=EN 
I use my I number and the password given for ES5 system to login, but then I am not getting any confirmation that I am logged in or the authentication has failed. Also I copied and pasted the value GWSAMPLE_BASIC and hit on Enter key. The NEXT button is still greyed out. No value/data appears in the field Select a Service. Please refer to the attached screenshot. 

Regards,
Pavan.

![2  Unable to login proceed to next step](https://user-images.githubusercontent.com/25876045/101348939-81ec1900-38b2-11eb-9ed2-fa1147c9a771.jpg)

**Comment by raz-korn** [comment]
Hi @pavanmulpur ,

Since in BAS you need to provide your credentials, it indicates that there are issues with the authentication.
It's probably the destination configuration in SCP Cockpit (is it configured to use Basic Authentication? Can you share screenshot of the destination configuration?), most often, the credentials. You may have updated the password in SAP GUI, but not in the destination (for example).

An additional tool to assist in locating the issue: Please refer to the following [blog](https://blogs.sap.com/2020/10/13/how-to-check-the-connectivity-to-your-backend-system-in-business-application-studio/).
Use the following: curl -v -i "ES5.dest/sap/opu/odata/iwbep/GWSAMPLE_BASIC/BusinessPartnerSet?%24top=1"

Regards - Raz

**Comment by pavanmulpur** [comment]
Hi @raz-korn,

PFA the screenshots showing destination configuration in SCP cockpit. I've checked the connection and got that 307 message. 

![3  SCP Destination](https://user-images.githubusercontent.com/25876045/101356770-97674000-38be-11eb-84e7-c362806fe1d7.jpg)
![3  SCP ES5 Connection Check](https://user-images.githubusercontent.com/25876045/101356788-9afac700-38be-11eb-85b4-aab06bd904e4.jpg)

Regards,

Pavan.

**Comment by raz-korn** [comment]
Hi @pavanmulpur ,

The destination is missing the "HTML5.DynamicDestination" additional property (value = true).
Please refer to the following [tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-gateway-connection.html).

Regards - Raz

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by pavanmulpur** [comment]
Thanks  a lot @raz-korn . I was able to fix it and complete the tutorial. 

Regards,
Pavan.
