### ISSUE TITLE
Build Skeleton React and UI5 Projects

### ISSUE THREAD

**Issue by fleischr** [SAPDocuments/Tutorials#7120]
Tutorials: https://developers.sap.com/tutorials/luigi-app-basic-setup.html
--------------------------

Step 1.5. Lots of issues trying to copy and paste these commands. Tried replacing quotations and also running commands from VS Code, Git Bash, Windows command, and Powershell with a lot of errors still taking place.

**Comment by alexandra-simeonova** [comment]
Hi, 
Thank you for the comment. We are trying to test the tutorial and find why there may be errors. In the meantime, you can try to install these Luigi examples instead: https://github.com/SAP/luigi/tree/master/core/examples

**Comment by alexandra-simeonova** [comment]
Also note that as [step 5 ](https://developers.sap.com/tutorials/luigi-app-basic-setup.html)says, `You may get a warning such as event not found, but this can safely be ignored.` Some messages that show up on the bash/terminal window are warnings instead of errors, which should have no effect on the application. If this is the issue you see, you should be able to proceed with the other steps.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Comment by fleischr** [comment]
Hi - I was able to run the commands by running each line separately. The commands ran ok - however I'm not sure they executed properly. When I get to step 7 and run npm run buildConfig I get the following error
![luigierror](https://user-images.githubusercontent.com/5488489/142509513-10dc8869-eae9-4233-ba4c-6175f164c230.PNG)

When I run node -v : v14.15.4
