### ISSUE TITLE
Help Thomas Get Started with SAP HANA Cloud

### ISSUE THREAD

**Issue by edwin7** [SAPDocuments/Tutorials#7146]
Tutorials: https://developers.sap.com/tutorials/hana-trial-advanced-analytics.html
--------------------------
a word "create" is missing

<img width="1238" alt="Screenshot 2021-11-07 at 23 45 02" src="https://user-images.githubusercontent.com/709198/140653937-e516e432-1c5d-4da7-b4e2-a876f825ac43.png">

**Comment by jung-thomas** [comment]
No actually adding CREATE would be incorrect.  With hdbgraphworkspace (like all the HDI artifacts) you leave the SQL verb off since the same design time artifact is used for both create and update of the objects. 
https://help.sap.com/viewer/c2cc2e43458d4abda6788049c58143dc/2021_3_QRC/en-US/ff893731c8514b098223e4a47a6d5f39.html

**Comment by edwin7** [comment]
Thank you Thomas for the info. I might have the old version of SAP HANA Cloud
<img width="968" alt="Screenshot 2021-11-09 at 09 30 03" src="https://user-images.githubusercontent.com/709198/140850830-bc2bcc5b-8503-471b-aeae-e720b8dff12b.png">

**Comment by jung-thomas** [comment]
No you putting the content in the wrong spot. You are in a SQL Console Editor.  The instructions in the tutorial say:
_creating a file with the extension hdbgraphworkspace (and be sure to Deploy again)_

You should be creating a design time artifact with the above referenced file extension in your project not in the Database Explorer console.

**Comment by edwin7** [comment]
Thanks Thomas!
