### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by nikegup** [SAPDocuments/Tutorials#7159]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi,
I was following the tutorial to build for my own project in a production environment. The steps which I had successfully done were:-
1. Created a CAP application
2. Added a Fiori App to the CAP application
3. Added Authentication to the CAP application
4. Deployed the Same on the cloud and the Entity for which I had enabled security. It gave an "Unauthorized" error.

While going to the next step
The srv and db are staged, however the app is not being staged and giving an error.
This is the error which I am getting:-
![image](https://user-images.githubusercontent.com/68983907/140729996-b841f0cc-5ddc-4047-a016-063dcabcdfe9.png)

Uploading the logs as well
[circtwo-srv.log](https://github.com/SAPDocuments/Tutorials/files/7496405/circtwo-srv.log)
[OPERATION.log](https://github.com/SAPDocuments/Tutorials/files/7496406/OPERATION.log)
[circtwo-app-content_circtwo-html5-repo-host.log](https://github.com/SAPDocuments/Tutorials/files/7496409/circtwo-app-content_circtwo-html5-repo-host.log)
[circtwo-db-deployer.log](https://github.com/SAPDocuments/Tutorials/files/7496410/circtwo-db-deployer.log)
[circtwo-destinations_circtwo-destination.log](https://github.com/SAPDocuments/Tutorials/files/7496411/circtwo-destinations_circtwo-destination.log)

**Comment by slavipande** [comment]
Hi @nikegup,

Thanks for your feedback!

These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question is more general since it involves deployment to a production landscape and not documented or suggested app modifications. As such, it would likely get more visibility and a better answer in the SAP Community's [Questions & Answers](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).

Best regards,
Svetoslav
