### ISSUE TITLE
Set Up SAP Web Analytics

### ISSUE THREAD

**Issue by jkbschmid** [SAPDocuments/Tutorials#7172]
Tutorials: https://developers.sap.com/tutorials/cp-webanalytics-setup.html
--------------------------

Step 6 should be updated, since Default Identity Provider is not clickable anymore.
See https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/31532c77bd61421e9d40d100fd75ef52.html

**Comment by Vikramkulkarni01** [comment]
Hi @jkbschmid , 

Thanks for reaching out to us and notifying this issue. 

We are completely revamping this step as per the latest update in the BTP cockpit. You no longer required to assign the role collections from the **Trust configuration**. You can directly assign users while creating role collection itself. 

The changes will be available to you shortly. 

Since there are no actions required from our end. We are closing this case. 

Thanks for your patience and truly appreciate your support. 

Regards, 
Vikram Kulkarni

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
