### ISSUE TITLE
Set Up Postman Client for SAP AI Core

### ISSUE THREAD

**Issue by SCHELLK** [SAPDocuments/Tutorials#7192]
Tutorials: https://developers.sap.com/tutorials/ai-core-aiapi-postman-setup.html
--------------------------

In step 4 the service key variable ML_API_URL needs to be changed to AI_API_URL

**Comment by dhrubpaul** [comment]
Hi Michael,
Please can you forward any queries or issues of the following groups
https://developers.sap.com/group.ai-core-aiapi-clientsdk-get-started.html
https://developers.sap.com/group.ai-core-aiapi-postman-get-started.html

to  ***@***.******@***.***> during my absence for the next two weeks.

Thanks,
Dhrub
From: Michael Czadankiewicz ***@***.***>
Reply to: SAPDocuments/Tutorials ***@***.***>
Date: Monday, 15 November 2021 at 1:14 PM
To: SAPDocuments/Tutorials ***@***.***>
Cc: Dhrubajyoti Paul ***@***.***>, Assign ***@***.***>
Subject: Re: [SAPDocuments/Tutorials] Set Up Postman Client for SAP AI Core (Issue #7192)


Assigned #7192<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSAPDocuments%2FTutorials%2Fissues%2F7192&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937675381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wqg3lun0yxD2hGzLnh5%2Fyyeo%2ByAvcKglcUy%2BwP7YOaA%3D&reserved=0> to @dhrubpaul<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdhrubpaul&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937685332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FIDdDrfpVbZtcMFdK82YYdVdvf%2FqUKvESqRFqt1aHdA%3D&reserved=0>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSAPDocuments%2FTutorials%2Fissues%2F7192%23event-5616212026&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937685332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i13%2FqnVwwJtL%2FYghZl%2Bmc0vN9iNeH0%2FvMQH%2FvFbYNcQ%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVZL7UH42LWO4FQCLTTGRE3UMC27HANCNFSM5H6QWXQA&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937695290%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P5SXUefZNr%2FB99zlLUDNdwa1tAzGahY%2FURyGqGhf%2BOA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937715211%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2FUAGd%2Bd7YFxJpSXKzDUg8H%2FfcXpYjKLD3SS4RAIpWg%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdhrubajyoti.paul%40sap.com%7C2aff786a4cae43d0f94008d9a80bcf09%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C637725590937725172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q68wqmdhCuNrGEOT%2FHZmkTWMKiTLnjyJCojL%2FNm3bUU%3D&reserved=0>.

**Comment by LunaticMaestro** [comment]
@SCHELLK Thank you for notifying, we have made the suggested changes.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
