### ISSUE TITLE
Create a Simple ABAP CDS View in ADT

### ISSUE THREAD

**Issue by dantizpal** [SAPDocuments/Tutorials#7197]
Tutorials: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html
--------------------------
I checked and only found SEPM_DG_OIA report, the other report is missing, even the tasklist has no EMP entry.

stc01
missing in the lasklist SAP_BASIS_EPM_OIA_CONFIG, found only 141 entries.

The only program found related to EPM is RS_EPM_DGC_HANA, the program mentioned SEPM_DG_OIA_NEW does not exist.

Managed to look inside the HDB database, looking for the CONTENT, the is a tree for "sap-bc-epm-oi" but maybe is not mapped to the ABAP schema,

Docker image is  store/saplabs/abaptrial:1909, opened ports and have access to HANA SYSTEMDB and TENANT.

Write here how you think we can improve the tutorial ...

**Comment by julieplummer20** [comment]
Hi Dantizpal,
Thanks for that. I will look into it at once.
BR Julie.

**Comment by julieplummer20** [comment]
Hi dantzipal, 
I have just run SEPM_DG_OIA : I get 100 000 sales oreders (149,05 s).

What happens when you do this? 
What messages / error messages do you get?
If you get the same result as me, I will clarify the text accordingly.
Thanks Julie.

![Snag_168d346](https://user-images.githubusercontent.com/22739917/142206896-e9603482-42c6-4c62-b555-b9cf56ebb27a.png)
![Snag_168bc05](https://user-images.githubusercontent.com/22739917/142206877-3e426474-1d75-48af-8983-f85e59631ec8.png)

**Comment by dantizpal** [comment]
This view "sepm_sddl_so_invoice_item" does not exists, the tasklist "SAP_BASIS_EPM_OIA_CONFIG" does not exist. We can't complete this excercise as the Docker image is not complete.
store/saplabs/abaptrial:1909

This is the only program found "SEPM_DG_OIA" but it does not create the CDS View  "sepm_sddl_so_invoice_item".
Should we work with another docker Image??

**Comment by julieplummer20** [comment]
Hi Dantzipal, No, this is the most up-to-date docker image.
I will look into this and get back to you.
Thanks for flagging this.
BR Julie.

**Comment by julieplummer20** [comment]
Hi Dantzipal, I'm sorry for the delay.
But I've just checked: sepm_sddl_so_INVOICE_ITEM is included in my Docker image
![Snag_13cf9df](https://user-images.githubusercontent.com/22739917/143245931-8fa33980-2a0b-4026-8323-54aebb7c7953.png)
Note that it's a data definition, not a transparent table.

I cannot understand why my image includes this data definition and yours does not. 
Since we have just uploaded a brand new image to Docker, I will download it, check it out and let you know.

I apologize for the inconvenience, but this is a very strange issue.
BR Julie.
:

**Comment by julieplummer20** [comment]
Hi Dantzipal, I'm sorry for the delay.
But I've just checked: sepm_sddl_so_INVOICE_ITEM is included in my Docker image

![Snag_144914b](https://user-images.githubusercontent.com/22739917/143247220-fa2648c9-af36-48d8-b76b-43d6d682fa14.png)

Note that it's a data definition, not a table.

I cannot understand why my image includes this data definition and yours does not.
Since we have just uploaded a brand new image to Docker, I will download it, check it out and let you know.

I apologize for the inconvenience, but this is a very strange issue.
BR Julie.

**Comment by julieplummer20** [comment]
Hi,
I've just logged into the newest version of SAP ABAP Platform 1909 Dev Edition on Docker. 
sepm_sddl_so_INVOICE_ITEM is definitely there:
![Snag_b50d4d](https://user-images.githubusercontent.com/22739917/143436395-55c0e14c-ed57-4ed0-a2fb-271da5198ef7.png)

I would suggest you download the newest version.  I can think of no other explanation.
BR Julie.

**Comment by dantizpal** [comment]
julieplummer20

Found that i was creating de data definition in a package and not the $TMP, just completed the example using only the $TMP and the view is there " sepm_sddl_so_INVOICE_ITEM ". I am trying to understand why this is not allowed, as my package is just to keep the examples in a tidy place.

Conclusion 
Create again all the examples using only the $TMP.

**Comment by dantizpal** [comment]
Thanks a lot for your efforts.

**Comment by julieplummer20** [comment]
Hi dantzipal, This should work:
![image](https://user-images.githubusercontent.com/22739917/144225451-04a88cca-38e0-41d7-99f6-8a3ab10c0fd2.png)

However, it does not seem to be a bug in the dev ed system. Your best bet is probably to create a question in the ABAP Development Forum: [SAP Community Forum : ABAP Development](https://answers.sap.com/tags/833755570260738661924709785639136)

I'm sorry this could not be resolved.
Best wishes,
Julie.
