### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by rafaellyrat** [SAPDocuments/Tutorials#7213]
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi!
I receive the error below on executing the point two of Step 8: Deploy the integration flow:
Deployment StatusDeployedNavigate to Manage Integration ContentRuntime StatusErrorDeployed Byrafael.lyra@seidor.com.brDeployed OnNov 17, 2021, 06:44:51Deployed Version1.0.0Error Message[CONTENT][CONTENT_DEPLOY][InstanceError] : {"message":"EXCEPTION","parameters":["org.apache.camel.FailedToCreateRouteException: Failed to create route Process_1 at: >>> SetHeader[productIdentifier, xpath{//productIdentifier}] <<< in route: Route(Process_1)[[From[sap-http:foo?maximumBodySize=40&urlPa... because of java.lang.ClassNotFoundException: java.lang.string"],"childMessageInstances":[{"message":"CAUSE","parameters":["org.apache.camel.RuntimeCamelException: java.lang.ClassNotFoundException: java.lang.string"],"childMessageInstances":[{"message":"CAUSE","parameters":["java.lang.ClassNotFoundException: java.lang.string"]}]}]}

Can you help to solve this error please?

Thanks!

Rafael.

**Comment by Karunaharan** [comment]
Hi @rafaellyrat
The deployment process is unable to create an endpoint because an endpoint already exists with the same Address used in the HTTP sender adapter. I guess you have another iflow in your tenant using the same Address (/products/details). If so, you won't be able to deploy since there will be a conflict in the endpoints. Please remove one of the iflows or change the Address in the other iflow.

Hope this helps.

@MichaelCzcz - please close the issue.
