### ISSUE TITLE
Subscribe to the Low-Code / No-Code Service in SAP BTP

### ISSUE THREAD

**Issue by mathit** [SAPDocuments/Tutorials#7302]
Tutorials: https://developers.sap.com/tutorials/appgyver-subscribe-service.html
--------------------------

This is one of the newest tutorials and only Cloud Foundry EU10 has the booster available.
But the region EU10 is not available anymore for new trial accounts
https://answers.sap.com/questions/13508076/sap-hana-cloud-trial-cf-eu10-no-longer-available.html

Can you make it so that the booster is available on other regions?

**Comment by heytombeck** [comment]
Thanks for your question.  The SAP AppGyver service offered through the SAP BTP is currently a paid service, which is why it can only be accessed through EU10 currently. However, it is still possible to follow the subsequent tutorials using the AppGyver community edition (www.sapappgyver.com). This is a free service and the feature set supports this use case. There are slight UI changes, but often this is color scheme differences or buttons that are in different places but appear on the same page. Hope that helps.

**Comment by mathit** [comment]
Ok, thanks you fast response. I will try via https://www.appgyver.com/

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
