### ISSUE TITLE
Feedback on Tutorial: Installing the VM Image

### ISSUE THREAD

**Issue by stealth70mde** [SAPDocuments/Tutorials#964]
Hello,

I have been trying to download the VM Image (Server+Apps) about 5 times and it always crashes between 85-90%. If I continue, it will resume to 100% only to say that the download failed at the end.

I wasted about 35GB+ of bandwidth today. HXEDownloadManager Program on Windows says to check the logs but there aren't any.

Is there a way to download the image directly without passing by the download manager?

The exact message is: "Failed to download HANA express edition virtual machine. Check log for error and retry download".

My hard disk has more than 1TB of free space...

**Comment by a1kannan** [comment]
Hi
Can you check if there are any partial download files left in your download folder (e.g. files looks like hxe.ova.001, hxe.ova.002 etc.,)? If so, can you clean them up and restart?
Also, are you seeing this issue downloading hxe.ova or hxexsa.ova? If it is the latter, were the former downloaded successfully.

If you pick the 'other' link instead of 'windows' link after registering - does it help?

There is no way to directly download the files  that I know of at this time.

**Comment by stealth70mde** [comment]
Hello,
I removed the partial downloads (there were 8 files) after I noticed that keeping them didn't help finish the download properly. So I clean them up and the download restarted from 0% and was not able to complete (80-90%) before the error message that the download failed.

I had no problem downloading the hxe.osa (2GB). 
I only have problems downloading the hxexsa.ova (8GB).

I didn't try the 'Other' link. I might give that a try but it will be difficult this week as I am travelling. 

Thanks for your support.

**Comment by stealth70mde** [comment]
I was finally able to download hxexsa.osa using the 'Other' selection (JAR File) after my second attempt.

Not sure what cause it to fail but there was one of temp files that seemed to be stuck while downloading as, after a little while, the size stopped changing. Eventually it failed.
